# Licensed under the HealthPorta Non-Commercial License (see LICENSE).

"""Standalone contracts and later runtime components for custom imports."""

from process.custom_import.capture import (
    CaptureError,
    CaptureLimits,
    CaptureManifest,
    DecodedRecord,
    SealedCapture,
    capture_stream,
    iter_records,
    verify_capture,
)
from process.custom_import.definition import (
    CONTRACT_VERSION,
    CustomImportDefinition,
    DefinitionError,
    canonical_json,
    canonical_sha256,
    load_json_definition,
    load_yaml_definition,
)
from process.custom_import.family import (
    CandidateRejected,
    FamilyBuildResult,
    FamilyRejection,
    SourceSnapshotError,
    assemble_root_families,
    merge_families,
    validate_source_snapshot_tokens,
)
from process.custom_import.materialization import (
    ChildScalarProjection,
    ChildScalarTarget,
    DefinitionIdentity,
    GenerationIdentity,
    MaterializedWinner,
    RootScalarProjection,
    RootScalarTarget,
    ScalarProjectionError,
    TypedScalar,
    ValidatedWinnerCandidateStream,
    WinnerCandidate,
    WinnerMaterialization,
    WinnerMaterializationError,
    materialize_winners,
    persist_scalar_projections,
    persist_selection_profiles,
    persist_winner_materialization,
    project_child_scalars,
    project_root_scalars,
    scalar_projection_models,
    selection_profile_models,
    winner_materialization_models,
)

__all__ = (
    "CONTRACT_VERSION",
    "CandidateRejected",
    "CaptureError",
    "CaptureLimits",
    "CaptureManifest",
    "ChildScalarProjection",
    "ChildScalarTarget",
    "CustomImportDefinition",
    "DefinitionIdentity",
    "DecodedRecord",
    "DefinitionError",
    "FamilyBuildResult",
    "FamilyRejection",
    "GenerationIdentity",
    "MaterializedWinner",
    "RootScalarProjection",
    "RootScalarTarget",
    "ScalarProjectionError",
    "SealedCapture",
    "SourceSnapshotError",
    "TypedScalar",
    "ValidatedWinnerCandidateStream",
    "WinnerCandidate",
    "WinnerMaterialization",
    "WinnerMaterializationError",
    "assemble_root_families",
    "canonical_json",
    "canonical_sha256",
    "capture_stream",
    "iter_records",
    "load_json_definition",
    "load_yaml_definition",
    "materialize_winners",
    "merge_families",
    "persist_scalar_projections",
    "persist_selection_profiles",
    "persist_winner_materialization",
    "project_child_scalars",
    "project_root_scalars",
    "scalar_projection_models",
    "selection_profile_models",
    "validate_source_snapshot_tokens",
    "verify_capture",
    "winner_materialization_models",
)
