# Licensed under the HealthPorta Non-Commercial License (see LICENSE).

"""Compatibility exports for the custom-import v1 contract boundary."""

from process.custom_import.capture import (
    CaptureError,
    CaptureLimits,
    CaptureManifest,
    DecodedRecord,
    SealedCapture,
    capture_stream,
    iter_records,
    verify_capture,
)
from process.custom_import.definition import (
    CONTRACT_VERSION,
    ChildCollection,
    CustomImportDefinition,
    DefinitionError,
    Field,
    FieldAlias,
    KeyPart,
    QueryContract,
    SelectionProfile,
    SortTerm,
    SourceStream,
    canonical_json,
    canonical_sha256,
    load_json_definition,
    load_yaml_definition,
)
from process.custom_import.family import (
    CandidateRejected,
    FamilyBuildResult,
    FamilyRejection,
    RootFamily,
    SourceSnapshotError,
    assemble_root_families,
    merge_families,
    validate_source_snapshot_tokens,
)

__all__ = (
    "CONTRACT_VERSION",
    "CaptureError",
    "CaptureLimits",
    "CaptureManifest",
    "CandidateRejected",
    "ChildCollection",
    "CustomImportDefinition",
    "DecodedRecord",
    "DefinitionError",
    "FamilyBuildResult",
    "FamilyRejection",
    "Field",
    "FieldAlias",
    "KeyPart",
    "QueryContract",
    "RootFamily",
    "SealedCapture",
    "SelectionProfile",
    "SortTerm",
    "SourceSnapshotError",
    "SourceStream",
    "assemble_root_families",
    "capture_stream",
    "canonical_json",
    "canonical_sha256",
    "load_json_definition",
    "load_yaml_definition",
    "iter_records",
    "merge_families",
    "validate_source_snapshot_tokens",
    "verify_capture",
)
