"""Schema fixtures for private PTG layout-candidate PostgreSQL proofs."""

from sqlalchemy import text

from process.ptg_parts import ptg2_shared_gc
from process.ptg_parts.ptg2_shared_blocks import PTG2_V3_DENSE_LAYOUT_TABLES


class _SessionExecutor:
    def __init__(self, session) -> None:
        self.session = session

    async def all(self, statement, **params):
        result = await self.session.execute(text(statement), params)
        return result.all()

    async def status(self, statement, **params):
        result = await self.session.execute(text(statement), params)
        return result.rowcount


async def _create_layout_identity_tables(connection, schema: str) -> None:
    for statement in (
        f"""
            CREATE TABLE {schema}.ptg2_v3_snapshot_layout (
                snapshot_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                storage_shard_id smallint NOT NULL DEFAULT 0,
                build_token varchar(96) NOT NULL,
                generation varchar(32) NOT NULL,
                state varchar(16) NOT NULL,
                mapping_digest bytea,
                support_digest bytea,
                layout_manifest jsonb NOT NULL DEFAULT '{{}}'::jsonb,
                logical_byte_count bigint NOT NULL DEFAULT 0,
                created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
                heartbeat_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
                lease_until timestamptz,
                published_at timestamptz
            )
        """,
        f"""
            CREATE UNIQUE INDEX layout_sealed_mapping_idx
                ON {schema}.ptg2_v3_snapshot_layout
                   (generation, mapping_digest, support_digest)
             WHERE state = 'sealed'
               AND mapping_digest IS NOT NULL
               AND support_digest IS NOT NULL
        """,
        f"""
            CREATE TABLE {schema}.ptg2_v3_layout_fingerprint (
                semantic_fingerprint bytea PRIMARY KEY,
                snapshot_key bigint NOT NULL REFERENCES
                    {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE CASCADE,
                created_at timestamptz NOT NULL DEFAULT transaction_timestamp()
            )
        """,
    ):
        await connection.execute(text(statement))


async def _create_layout_candidate_tables(connection, schema: str) -> None:
    for statement in (
        f"""
            CREATE TABLE {schema}.ptg2_layout_build_candidate (
                snapshot_key bigint PRIMARY KEY REFERENCES
                    {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE CASCADE,
                semantic_fingerprint bytea NOT NULL,
                created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
                cleanup_pending_at timestamptz,
                canonical_snapshot_key bigint,
                CHECK (
                    (cleanup_pending_at IS NULL AND canonical_snapshot_key IS NULL)
                    OR
                    (cleanup_pending_at IS NOT NULL
                     AND canonical_snapshot_key IS NOT NULL
                     AND canonical_snapshot_key <> snapshot_key)
                )
            )
        """,
        f"""
            CREATE INDEX layout_candidate_fingerprint_idx
                ON {schema}.ptg2_layout_build_candidate
                   (semantic_fingerprint, snapshot_key)
        """,
        f"""
            CREATE TABLE {schema}.ptg2_v3_snapshot_binding (
                snapshot_id varchar(160) PRIMARY KEY,
                snapshot_key bigint NOT NULL REFERENCES
                    {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE RESTRICT
            )
        """,
    ):
        await connection.execute(text(statement))


async def _create_layout_block_tables(connection, schema: str) -> None:
    for statement in (
        f"""
            CREATE TABLE {schema}.ptg2_v3_block (
                block_hash bytea PRIMARY KEY,
                stored_byte_count bigint NOT NULL
            )
        """,
        f"""
            CREATE TABLE {schema}.ptg2_v3_snapshot_block (
                snapshot_key bigint NOT NULL REFERENCES
                    {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE CASCADE,
                block_hash bytea NOT NULL REFERENCES
                    {schema}.ptg2_v3_block(block_hash) ON DELETE RESTRICT
            )
        """,
        f"""
            CREATE TABLE {schema}.ptg2_v3_gc_candidate (
                block_hash bytea PRIMARY KEY,
                eligible_at timestamptz NOT NULL,
                queued_at timestamptz NOT NULL
            )
        """,
    ):
        await connection.execute(text(statement))
    for table_name in PTG2_V3_DENSE_LAYOUT_TABLES:
        await connection.execute(
            text(
                f'CREATE TABLE {schema}."{table_name}" '
                "(snapshot_key bigint NOT NULL)"
            )
        )


async def create_layout_tables(connection, schema: str) -> None:
    """Create the private-candidate schema in production statement order."""
    await _create_layout_identity_tables(connection, schema)
    await _create_layout_candidate_tables(connection, schema)
    await _create_layout_block_tables(connection, schema)


async def _insert_v4_cleanup_winner(
    session,
    schema: str,
    generation: str,
) -> int:
    winner_key = await session.scalar(
        text(
            f"""
            INSERT INTO {schema}.ptg2_v3_snapshot_layout
                (build_token, generation, state, mapping_digest,
                 support_digest, lease_until, published_at)
            VALUES ('v4-winner', :generation, 'sealed', :mapping_digest,
                    :support_digest,
                    transaction_timestamp() + INTERVAL '6 hours',
                    transaction_timestamp())
            RETURNING snapshot_key
            """
        ),
        {
            "generation": generation,
            "mapping_digest": b"m" * 32,
            "support_digest": b"s" * 32,
        },
    )
    return int(winner_key)


async def seed_v4_duplicate_cleanup_pair(
    sessions,
    schema: str,
    *,
    generation: str,
) -> tuple[int, int]:
    """Seed one sealed winner and one dense, unbound V4 loser candidate."""

    fingerprint = b"v" * 32
    async with sessions.begin() as session:
        winner_key = await _insert_v4_cleanup_winner(
            session,
            schema,
            generation,
        )
        loser_key = await session.scalar(
            text(
                f"""
                INSERT INTO {schema}.ptg2_v3_snapshot_layout
                    (build_token, generation, state, lease_until)
                VALUES ('v4-loser', :generation, 'building',
                        transaction_timestamp() + INTERVAL '6 hours')
                RETURNING snapshot_key
                """
            ),
            {"generation": generation},
        )
        await session.execute(
            text(
                f"INSERT INTO {schema}.ptg2_v3_layout_fingerprint "
                "(semantic_fingerprint, snapshot_key) "
                "VALUES (:fingerprint, :snapshot_key)"
            ),
            {"fingerprint": fingerprint, "snapshot_key": winner_key},
        )
        await session.execute(
            text(
                f"INSERT INTO {schema}.ptg2_layout_build_candidate "
                "(snapshot_key, semantic_fingerprint) "
                "VALUES (:snapshot_key, :fingerprint)"
            ),
            {"snapshot_key": loser_key, "fingerprint": fingerprint},
        )
        await session.execute(
            text(
                f'INSERT INTO {schema}."{PTG2_V3_DENSE_LAYOUT_TABLES[0]}" '
                "(snapshot_key) SELECT :snapshot_key FROM generate_series(1, 3)"
            ),
            {"snapshot_key": loser_key},
        )
    return int(loser_key), int(winner_key)


async def _release_v4_cleanup_batch(
    sessions,
    schema_name: str,
    schema: str,
    loser_key: int,
):
    async with sessions.begin() as session:
        stats = await ptg2_shared_gc._release_layouts_ready(
            _SessionExecutor(session),
            schema_name=schema_name,
            building_max_age_seconds=21_600,
            grace_seconds=0,
            max_layouts=1,
            layout_keys=(loser_key,),
            dense_batch_rows=1,
        )
    async with sessions() as observer:
        remaining_rows = await observer.scalar(
            text(
                f'SELECT COUNT(*) FROM {schema}."'
                f'{PTG2_V3_DENSE_LAYOUT_TABLES[0]}" '
                "WHERE snapshot_key = :snapshot_key"
            ),
            {"snapshot_key": loser_key},
        )
    return stats, int(remaining_rows)


async def verify_v4_cleanup_replay(
    sessions,
    schema_name: str,
    schema: str,
    loser_key: int,
    winner_key: int,
) -> None:
    """Prove bounded cleanup commits progress and exact-replays to zero."""

    logical_counts: list[int] = []
    remaining_counts: list[int] = []
    for _attempt in range(3):
        stats, remaining = await _release_v4_cleanup_batch(
            sessions,
            schema_name,
            schema,
            loser_key,
        )
        logical_counts.append(stats.logical_layout_count)
        remaining_counts.append(remaining)
    replay_stats, _remaining = await _release_v4_cleanup_batch(
        sessions,
        schema_name,
        schema,
        loser_key,
    )
    assert logical_counts == [0, 0, 1]
    assert remaining_counts == [2, 1, 0]
    assert replay_stats.logical_layout_count == 0
    async with sessions() as observer:
        surviving_keys = tuple(
            (await observer.scalars(
                text(
                    f"SELECT snapshot_key FROM {schema}.ptg2_v3_snapshot_layout "
                    "ORDER BY snapshot_key"
                )
            )).all()
        )
    assert surviving_keys == (winner_key,)


async def install_legacy_layout_candidate_fixture(
    connection,
    schema: str,
) -> None:
    """Install the exact mixed-version pre-migration candidate state."""
    await connection.execute(
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_layout (
            snapshot_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            storage_shard_id smallint NOT NULL DEFAULT 0,
            build_token varchar(96) NOT NULL,
            generation varchar(32) NOT NULL,
            state varchar(16) NOT NULL,
            mapping_digest bytea,
            support_digest bytea,
            layout_manifest jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            logical_byte_count bigint NOT NULL DEFAULT 0,
            created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
            heartbeat_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
            lease_until timestamptz,
            published_at timestamptz
        );
        CREATE UNIQUE INDEX layout_upgrade_sealed_mapping_idx
            ON {schema}.ptg2_v3_snapshot_layout
               (generation, mapping_digest, support_digest)
         WHERE state = 'sealed'
           AND mapping_digest IS NOT NULL
           AND support_digest IS NOT NULL;
        CREATE TABLE {schema}.ptg2_v3_layout_fingerprint (
            semantic_fingerprint bytea PRIMARY KEY,
            snapshot_key bigint NOT NULL REFERENCES
                {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE CASCADE,
            created_at timestamptz NOT NULL DEFAULT transaction_timestamp()
        );
        INSERT INTO {schema}.ptg2_v3_snapshot_layout
            (snapshot_key, build_token, generation, state, lease_until)
        VALUES (41, 'old-source', 'shared_blocks_v3', 'building',
                transaction_timestamp() + INTERVAL '6 hours');
        INSERT INTO {schema}.ptg2_v3_layout_fingerprint
            (semantic_fingerprint, snapshot_key)
        VALUES (decode(repeat('41', 32), 'hex'), 41);
        CREATE TABLE {schema}.ptg2_v3_snapshot_binding (
            snapshot_id varchar(160) PRIMARY KEY,
            snapshot_key bigint NOT NULL REFERENCES
                {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE RESTRICT
        );
        """
    )


async def upgrade_and_assert_live_candidate_adoption(
    connection,
    schema: str,
    migration,
    statements: list[str],
) -> None:
    """Apply the migration and verify old and newly-triggered adoption."""
    migration.upgrade()
    for statement in statements:
        await connection.execute(statement)
    adopted = await connection.fetchrow(
        f"SELECT candidate.snapshot_key, "
        f"encode(candidate.semantic_fingerprint, 'hex') AS fingerprint, "
        f"EXISTS (SELECT 1 FROM {schema}.ptg2_v3_layout_fingerprint "
        f"WHERE snapshot_key = candidate.snapshot_key) AS legacy_index_retained "
        f"FROM {schema}.ptg2_layout_build_candidate AS candidate"
    )
    assert dict(adopted) == {
        "snapshot_key": 41,
        "fingerprint": "41" * 32,
        "legacy_index_retained": True,
    }
    await connection.execute(
        f"INSERT INTO {schema}.ptg2_v3_snapshot_layout "
        f"(snapshot_key, build_token, generation, state, lease_until) "
        f"VALUES (42, 'old-after-upgrade', 'shared_blocks_v3', 'building', "
        f"transaction_timestamp() + INTERVAL '6 hours'); "
        f"INSERT INTO {schema}.ptg2_v3_layout_fingerprint "
        f"(semantic_fingerprint, snapshot_key) "
        f"VALUES (decode(repeat('42', 32), 'hex'), 42);"
    )
    assert await connection.fetchval(
        f"SELECT COUNT(*) FROM {schema}.ptg2_layout_build_candidate "
        f"WHERE snapshot_key = 42 "
        f"AND semantic_fingerprint = decode(repeat('42', 32), 'hex') "
        f"AND cleanup_pending_at IS NULL"
    ) == 1
    await connection.execute(
        f"DELETE FROM {schema}.ptg2_v3_snapshot_layout WHERE snapshot_key = 42"
    )


async def assert_migration_candidate_cleanup(
    connection,
    schema: str,
    canonical_snapshot_key: int,
) -> None:
    """Assert the old candidate durably targets the canonical winner."""
    cleanup = await connection.fetchrow(
        f"SELECT cleanup_pending_at IS NOT NULL AS cleanup_pending, "
        f"canonical_snapshot_key FROM {schema}.ptg2_layout_build_candidate "
        f"WHERE snapshot_key = 41"
    )
    assert dict(cleanup) == {
        "cleanup_pending": True,
        "canonical_snapshot_key": canonical_snapshot_key,
    }
    assert await connection.fetchval(
        f"SELECT COUNT(*) FROM {schema}.ptg2_v3_layout_fingerprint"
    ) == 1


async def assert_candidate_migration_downgrade(
    connection,
    schema_name: str,
    migration,
    statements: list[str],
) -> None:
    """Drain adopted candidates, then verify the exact-empty downgrade."""
    await connection.execute(
        f'DELETE FROM "{schema_name}".ptg2_layout_build_candidate'
    )
    downgrade_offset = len(statements)
    migration.downgrade()
    for statement in statements[downgrade_offset:]:
        await connection.execute(statement)
    assert await connection.fetchval(
        "SELECT to_regclass($1)",
        f"{schema_name}.ptg2_layout_build_candidate",
    ) is None
    assert await connection.fetchval(
        "SELECT COUNT(*) FROM pg_proc AS procedure "
        "JOIN pg_namespace AS namespace "
        "ON namespace.oid = procedure.pronamespace "
        "WHERE namespace.nspname = $1 "
        "AND procedure.proname = "
        "'ptg2_capture_building_layout_fingerprint'",
        schema_name,
    ) == 0
