# Licensed under the HealthPorta Non-Commercial License (see LICENSE).

from __future__ import annotations

from process.ptg_parts import ptg2_shared_gc as shared_gc
from tests.ptg2_v4_migration_catalog_support import (
    attempt_guard_prerequisite_ddl,
)


async def _create_layout_identity_tables(connection, schema: str) -> None:
    for ddl in (
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_layout (
            snapshot_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            storage_shard_id smallint NOT NULL DEFAULT 0,
            build_token varchar(96) NOT NULL,
            generation varchar(32) NOT NULL,
            state varchar(16) NOT NULL,
            mapping_digest bytea,
            support_digest bytea,
            layout_manifest jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            logical_byte_count bigint NOT NULL DEFAULT 0,
            created_at timestamptz NOT NULL DEFAULT now(),
            heartbeat_at timestamptz NOT NULL DEFAULT now(),
            lease_until timestamptz,
            published_at timestamptz
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_layout_fingerprint (
            semantic_fingerprint bytea PRIMARY KEY,
            snapshot_key bigint NOT NULL
                REFERENCES {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE CASCADE,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_binding (
            snapshot_id varchar(96) PRIMARY KEY,
            snapshot_key bigint NOT NULL
                REFERENCES {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE RESTRICT,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """,
    ):
        await connection.status(ddl)


async def _create_scope_and_code_tables(connection, schema: str) -> None:
    for ddl in (
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_scope (
            snapshot_id varchar(96) NOT NULL,
            plan_id varchar(64) NOT NULL,
            plan_market_type varchar(32) NOT NULL DEFAULT '',
            coverage_scope_id bytea NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (snapshot_id)
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_plan_scope (
            snapshot_id varchar(96) NOT NULL,
            plan_id varchar(64) NOT NULL,
            plan_market_type varchar(32) NOT NULL DEFAULT '',
            created_at timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (snapshot_id, plan_id, plan_market_type),
            FOREIGN KEY (snapshot_id)
                REFERENCES {schema}.ptg2_v3_snapshot_scope(snapshot_id)
                ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_code (
            snapshot_key bigint NOT NULL,
            code_key integer NOT NULL,
            code_global_id_128 bytea NOT NULL,
            coverage_scope_id bytea NOT NULL,
            reported_code_system text,
            reported_code text,
            negotiation_arrangement text,
            rate_count bigint NOT NULL,
            PRIMARY KEY (snapshot_key, code_key)
        )
        """,
    ):
        await connection.status(ddl)


async def _create_gc_tables(connection, schema: str) -> None:
    for ddl in (
        f"""
        CREATE TABLE {schema}.ptg2_v3_block (
            block_hash bytea PRIMARY KEY,
            stored_byte_count bigint NOT NULL
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_block (
            snapshot_key bigint NOT NULL,
            block_hash bytea NOT NULL,
            PRIMARY KEY (snapshot_key, block_hash)
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_gc_candidate (
            block_hash bytea PRIMARY KEY,
            eligible_at timestamptz NOT NULL,
            queued_at timestamptz NOT NULL
        )
        """,
    ):
        await connection.status(ddl)


async def _create_remaining_shared_tables(connection, schema: str) -> None:
    core_tables = {
        "ptg2_v3_snapshot_layout",
        "ptg2_v3_layout_fingerprint",
        "ptg2_v3_snapshot_binding",
        "ptg2_v3_snapshot_scope",
        "ptg2_v3_snapshot_plan_scope",
        "ptg2_v3_code",
        "ptg2_v3_block",
        "ptg2_v3_snapshot_block",
        "ptg2_v3_gc_candidate",
    }
    for table_name in sorted(set(shared_gc._SHARED_TABLE_NAMES) - core_tables):
        await connection.status(
            f'CREATE TABLE {schema}."{table_name}" (snapshot_key bigint)'
        )


async def create_cross_plan_test_schema(connection, schema_name: str) -> None:
    """Create the minimal shared-layout schema required by this PostgreSQL test."""

    schema = f'"{schema_name}"'
    await connection.status(f"CREATE SCHEMA {schema}")
    await connection.status(attempt_guard_prerequisite_ddl(schema))
    await _create_layout_identity_tables(connection, schema)
    await _create_scope_and_code_tables(connection, schema)
    await _create_gc_tables(connection, schema)
    await _create_remaining_shared_tables(connection, schema)
