# Licensed under the HealthPorta Non-Commercial License (see LICENSE).
"""Shared PostgreSQL fixtures for source-snapshot removal tests."""

from __future__ import annotations

import json
from typing import Any

from process.ptg_parts.ptg2_shared_blocks import (
    PTG2_V3_DENSE_LAYOUT_TABLES,
    PTG2_V3_SHARED_GENERATION,
)


_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE __SCHEMA__.ptg2_snapshot (
        snapshot_id varchar(96) PRIMARY KEY,
        import_month date NOT NULL,
        previous_snapshot_id varchar(96),
        status varchar(32) NOT NULL,
        manifest jsonb NOT NULL
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_snapshot_pin (
        owner_type varchar(48) NOT NULL,
        owner_id varchar(96) NOT NULL,
        snapshot_id varchar(128) NOT NULL REFERENCES
            __SCHEMA__.ptg2_snapshot(snapshot_id) ON DELETE RESTRICT,
        reason varchar(256),
        created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
        PRIMARY KEY (owner_type, owner_id, snapshot_id),
        CHECK (btrim(owner_type) <> '' AND btrim(owner_id) <> '')
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_current_snapshot (
        slot varchar(32) PRIMARY KEY,
        snapshot_id varchar(96),
        previous_snapshot_id varchar(96)
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_current_source_snapshot (
        source_key varchar(255) PRIMARY KEY,
        snapshot_id varchar(96),
        previous_snapshot_id varchar(96)
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_current_plan_source (
        plan_source_key varchar(255) PRIMARY KEY,
        snapshot_id varchar(96),
        previous_snapshot_id varchar(96)
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_artifact_manifest (
        artifact_id varchar(255) PRIMARY KEY,
        snapshot_id varchar(96)
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_snapshot_layout (
        snapshot_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        storage_shard_id smallint NOT NULL DEFAULT 0,
        build_token varchar(96) NOT NULL,
        generation varchar(32) NOT NULL,
        state varchar(16) NOT NULL CHECK (state IN ('building', 'sealed')),
        mapping_digest bytea,
        support_digest bytea,
        layout_manifest jsonb NOT NULL DEFAULT '{}'::jsonb,
        logical_byte_count bigint NOT NULL DEFAULT 0,
        created_at timestamptz NOT NULL DEFAULT now(),
        heartbeat_at timestamptz NOT NULL DEFAULT now(),
        lease_until timestamptz,
        published_at timestamptz
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_layout_fingerprint (
        semantic_fingerprint bytea PRIMARY KEY,
        snapshot_key bigint NOT NULL REFERENCES
            __SCHEMA__.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE CASCADE,
        created_at timestamptz NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_snapshot_binding (
        snapshot_id varchar(96) PRIMARY KEY REFERENCES
            __SCHEMA__.ptg2_snapshot(snapshot_id) ON DELETE CASCADE,
        snapshot_key bigint NOT NULL REFERENCES
            __SCHEMA__.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE RESTRICT,
        created_at timestamptz NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_snapshot_scope (
        snapshot_id varchar(96) PRIMARY KEY REFERENCES
            __SCHEMA__.ptg2_snapshot(snapshot_id) ON DELETE CASCADE,
        plan_id varchar(64) NOT NULL,
        plan_market_type varchar(32) NOT NULL DEFAULT '',
        coverage_scope_id bytea NOT NULL CHECK (octet_length(coverage_scope_id) = 32),
        created_at timestamptz NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_snapshot_plan_scope (
        snapshot_id varchar(96) NOT NULL REFERENCES
            __SCHEMA__.ptg2_v3_snapshot_scope(snapshot_id) ON DELETE CASCADE,
        plan_id varchar(64) NOT NULL,
        plan_market_type varchar(32) NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY (snapshot_id, plan_id, plan_market_type)
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_source_trace_set (
        source_trace_set_hash varchar(64) PRIMARY KEY,
        source_trace_hashes varchar(64)[] NOT NULL
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_snapshot_source (
        snapshot_id varchar(96) NOT NULL REFERENCES
            __SCHEMA__.ptg2_v3_snapshot_scope(snapshot_id) ON DELETE CASCADE,
        source_key integer NOT NULL,
        source_type varchar(32) NOT NULL,
        identity_kind varchar(64) NOT NULL,
        identity_sha256 varchar(64) NOT NULL,
        raw_container_sha256 varchar(64) NOT NULL,
        logical_json_sha256 varchar(64),
        logical_hash_deferred boolean NOT NULL,
        source_trace_set_hash varchar(64) NOT NULL REFERENCES
            __SCHEMA__.ptg2_source_trace_set(source_trace_set_hash) ON DELETE RESTRICT,
        PRIMARY KEY (snapshot_id, source_key)
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_candidate_audit_attestation (
        snapshot_id varchar(96) PRIMARY KEY REFERENCES
            __SCHEMA__.ptg2_v3_snapshot_scope(snapshot_id) ON DELETE CASCADE,
        snapshot_key bigint NOT NULL REFERENCES
            __SCHEMA__.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE RESTRICT,
        source_key varchar(96) NOT NULL,
        plan_id varchar(64) NOT NULL,
        plan_market_type varchar(32) NOT NULL,
        coverage_scope_id bytea NOT NULL,
        source_set_digest bytea NOT NULL,
        audit_sample_digest bytea NOT NULL,
        contract varchar(64) NOT NULL,
        tool_name varchar(64) NOT NULL,
        tool_version varchar(32) NOT NULL,
        report_digest bytea NOT NULL,
        report jsonb NOT NULL,
        attested_at timestamptz NOT NULL,
        expires_at timestamptz NOT NULL,
        activated_at timestamptz
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_block (
        block_hash bytea PRIMARY KEY,
        stored_byte_count bigint NOT NULL
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_snapshot_block (
        snapshot_key bigint NOT NULL REFERENCES
            __SCHEMA__.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE CASCADE,
        object_kind varchar(64) NOT NULL,
        block_key bigint NOT NULL,
        fragment_no integer NOT NULL,
        entry_count bigint NOT NULL,
        block_hash bytea NOT NULL REFERENCES __SCHEMA__.ptg2_v3_block(block_hash),
        PRIMARY KEY (snapshot_key, object_kind, block_key, fragment_no)
    )
    """,
    """
    CREATE TABLE __SCHEMA__.ptg2_v3_gc_candidate (
        block_hash bytea PRIMARY KEY REFERENCES
            __SCHEMA__.ptg2_v3_block(block_hash) ON DELETE CASCADE,
        eligible_at timestamptz NOT NULL,
        queued_at timestamptz NOT NULL DEFAULT now()
    )
    """,
)

_LAYOUT_INSERT = """
INSERT INTO __SCHEMA__.ptg2_v3_snapshot_layout
    (snapshot_key, build_token, generation, state, created_at, heartbeat_at, lease_until)
VALUES
    (10, 'build-10', :generation, 'sealed', now() - INTERVAL '2 hours',
     now() - INTERVAL '2 hours', NULL)
"""

_SNAPSHOT_INSERT = """
INSERT INTO __SCHEMA__.ptg2_snapshot
    (snapshot_id, import_month, previous_snapshot_id, status, manifest)
VALUES (:snapshot_id, DATE '2026-07-01', NULL, 'published', CAST(:manifest AS jsonb))
"""

_BINDING_INSERT = """
INSERT INTO __SCHEMA__.ptg2_v3_snapshot_binding (snapshot_id, snapshot_key)
VALUES (:snapshot_id, 10)
"""

_SCOPE_INSERT = """
INSERT INTO __SCHEMA__.ptg2_v3_snapshot_scope
    (snapshot_id, plan_id, plan_market_type, coverage_scope_id)
VALUES (:snapshot_id, :plan_id, 'group', :coverage_scope_id)
"""

_PLAN_SCOPE_INSERT = """
INSERT INTO __SCHEMA__.ptg2_v3_snapshot_plan_scope
    (snapshot_id, plan_id, plan_market_type)
VALUES (:snapshot_id, :plan_id, 'group')
"""

_ATTESTATION_INSERT = """
INSERT INTO __SCHEMA__.ptg2_v3_candidate_audit_attestation
    (snapshot_id, snapshot_key, source_key, plan_id,
     plan_market_type, coverage_scope_id, source_set_digest,
     audit_sample_digest, contract, tool_name, tool_version,
     report_digest, report, attested_at, expires_at, activated_at)
VALUES
    (:snapshot_id, 10, :source_key, :plan_id, 'group',
     :coverage_scope_id, :source_set_digest, :audit_sample_digest,
     'source_to_api_v1', 'fixture-auditor', '1.0',
     :report_digest, '{}'::jsonb, now(), now() + INTERVAL '1 hour', NULL)
"""


def _schema_sql(statement: str, schema: str) -> str:
    return statement.replace("__SCHEMA__", schema)


async def create_production_shaped_schema(database: Any, schema_name: str) -> None:
    """Create the production foreign-key shape used by removal tests."""

    schema = f'"{schema_name}"'
    async with database.acquire() as connection:
        await connection.status(f"CREATE SCHEMA {schema}")
        for statement in _SCHEMA_STATEMENTS[:-1]:
            await connection.status(_schema_sql(statement, schema))
        for table_name in PTG2_V3_DENSE_LAYOUT_TABLES:
            await connection.status(
                f'CREATE TABLE {schema}."{table_name}" '
                "(snapshot_key bigint NOT NULL)"
            )
        await connection.status(_schema_sql(_SCHEMA_STATEMENTS[-1], schema))


def _snapshot_manifest(source_key: str) -> str:
    return json.dumps(
        {
            "serving_index": {
                "arch_version": "postgres_binary_v3",
                "storage_generation": PTG2_V3_SHARED_GENERATION,
                "shared_snapshot_key": 10,
                "source_key": source_key,
            }
        }
    )


async def _insert_snapshot_binding(
    connection: Any,
    schema: str,
    snapshot_id: str,
    source_key: str,
) -> None:
    plan_id = f"plan-{source_key}"
    digit = 1 if source_key == "source_a" else 2
    parameter_by_name = {
        "snapshot_id": snapshot_id,
        "source_key": source_key,
        "plan_id": plan_id,
        "coverage_scope_id": bytes([digit]) * 32,
    }
    await connection.status(
        _schema_sql(_SNAPSHOT_INSERT, schema),
        snapshot_id=snapshot_id,
        manifest=_snapshot_manifest(source_key),
    )
    await connection.status(
        _schema_sql(_BINDING_INSERT, schema),
        **parameter_by_name,
    )
    await connection.status(
        _schema_sql(_SCOPE_INSERT, schema),
        **parameter_by_name,
    )
    await connection.status(
        _schema_sql(_PLAN_SCOPE_INSERT, schema),
        **parameter_by_name,
    )
    await connection.status(
        _schema_sql(_ATTESTATION_INSERT, schema),
        **parameter_by_name,
        source_set_digest=bytes([digit + 2]) * 32,
        audit_sample_digest=bytes([digit + 4]) * 32,
        report_digest=bytes([digit + 6]) * 32,
    )


async def insert_shared_snapshots(database: Any, schema_name: str) -> None:
    """Insert two source snapshots bound to one shared layout."""

    schema = f'"{schema_name}"'
    async with database.acquire() as connection:
        await connection.status(
            _schema_sql(_LAYOUT_INSERT, schema),
            generation=PTG2_V3_SHARED_GENERATION,
        )
        for snapshot_id, source_key in (
            ("shared-a", "source_a"),
            ("shared-b", "source_b"),
        ):
            await _insert_snapshot_binding(
                connection,
                schema,
                snapshot_id,
                source_key,
            )


async def count_rows(
    database: Any,
    schema_name: str,
    table_name: str,
    *,
    snapshot_id: str | None = None,
) -> int:
    """Count fixture rows, optionally for one snapshot."""

    schema = f'"{schema_name}"'
    where_clause = ""
    query_param_map: dict[str, str] = {}
    if snapshot_id is not None:
        where_clause = " WHERE snapshot_id = :snapshot_id"
        query_param_map["snapshot_id"] = snapshot_id
    return int(
        await database.scalar(
            f'SELECT COUNT(*) FROM {schema}."{table_name}"{where_clause}',
            **query_param_map,
        )
        or 0
    )
