# Licensed under the HealthPorta Non-Commercial License (see LICENSE).

from __future__ import annotations

import os
import uuid

import pytest
from sqlalchemy import text

from api import ptg2_serving
from api.ptg2_types import PTG2ServingTables
from db.connection import Database
from process.ptg_parts import ptg2_shared_gc as shared_gc
from process.ptg_parts.domain import (
    PTG2DownloadedJob,
    PTG2LogicalArtifact,
    PTG2RawArtifact,
)
from process.ptg_parts.ptg2_shared_blocks import (
    PTG2_V3_COLD_LOOKUP_CONTRACT,
    PTG2_V3_SHARED_GENERATION,
    bind_snapshot_to_shared_layout,
    reserve_shared_layout,
)
from process.ptg_parts.ptg2_shared_reuse import shared_physical_input_identity
from process.ptg_parts.source_pointers import _bind_snapshot_coverage_scope


POSTGRES_TEST_ENV = "HLTHPRT_PTG2_CROSS_PLAN_POSTGRES_TEST"
SNAPSHOT_A = "strict-v3-snapshot-a"
SNAPSHOT_B = "strict-v3-snapshot-b"
PLAN_A = "logical-plan-a"
PLAN_B = "logical-plan-b"


def _downloaded(plan_id: str) -> PTG2DownloadedJob:
    url = "https://example.invalid/identical-full-input.json.gz"
    return PTG2DownloadedJob(
        job={
            "type": "in_network",
            "url": url,
            "plan_info": [
                {
                    "plan_id": plan_id,
                    "plan_id_type": "ein",
                    "plan_market_type": "group",
                }
            ],
        },
        raw_artifact=PTG2RawArtifact(
            original_url=url,
            canonical_url=url,
            raw_path="/tmp/identical-full-input.json.gz",
            raw_storage_uri="file:///tmp/identical-full-input.json.gz",
            raw_sha256="a" * 64,
            byte_count=1_024,
        ),
        logical_artifact=PTG2LogicalArtifact(
            logical_path="/tmp/identical-full-input.json.gz",
            logical_sha256="b" * 64,
            byte_count=8_192,
            compression="gzip",
        ),
    )


def _identity(plan_id: str):
    return shared_physical_input_identity(
        [_downloaded(plan_id)],
        options={
            "snapshot_arch": "postgres_binary_v3",
            "snapshot_arch_variant": PTG2_V3_SHARED_GENERATION,
        },
        scanner_canon_version={"version": 7},
    )


def _serving_tables(snapshot_id: str, snapshot_key: int) -> PTG2ServingTables:
    return PTG2ServingTables(
        snapshot_id=snapshot_id,
        arch_version="postgres_binary_v3",
        storage_generation=PTG2_V3_SHARED_GENERATION,
        cold_lookup_contract=PTG2_V3_COLD_LOOKUP_CONTRACT,
        shared_snapshot_key=snapshot_key,
    )


async def _create_test_schema(connection, schema_name: str) -> None:
    """Create the minimal shared-layout schema required by this PostgreSQL test."""

    schema = f'"{schema_name}"'
    await connection.status(f"CREATE SCHEMA {schema}")
    for ddl in (
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_layout (
            snapshot_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            storage_shard_id smallint NOT NULL DEFAULT 0,
            build_token varchar(96) NOT NULL,
            generation varchar(32) NOT NULL,
            state varchar(16) NOT NULL,
            mapping_digest bytea,
            support_digest bytea,
            layout_manifest jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            logical_byte_count bigint NOT NULL DEFAULT 0,
            created_at timestamptz NOT NULL DEFAULT now(),
            heartbeat_at timestamptz NOT NULL DEFAULT now(),
            lease_until timestamptz,
            published_at timestamptz
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_layout_fingerprint (
            semantic_fingerprint bytea PRIMARY KEY,
            snapshot_key bigint NOT NULL
                REFERENCES {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE CASCADE,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_binding (
            snapshot_id varchar(96) PRIMARY KEY,
            snapshot_key bigint NOT NULL
                REFERENCES {schema}.ptg2_v3_snapshot_layout(snapshot_key) ON DELETE RESTRICT,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_scope (
            snapshot_id varchar(96) NOT NULL,
            plan_id varchar(64) NOT NULL,
            plan_market_type varchar(32) NOT NULL DEFAULT '',
            coverage_scope_id bytea NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (snapshot_id)
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_plan_scope (
            snapshot_id varchar(96) NOT NULL,
            plan_id varchar(64) NOT NULL,
            plan_market_type varchar(32) NOT NULL DEFAULT '',
            created_at timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (snapshot_id, plan_id, plan_market_type),
            FOREIGN KEY (snapshot_id)
                REFERENCES {schema}.ptg2_v3_snapshot_scope(snapshot_id)
                ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_code (
            snapshot_key bigint NOT NULL,
            code_key integer NOT NULL,
            code_global_id_128 bytea NOT NULL,
            coverage_scope_id bytea NOT NULL,
            reported_code_system text,
            reported_code text,
            negotiation_arrangement text,
            rate_count bigint NOT NULL,
            PRIMARY KEY (snapshot_key, code_key)
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_block (
            block_hash bytea PRIMARY KEY,
            stored_byte_count bigint NOT NULL
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_block (
            snapshot_key bigint NOT NULL,
            block_hash bytea NOT NULL,
            PRIMARY KEY (snapshot_key, block_hash)
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_gc_candidate (
            block_hash bytea PRIMARY KEY,
            eligible_at timestamptz NOT NULL,
            queued_at timestamptz NOT NULL
        )
        """,
    ):
        await connection.status(ddl)

    core_tables = {
        "ptg2_v3_snapshot_layout",
        "ptg2_v3_layout_fingerprint",
        "ptg2_v3_snapshot_binding",
        "ptg2_v3_snapshot_scope",
        "ptg2_v3_snapshot_plan_scope",
        "ptg2_v3_code",
        "ptg2_v3_block",
        "ptg2_v3_snapshot_block",
        "ptg2_v3_gc_candidate",
    }
    for table_name in sorted(set(shared_gc._SHARED_TABLE_NAMES) - core_tables):
        await connection.status(
            f'CREATE TABLE {schema}."{table_name}" (snapshot_key bigint)'
        )


async def _bind_logical_snapshot(
    session,
    *,
    schema_name: str,
    snapshot_id: str,
    snapshot_key: int,
    plan_id: str,
    coverage_scope_id: bytes,
) -> None:
    await bind_snapshot_to_shared_layout(
        session,
        schema_name=schema_name,
        snapshot_id=snapshot_id,
        snapshot_key=snapshot_key,
    )
    await _bind_snapshot_coverage_scope(
        session,
        schema_name=schema_name,
        snapshot_id=snapshot_id,
        coverage_scope_id=coverage_scope_id,
        plan_pointer_entries=[
            {"plan_id": plan_id, "plan_market_type": "group"}
        ],
    )


async def _scoped_plan_rows(
    session,
    *,
    schema_name: str,
    snapshot_id: str,
    snapshot_key: int,
    requested_plan: str,
) -> tuple[list[str], str, dict[str, object]]:
    join_sql, filters, params, _ = ptg2_serving._shared_v3_code_scope_sql(
        _serving_tables(snapshot_id, snapshot_key),
        requested_plan=requested_plan,
        plan_market_type="group",
    )
    params.update(
        {
            "shared_snapshot_key": snapshot_key,
            "reported_code": "99213",
        }
    )
    where_sql = " AND ".join(
        [
            "code_metadata.snapshot_key = :shared_snapshot_key",
            "code_metadata.reported_code = :reported_code",
            *filters,
        ]
    )
    sql = f"""
        SELECT logical_scope.plan_id
          FROM \"{schema_name}\".ptg2_v3_code AS code_metadata
          {join_sql}
         WHERE {where_sql}
         ORDER BY logical_scope.plan_id
    """
    query_result = await session.execute(text(sql), params)
    return list(query_result.scalars().all()), sql, params


def test_identical_full_input_reuses_physical_identity_across_logical_plans():
    identity_a = _identity(PLAN_A)
    identity_b = _identity(PLAN_B)

    assert identity_a.logical_plan.plan_id == PLAN_A
    assert identity_b.logical_plan.plan_id == PLAN_B
    assert identity_a.semantic_fingerprint == identity_b.semantic_fingerprint
    assert identity_a.coverage_scope_id == identity_b.coverage_scope_id
    assert len(identity_a.semantic_fingerprint) == 32
    assert len(identity_a.coverage_scope_id) == 32


@pytest.mark.asyncio
async def test_postgres_cross_plan_scope_isolation_and_bound_layout_retention(monkeypatch):
    """Ensure cross-plan reuse preserves logical scope isolation and retention."""

    if os.getenv(POSTGRES_TEST_ENV) != "1":
        pytest.skip(f"set {POSTGRES_TEST_ENV}=1 for the isolated PostgreSQL test")

    identity_a = _identity(PLAN_A)
    identity_b = _identity(PLAN_B)
    assert identity_a.semantic_fingerprint == identity_b.semantic_fingerprint
    assert identity_a.coverage_scope_id == identity_b.coverage_scope_id

    database = Database()
    schema_name = f"ptg2_cross_plan_reuse_{uuid.uuid4().hex}"
    schema = f'"{schema_name}"'
    monkeypatch.setattr(ptg2_serving, "PTG2_SCHEMA", schema_name)
    await database.connect()
    try:
        async with database.acquire() as connection:
            await _create_test_schema(connection, schema_name)

        async with database.transaction() as session:
            first = await reserve_shared_layout(
                session,
                schema_name=schema_name,
                semantic_fingerprint=identity_a.semantic_fingerprint,
                build_token="build-a",
            )
            assert not first.reused
            await session.execute(
                text(
                    f"""
                    UPDATE {schema}.ptg2_v3_snapshot_layout
                       SET state = 'sealed',
                           lease_until = transaction_timestamp() - INTERVAL '1 second'
                     WHERE snapshot_key = :snapshot_key
                    """
                ),
                {"snapshot_key": first.snapshot_key},
            )
            second = await reserve_shared_layout(
                session,
                schema_name=schema_name,
                semantic_fingerprint=identity_b.semantic_fingerprint,
                build_token="build-b",
            )
            assert second.reused
            assert second.snapshot_key == first.snapshot_key

            await _bind_logical_snapshot(
                session,
                schema_name=schema_name,
                snapshot_id=SNAPSHOT_A,
                snapshot_key=first.snapshot_key,
                plan_id=PLAN_A,
                coverage_scope_id=identity_a.coverage_scope_id,
            )
            await _bind_logical_snapshot(
                session,
                schema_name=schema_name,
                snapshot_id=SNAPSHOT_B,
                snapshot_key=first.snapshot_key,
                plan_id=PLAN_B,
                coverage_scope_id=identity_b.coverage_scope_id,
            )
            await session.execute(
                text(
                    f"""
                    INSERT INTO {schema}.ptg2_v3_code
                        (snapshot_key, code_key, code_global_id_128,
                         coverage_scope_id, reported_code_system,
                         reported_code, negotiation_arrangement, rate_count)
                    VALUES
                        (:snapshot_key, 7, :code_global_id_128,
                         :coverage_scope_id, 'CPT', '99213', 'ffs', 1)
                    """
                ),
                {
                    "snapshot_key": first.snapshot_key,
                    "code_global_id_128": bytes.fromhex("07" * 16),
                    "coverage_scope_id": identity_a.coverage_scope_id,
                },
            )

        async with database.transaction() as session:
            bindings = (
                await session.execute(
                    text(
                        f"""
                        SELECT snapshot_id, snapshot_key
                          FROM {schema}.ptg2_v3_snapshot_binding
                         ORDER BY snapshot_id
                        """
                    )
                )
            ).all()
            scopes = (
                await session.execute(
                    text(
                        f"""
                        SELECT snapshot_id, plan_id, plan_market_type,
                               coverage_scope_id
                          FROM {schema}.ptg2_v3_snapshot_scope
                         ORDER BY snapshot_id
                        """
                    )
                )
            ).all()
            assert [tuple(binding_row) for binding_row in bindings] == [
                (SNAPSHOT_A, first.snapshot_key),
                (SNAPSHOT_B, first.snapshot_key),
            ]
            assert [tuple(scope_row) for scope_row in scopes] == [
                (SNAPSHOT_A, PLAN_A, "group", identity_a.coverage_scope_id),
                (SNAPSHOT_B, PLAN_B, "group", identity_a.coverage_scope_id),
            ]

            own_rows, own_sql, own_params = await _scoped_plan_rows(
                session,
                schema_name=schema_name,
                snapshot_id=SNAPSHOT_A,
                snapshot_key=first.snapshot_key,
                requested_plan=PLAN_A,
            )
            cross_plan_rows, cross_plan_sql, cross_plan_params = await _scoped_plan_rows(
                session,
                schema_name=schema_name,
                snapshot_id=SNAPSHOT_A,
                snapshot_key=first.snapshot_key,
                requested_plan=PLAN_B,
            )
            other_rows, _, _ = await _scoped_plan_rows(
                session,
                schema_name=schema_name,
                snapshot_id=SNAPSHOT_B,
                snapshot_key=first.snapshot_key,
                requested_plan=PLAN_B,
            )

            assert own_rows == [PLAN_A]
            assert cross_plan_rows == []
            assert other_rows == [PLAN_B]
            assert "physical_scope.snapshot_id = :logical_snapshot_id" in own_sql
            assert (
                "physical_scope.coverage_scope_id = code_metadata.coverage_scope_id"
                in own_sql
            )
            assert "plan_scope.plan_id = :plan_id" in cross_plan_sql
            assert own_params["logical_snapshot_id"] == SNAPSHOT_A
            assert own_params["plan_id"] == PLAN_A
            assert cross_plan_params["logical_snapshot_id"] == SNAPSHOT_A
            assert cross_plan_params["plan_id"] == PLAN_B

        async with database.acquire() as connection:
            planned = await shared_gc.build_shared_layout_release_plan(
                schema_name=schema_name,
                executor=connection,
                removing_snapshot_ids=(SNAPSHOT_A,),
                all_eligible_layouts=True,
                require_shared=True,
            )
            assert planned.logical_layout_count == 0

            await connection.status(
                f"DELETE FROM {schema}.ptg2_v3_snapshot_scope WHERE snapshot_id = :snapshot_id",
                snapshot_id=SNAPSHOT_A,
            )
            await connection.status(
                f"DELETE FROM {schema}.ptg2_v3_snapshot_binding WHERE snapshot_id = :snapshot_id",
                snapshot_id=SNAPSHOT_A,
            )
            released = await shared_gc.release_unbound_ptg2_shared_layouts(
                schema_name=schema_name,
                executor=connection,
                building_max_age_seconds=0,
                grace_seconds=0,
                max_layouts=10,
                require_shared=True,
            )

            assert released.logical_layout_count == 0
            assert await connection.scalar(
                f"SELECT COUNT(*) FROM {schema}.ptg2_v3_snapshot_layout"
            ) == 1
            assert await connection.scalar(
                f"""
                SELECT COUNT(*)
                  FROM {schema}.ptg2_v3_snapshot_binding
                 WHERE snapshot_id = :snapshot_id
                   AND snapshot_key = :snapshot_key
                """,
                snapshot_id=SNAPSHOT_B,
                snapshot_key=first.snapshot_key,
            ) == 1
            assert await connection.scalar(
                f"""
                SELECT COUNT(*)
                  FROM {schema}.ptg2_v3_snapshot_scope
                 WHERE snapshot_id = :snapshot_id
                   AND plan_id = :plan_id
                   AND coverage_scope_id = :coverage_scope_id
                """,
                snapshot_id=SNAPSHOT_B,
                plan_id=PLAN_B,
                coverage_scope_id=identity_b.coverage_scope_id,
            ) == 1
    finally:
        try:
            async with database.acquire() as connection:
                await connection.status(f"DROP SCHEMA IF EXISTS {schema} CASCADE")
        finally:
            await database.disconnect()
