# Licensed under the HealthPorta Non-Commercial License (see LICENSE).
"""PostgreSQL lifecycle proof for the additive PTG V4 map migration."""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
import re
from typing import Any
import uuid

from alembic.migration import MigrationContext
from alembic.operations import Operations
import pytest
import sqlalchemy as sa
from sqlalchemy.engine import make_url
from sqlalchemy.exc import DBAPIError
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

from tests.ptg2_v4_migration_catalog_support import (
    assert_v4_catalog,
    assert_v4_schema_absent,
    v3_provider_set_prerequisite_ddl,
)


ROOT = Path(__file__).resolve().parents[1]
MIGRATION_PATH = (
    ROOT
    / "alembic"
    / "versions"
    / "20260723100000_ptg2_v4_snapshot_map_pack.py"
)
POSTGRES_DSN_ENV = "HLTHPRT_PTG2_V4_MIGRATION_POSTGRES_DSN"
_DISPOSABLE_DATABASE_RE = re.compile(
    r"(?:^test(?:[_-]|$)|(?:^|[_-])test(?:[_-]|$))",
    re.IGNORECASE,
)
_DISPOSABLE_SCHEMA_RE = re.compile(r"^ptg2_v4_migration_test_[0-9a-f]{32}$")
def _load_migration():
    spec = importlib.util.spec_from_file_location(
        "ptg2_v4_migration_postgres_proof",
        MIGRATION_PATH,
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _quoted(identifier: str) -> str:
    return '"' + str(identifier).replace('"', '""') + '"'


def _async_database_url() -> sa.URL:
    raw_dsn = os.getenv(POSTGRES_DSN_ENV)
    if not raw_dsn:
        pytest.skip(f"set {POSTGRES_DSN_ENV} for the PostgreSQL migration proof")
    database_url = make_url(raw_dsn)
    database_name = str(database_url.database or "")
    if (
        not database_url.drivername.startswith("postgresql")
        or not database_name
        or not _DISPOSABLE_DATABASE_RE.search(database_name)
    ):
        pytest.fail(
            f"{POSTGRES_DSN_ENV} must target an explicit PostgreSQL test "
            "database; only a generated disposable schema is modified"
        )
    return database_url.set(drivername="postgresql+asyncpg")


async def _run_migration_action(
    engine: AsyncEngine,
    migration: Any,
    action: str,
) -> None:
    """Run one revision action through Alembic's real PostgreSQL operations."""

    async with engine.connect() as async_connection:

        def run_action(sync_connection) -> None:
            migration_context = MigrationContext.configure(sync_connection)
            migration.op = Operations(migration_context)
            with migration_context.begin_transaction():
                getattr(migration, action)()

        await async_connection.run_sync(run_action)


async def _create_prerequisites(engine: AsyncEngine, schema_name: str) -> None:
    """Create the exact V3 relations referenced by the additive V4 migration."""

    schema = _quoted(schema_name)
    statements = (
        f"CREATE SCHEMA {schema}",
        f"""
        CREATE TABLE {schema}.ptg2_v3_snapshot_layout (
            snapshot_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            storage_shard_id smallint NOT NULL DEFAULT 0,
            build_token varchar(96) NOT NULL,
            generation varchar(32) NOT NULL,
            state varchar(16) NOT NULL,
            mapping_digest bytea,
            support_digest bytea,
            layout_manifest jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            logical_byte_count bigint NOT NULL DEFAULT 0,
            created_at timestamptz NOT NULL DEFAULT now(),
            heartbeat_at timestamptz NOT NULL DEFAULT now(),
            lease_until timestamptz,
            published_at timestamptz
        )
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_block (
            block_hash bytea PRIMARY KEY,
            format_version smallint NOT NULL,
            object_kind varchar(64) NOT NULL,
            codec varchar(16) NOT NULL,
            entry_count bigint NOT NULL,
            raw_byte_count bigint NOT NULL,
            stored_byte_count bigint NOT NULL,
            payload bytea NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """,
        v3_provider_set_prerequisite_ddl(schema),
        f"""
        CREATE TABLE {schema}.ptg2_v3_npi_scope (
            snapshot_key bigint NOT NULL,
            npi bigint NOT NULL,
            CONSTRAINT ptg2_v3_npi_scope_pkey
                PRIMARY KEY (snapshot_key, npi),
            CONSTRAINT ptg2_v3_npi_scope_npi_check CHECK (npi > 0)
        ) PARTITION BY HASH (snapshot_key)
        """,
        f"""
        CREATE TABLE {schema}.ptg2_v3_npi_scope_p00
            PARTITION OF {schema}.ptg2_v3_npi_scope
            FOR VALUES WITH (MODULUS 1, REMAINDER 0)
        """,
        f"""
        INSERT INTO {schema}.ptg2_v3_npi_scope (snapshot_key, npi)
        VALUES (91, 1234567890)
        """,
    )
    async with engine.begin() as connection:
        for statement in statements:
            await connection.exec_driver_sql(statement)


async def _drop_disposable_schema(
    engine: AsyncEngine,
    schema_name: str,
) -> None:
    if not _DISPOSABLE_SCHEMA_RE.fullmatch(schema_name):
        raise RuntimeError(f"refusing to drop non-disposable schema {schema_name!r}")
    async with engine.begin() as connection:
        await connection.exec_driver_sql(
            f"DROP SCHEMA IF EXISTS {_quoted(schema_name)} CASCADE"
        )


async def _legacy_npi_signature(
    engine: AsyncEngine,
    schema_name: str,
) -> dict[str, Any]:
    """Return catalog and physical identity for the legacy partitioned scope."""

    async with engine.connect() as connection:
        columns = (
            await connection.execute(
                sa.text(
                    """
                    SELECT relation.relname,
                           attribute.attname,
                           format_type(attribute.atttypid, attribute.atttypmod),
                           attribute.attnotnull,
                           pg_get_expr(default_value.adbin, default_value.adrelid)
                      FROM pg_class AS relation
                      JOIN pg_namespace AS namespace
                        ON namespace.oid = relation.relnamespace
                      JOIN pg_attribute AS attribute
                        ON attribute.attrelid = relation.oid
                      LEFT JOIN pg_attrdef AS default_value
                        ON default_value.adrelid = relation.oid
                       AND default_value.adnum = attribute.attnum
                     WHERE namespace.nspname = :schema_name
                       AND relation.relname IN (
                           'ptg2_v3_npi_scope',
                           'ptg2_v3_npi_scope_p00'
                       )
                       AND attribute.attnum > 0
                       AND NOT attribute.attisdropped
                     ORDER BY relation.relname, attribute.attnum
                    """
                ),
                {"schema_name": schema_name},
            )
        ).all()
        indexes = (
            await connection.execute(
                sa.text(
                    """
                    SELECT table_record.relname,
                           index_record.relname,
                           index_catalog.indisvalid,
                           index_catalog.indisready,
                           pg_get_indexdef(index_record.oid)
                      FROM pg_index AS index_catalog
                      JOIN pg_class AS table_record
                        ON table_record.oid = index_catalog.indrelid
                      JOIN pg_class AS index_record
                        ON index_record.oid = index_catalog.indexrelid
                      JOIN pg_namespace AS namespace
                        ON namespace.oid = table_record.relnamespace
                     WHERE namespace.nspname = :schema_name
                       AND table_record.relname IN (
                           'ptg2_v3_npi_scope',
                           'ptg2_v3_npi_scope_p00'
                       )
                     ORDER BY table_record.relname, index_record.relname
                    """
                ),
                {"schema_name": schema_name},
            )
        ).all()
        physical_relations = (
            await connection.execute(
                sa.text(
                    """
                    WITH legacy_tables AS (
                        SELECT relation.oid
                          FROM pg_class AS relation
                          JOIN pg_namespace AS namespace
                            ON namespace.oid = relation.relnamespace
                         WHERE namespace.nspname = :schema_name
                           AND relation.relname IN (
                               'ptg2_v3_npi_scope',
                               'ptg2_v3_npi_scope_p00'
                           )
                    ), legacy_relations AS (
                        SELECT oid FROM legacy_tables
                        UNION
                        SELECT indexrelid
                          FROM pg_index
                         WHERE indrelid IN (SELECT oid FROM legacy_tables)
                    )
                    SELECT relation.relname,
                           relation.relkind::text,
                           relation.oid::bigint,
                           pg_relation_filenode(relation.oid)::bigint
                      FROM legacy_relations
                      JOIN pg_class AS relation
                        ON relation.oid = legacy_relations.oid
                     ORDER BY relation.relname
                    """
                ),
                {"schema_name": schema_name},
            )
        ).all()
        row_count = int(
            (
                await connection.execute(
                    sa.text(
                        f"SELECT COUNT(*) FROM {_quoted(schema_name)}."
                        "ptg2_v3_npi_scope"
                    )
                )
            ).scalar_one()
        )
    return {
        "columns": tuple(tuple(column_row) for column_row in columns),
        "indexes": tuple(tuple(index_row) for index_row in indexes),
        "physical_relations": tuple(
            tuple(relation_row) for relation_row in physical_relations
        ),
        "row_count": row_count,
    }


async def _insert_v4_state(engine: AsyncEngine, schema_name: str) -> int:
    schema = _quoted(schema_name)
    snapshot_key = 7
    async with engine.begin() as connection:
        await connection.execute(
            sa.text(
                f"""
                INSERT INTO {schema}.ptg2_v3_snapshot_layout
                    (snapshot_key, build_token, generation, state)
                VALUES
                    (:snapshot_key, 'migration-proof', 'shared_blocks_v4',
                     'building')
                """
            ),
            {"snapshot_key": snapshot_key},
        )
        await connection.execute(
            sa.text(
                f"""
                INSERT INTO {schema}.ptg2_v4_snapshot_map_root
                    (snapshot_key, state, format_version, map_format,
                     representation, projection_id_scope)
                VALUES
                    (:snapshot_key, 'building', 1,
                     'packed_coordinate_hash_v1', 'direct_v1',
                     'snapshot_local_v1')
                """
            ),
            {"snapshot_key": snapshot_key},
        )
        await connection.execute(
            sa.text(
                f"""
                INSERT INTO {schema}.ptg2_v4_npi_scope
                    (snapshot_key, npi_key, npi)
                VALUES (:snapshot_key, 0, 1234567890)
                """
            ),
            {"snapshot_key": snapshot_key},
        )
    return snapshot_key


async def _v4_state_counts(
    engine: AsyncEngine,
    schema_name: str,
) -> tuple[int, int, int]:
    schema = _quoted(schema_name)
    async with engine.connect() as connection:
        row = (
            await connection.execute(
                sa.text(
                    f"""
                    SELECT
                        (SELECT COUNT(*)
                           FROM {schema}.ptg2_v3_snapshot_layout
                          WHERE generation = 'shared_blocks_v4'),
                        (SELECT COUNT(*)
                           FROM {schema}.ptg2_v4_snapshot_map_root),
                        (SELECT COUNT(*)
                           FROM {schema}.ptg2_v4_npi_scope)
                    """
                )
            )
        ).one()
    return tuple(int(value) for value in row)


@pytest.mark.asyncio
async def test_v4_migration_empty_upgrade_downgrade_upgrade_is_additive(
    monkeypatch,
) -> None:
    """Prove an empty lifecycle never mutates the legacy partitioned scope."""

    engine = create_async_engine(_async_database_url(), pool_size=1, max_overflow=0)
    schema_name = f"ptg2_v4_migration_test_{uuid.uuid4().hex}"
    migration = _load_migration()
    monkeypatch.setenv("HLTHPRT_DB_SCHEMA", schema_name)
    monkeypatch.delenv("DB_SCHEMA", raising=False)
    is_schema_created = False
    try:
        await _create_prerequisites(engine, schema_name)
        is_schema_created = True
        legacy_before = await _legacy_npi_signature(engine, schema_name)
        assert legacy_before["row_count"] == 1

        await _run_migration_action(engine, migration, "upgrade")
        assert await _legacy_npi_signature(engine, schema_name) == legacy_before
        await assert_v4_catalog(engine, schema_name)

        await _run_migration_action(engine, migration, "downgrade")
        assert await _legacy_npi_signature(engine, schema_name) == legacy_before
        await assert_v4_schema_absent(engine, schema_name)

        await _run_migration_action(engine, migration, "upgrade")
        assert await _legacy_npi_signature(engine, schema_name) == legacy_before
        await assert_v4_catalog(engine, schema_name)
    finally:
        if is_schema_created:
            await _drop_disposable_schema(engine, schema_name)
        await engine.dispose()


@pytest.mark.asyncio
async def test_v4_migration_downgrade_refuses_state_before_any_drop(
    monkeypatch,
) -> None:
    """Refuse lossy rollback, then allow the supported layout cascade."""

    engine = create_async_engine(_async_database_url(), pool_size=1, max_overflow=0)
    schema_name = f"ptg2_v4_migration_test_{uuid.uuid4().hex}"
    migration = _load_migration()
    monkeypatch.setenv("HLTHPRT_DB_SCHEMA", schema_name)
    monkeypatch.delenv("DB_SCHEMA", raising=False)
    is_schema_created = False
    try:
        await _create_prerequisites(engine, schema_name)
        is_schema_created = True
        legacy_before = await _legacy_npi_signature(engine, schema_name)
        await _run_migration_action(engine, migration, "upgrade")
        snapshot_key = await _insert_v4_state(engine, schema_name)

        with pytest.raises(
            DBAPIError,
            match="ptg2_v4_downgrade_requires_empty_generation",
        ):
            await _run_migration_action(engine, migration, "downgrade")

        assert await _v4_state_counts(engine, schema_name) == (1, 1, 1)
        assert await _legacy_npi_signature(engine, schema_name) == legacy_before
        await assert_v4_catalog(engine, schema_name)

        async with engine.begin() as connection:
            await connection.execute(
                sa.text(
                    f"DELETE FROM {_quoted(schema_name)}."
                    "ptg2_v3_snapshot_layout WHERE snapshot_key = :snapshot_key"
                ),
                {"snapshot_key": snapshot_key},
            )
        assert await _v4_state_counts(engine, schema_name) == (0, 0, 0)

        await _run_migration_action(engine, migration, "downgrade")
        assert await _legacy_npi_signature(engine, schema_name) == legacy_before
        await assert_v4_schema_absent(engine, schema_name)
    finally:
        if is_schema_created:
            await _drop_disposable_schema(engine, schema_name)
        await engine.dispose()
