# Licensed under the HealthPorta Non-Commercial License (see LICENSE).

"""Static contract coverage for the schema-only generation-finality revision."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIGRATION_PATH = ROOT / "alembic" / "versions" / "20260917130000_custom_import_generation_finality.py"


def _migration():
    spec = importlib.util.spec_from_file_location("custom_import_finality_migration", MIGRATION_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _normalized(statements: list[str]) -> str:
    return "\n".join(" ".join(statement.split()) for statement in statements)


def test_finality_migration_is_schema_only_and_installs_fenced_seal_guards(monkeypatch):
    migration = _migration()
    monkeypatch.setenv("HLTHPRT_DB_SCHEMA", "custom_import_finality_test")
    monkeypatch.delenv("DB_SCHEMA", raising=False)
    statements: list[str] = []
    monkeypatch.setattr(migration.op, "execute", statements.append)

    migration.upgrade()

    normalized = _normalized(statements)
    assert migration.down_revision == "20260914120000_npi_result_generation"
    assert "INSERT INTO" not in normalized
    assert "UPDATE custom_import" not in normalized
    assert "CREATE TABLE" in normalized
    assert "custom_import_generation_seal" in normalized
    assert "custom_import_no_change_seal" in normalized
    assert "producing_fence BIGINT" in normalized
    assert "producing_token_sha256 BYTEA" in normalized
    assert "custom_import_generation_producing_authority_check" in normalized
    assert "RENAME COLUMN generation_sha256 TO candidate_sha256" in normalized
    assert "DROP CONSTRAINT custom_import_generation_content_key" in normalized
    assert "DROP CONSTRAINT custom_import_generation_execution_key" in normalized
    assert "custom_import_generation_execution_fence_key" in normalized
    assert "NOT VALID" in normalized
    assert "custom_import_current_generation_seal_fkey" in normalized
    assert "custom_import_publication_event_to_seal_fkey" in normalized
    assert "custom_import_no_change_seal_base_finality_fkey" in normalized
    assert "custom_import_publication_event_pointer_version_key" in normalized
    assert "custom_import_publication_event_no_change_execution_key" in normalized
    assert "WHERE finality_contract = 'custom-import-finality/v1'" in normalized
    assert "ADD COLUMN rejection_id BIGINT GENERATED BY DEFAULT AS IDENTITY" in normalized
    assert "custom_import_generation_seal_duplicate_child_key" in normalized
    assert "GROUP BY child.family_revision_id, child.collection_slot, child_revision.child_key_sha256" in normalized
    assert "current_setting('transaction_isolation') <> 'read committed'" in normalized
    assert "clock_timestamp()" in normalized
    assert "FOR UPDATE" in normalized
    assert normalized.count("SECURITY DEFINER") == 6
    assert normalized.count("SET search_path = pg_catalog") == 6
    assert normalized.count("REVOKE ALL ON FUNCTION") == 6
    for table_name in migration._APPEND_GUARD_TABLES:
        assert f'BEFORE INSERT ON "custom_import_finality_test"."{table_name}"' in normalized
    for table_name in migration._DATASET_FIRST_INSERT_TABLES:
        assert f'BEFORE INSERT ON "custom_import_finality_test"."{table_name}"' in normalized
    assert "custom_import_generation_seal_immutable_row_guard" in normalized
    assert "custom_import_no_change_seal_immutable_row_guard" in normalized


def test_finality_downgrade_removes_references_before_finality_tables(monkeypatch):
    migration = _migration()
    monkeypatch.setenv("HLTHPRT_DB_SCHEMA", "custom_import_finality_test")
    monkeypatch.delenv("DB_SCHEMA", raising=False)
    statements: list[str] = []
    monkeypatch.setattr(migration.op, "execute", statements.append)

    migration.downgrade()

    normalized = _normalized(statements)
    guard = normalized.index("custom_import_generation_finality_downgrade_blocked")
    first_drop = normalized.index("DROP TRIGGER IF EXISTS")
    current_fk = normalized.index("DROP CONSTRAINT IF EXISTS custom_import_current_generation_seal_fkey")
    event_fk = normalized.index("DROP CONSTRAINT IF EXISTS custom_import_publication_event_to_seal_fkey")
    no_change_table = normalized.index(
        'DROP TABLE IF EXISTS "custom_import_finality_test"."custom_import_no_change_seal"'
    )
    generation_table = normalized.index(
        'DROP TABLE IF EXISTS "custom_import_finality_test"."custom_import_generation_seal"'
    )
    assert guard < first_drop < current_fk < generation_table
    assert event_fk < generation_table
    assert no_change_table < generation_table
    assert "producing_fence IS NOT NULL OR producing_token_sha256 IS NOT NULL" in normalized
    assert "DROP CONSTRAINT IF EXISTS custom_import_generation_seal_reference_key" in normalized
    assert "DROP CONSTRAINT IF EXISTS custom_import_generation_execution_fence_key" in normalized
    assert "RENAME COLUMN candidate_sha256 TO generation_sha256" in normalized
    assert "LOCK TABLE" in normalized
    assert "IN SHARE ROW EXCLUSIVE MODE" in normalized
    assert "DROP COLUMN IF EXISTS rejection_id" in normalized
    assert "code ~ '^[a-z][a-z0-9_]{0,62}$'" in normalized
    assert "{{0,62}}" not in normalized
