# Licensed under the HealthPorta Non-Commercial License (see LICENSE).
"""Host-only custody and deferred-DDL regressions for explicit model families."""

from dataclasses import replace
from types import SimpleNamespace
from unittest.mock import AsyncMock
from uuid import UUID

import pytest
from sqlalchemy import CheckConstraint, Column, ForeignKey, Identity, Index, Integer, MetaData, Table, UniqueConstraint

from process import reference_family_archive as archive


@pytest.fixture
def scoped_family_fixture(monkeypatch):
    metadata = MetaData(schema="synthetic_source")
    parent = Table(
        "synthetic_parent",
        metadata,
        Column("id", Integer, Identity(), primary_key=True),
        postgresql_partition_by="RANGE (id)",
    )
    child = Table(
        "synthetic_child",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("parent_id", Integer, ForeignKey("synthetic_source.synthetic_parent.id"), nullable=False),
        UniqueConstraint("parent_id", name="synthetic_child_parent_key"),
        CheckConstraint("id > 0", name="synthetic_child_id_check"),
    )
    Index("synthetic_child_parent_idx", child.c.parent_id)
    models = tuple(SimpleNamespace(__tablename__=table.name, __table__=table) for table in (child, parent))
    spec = archive.ReferenceFamilySpec(
        "synthetic-unregistered",
        models,
        relationships=((models[0], "parent_id", models[1], "id", False, False),),
    )
    dataset_id = UUID(int=42)
    ownership = archive.ReferenceFamilyStageOwnership(
        spec.importer_id,
        dataset_id,
        archive.reference_family_stage_schema(dataset_id),
        100,
        (("synthetic_child", 101), ("synthetic_parent", 102)),
        (("synthetic_parent_id_seq", 103, "synthetic_parent", "id"),),
    )
    catalog_records = [{"relkind": "r", "oid": oid, "index_table_oid": None} for _name, oid in ownership.relation_oids]
    catalog_records.extend(
        (
            {"relkind": "S", "oid": 103, "index_table_oid": None},
            {"relkind": "i", "oid": 104, "index_table_oid": 101},
        )
    )
    catalog = SimpleNamespace(
        schema=AsyncMock(return_value=ownership.schema_oid),
        relations=AsyncMock(side_effect=lambda _session, _schema, name: dict(ownership.relation_oids).get(name)),
        sequences=AsyncMock(return_value=ownership.sequence_oids),
        namespace=AsyncMock(return_value=catalog_records),
        lock=AsyncMock(),
    )
    monkeypatch.setattr(archive, "_schema_oid", catalog.schema)
    monkeypatch.setattr(archive, "_relation_oid", catalog.relations)
    monkeypatch.setattr(archive, "_owned_sequences", catalog.sequences)
    monkeypatch.setattr(archive, "_namespace_relations", catalog.namespace)
    monkeypatch.setattr(archive, "_lock_family", catalog.lock)
    session = SimpleNamespace(in_transaction=lambda: True, execute=AsyncMock(), scalar=AsyncMock(return_value=False))
    return spec, ownership, catalog, session


def _statements(session):
    return [
        " ".join(str(call.args[0].compile(dialect=archive.postgresql.dialect())).split())
        for call in session.execute.await_args_list
    ]


@pytest.mark.asyncio
async def test_unregistered_family_precreates_ordinary_heaps_with_exact_identity_custody(scoped_family_fixture):
    spec, ownership, catalog, session = scoped_family_fixture
    assert spec.importer_id not in archive._SPECS
    observed = await archive.precreate_model_family_stage(session, spec, ownership.dataset_id, include_identity=True)
    assert observed == ownership
    statements = _statements(session)
    assert len(statements) == 3
    assert "GENERATED BY DEFAULT AS IDENTITY" in statements[2]
    assert all(
        fragment not in " ".join(statements)
        for fragment in ("PARTITION BY", "SERIAL", "PRIMARY KEY", "UNIQUE", "CHECK", "CREATE INDEX", "FOREIGN KEY")
    )
    assert all(model.__table__.schema == "synthetic_source" for model in spec.model_types)
    catalog.sequences.assert_awaited_once_with(session, ownership.schema_oid, include_identity=True)
    assert (
        await archive.verify_model_family_stage_ownership(session, spec, ownership, include_identity=True) == ownership
    )
    catalog.sequences.assert_awaited_with(session, ownership.schema_oid, include_identity=True)


@pytest.mark.asyncio
async def test_identity_is_opt_in_and_its_oid_is_reverified(scoped_family_fixture):
    spec, ownership, catalog, session = scoped_family_fixture
    with pytest.raises(archive.ReferenceFamilyArchiveError, match="sequence set"):
        await archive.capture_model_family_stage_ownership(session, spec, ownership.dataset_id)
    catalog.sequences.assert_awaited_with(session, ownership.schema_oid, include_identity=False)
    catalog.sequences.return_value = (("synthetic_parent_id_seq", 999, "synthetic_parent", "id"),)
    catalog.namespace.return_value[-2]["oid"] = 999
    with pytest.raises(archive.ReferenceFamilyArchiveError, match="ownership differs"):
        await archive.verify_model_family_stage_ownership(session, spec, ownership, include_identity=True)


@pytest.mark.asyncio
async def test_completion_finishes_all_indexes_and_constraints_before_set_checks(scoped_family_fixture):
    spec, ownership, catalog, session = scoped_family_fixture

    async def has_invalid_relationship(statement):
        statements = _statements(session)
        assert sum("PRIMARY KEY" in sql for sql in statements) == 2
        assert any("UNIQUE" in sql for sql in statements)
        assert any("synthetic_child_parent_idx" in sql for sql in statements)
        assert any("synthetic_child_id_check" in sql for sql in statements)
        assert "SELECT EXISTS" in str(statement) and "NOT EXISTS" in str(statement)
        return False

    session.scalar.side_effect = has_invalid_relationship
    await archive.complete_model_family_stage(session, spec, ownership, include_identity=True)
    catalog.sequences.assert_awaited_once_with(session, ownership.schema_oid, include_identity=True)
    assert session.scalar.await_count == 2
    assert all("FOREIGN KEY" not in statement and "TRIGGER" not in statement for statement in _statements(session))


@pytest.mark.asyncio
async def test_bad_relationship_set_is_not_reported_as_complete(scoped_family_fixture):
    spec, ownership, _catalog, session = scoped_family_fixture
    session.scalar.return_value = True
    with pytest.raises(archive.ReferenceFamilyArchiveError, match="relationship differs"):
        await archive.complete_model_family_stage(session, spec, ownership, include_identity=True)


@pytest.mark.asyncio
@pytest.mark.parametrize("failure", ("invalid", "changed", "relationship"))
async def test_ptg_completion_preserves_custody_errors_and_native_relationship_failure(
    scoped_family_fixture, monkeypatch, failure
):
    from process.ptg_parts import ptg2_physical_binding as binding

    spec, ownership, _catalog, session = scoped_family_fixture
    monkeypatch.setattr(binding, "local_data_family_spec", lambda: spec)
    if failure == "relationship":
        session.scalar.return_value = True
        with pytest.raises(archive.ReferenceFamilyArchiveError, match="relationship differs"):
            await binding.complete_local_data_family(session, ownership)
        assert session.execute.await_count
    else:
        token = object() if failure == "invalid" else replace(ownership, schema_oid=999)
        message = "ownership is invalid" if failure == "invalid" else "ownership changed"
        with pytest.raises(binding.PTG2PhysicalBindingError, match=message):
            await binding.complete_local_data_family(session, token)
        session.execute.assert_not_awaited()


@pytest.mark.asyncio
@pytest.mark.parametrize("operation", ("verify", "complete", "cleanup"))
@pytest.mark.parametrize("mismatch", ("schema", "relation", "sequence", "scope", "incomplete"))
async def test_mismatched_stage_ownership_refuses_before_completion_or_cleanup_ddl(
    scoped_family_fixture, operation, mismatch
):
    spec, ownership, _catalog, session = scoped_family_fixture
    ownership_by_mismatch = {
        "schema": {"schema_oid": 999},
        "relation": {"relation_oids": (("synthetic_child", 999), ("synthetic_parent", 102))},
        "sequence": {"sequence_oids": (("synthetic_parent_id_seq", 999, "synthetic_parent", "id"),)},
        "scope": {"importer_id": "synthetic-other"},
        "incomplete": {"relation_oids": (("synthetic_child", 101),)},
    }
    session.scalar.return_value = ownership.schema_oid
    function = {
        "verify": archive.verify_model_family_stage_ownership,
        "complete": archive.complete_model_family_stage,
        "cleanup": archive.cleanup_model_family_stage,
    }[operation]
    with pytest.raises(archive.ReferenceFamilyArchiveError, match="ownership differs"):
        await function(session, spec, replace(ownership, **ownership_by_mismatch[mismatch]), include_identity=True)
    session.execute.assert_not_awaited()


@pytest.mark.asyncio
@pytest.mark.parametrize("operation", ("capture", "verify", "complete", "cleanup"))
@pytest.mark.parametrize("unexpected", ("heap", "sequence", "index"))
async def test_unexpected_namespace_objects_refuse_before_ddl(scoped_family_fixture, operation, unexpected):
    spec, ownership, catalog, session = scoped_family_fixture
    catalog.namespace.return_value.append(
        {"relkind": {"heap": "r", "sequence": "S", "index": "i"}[unexpected], "oid": 999, "index_table_oid": 998}
    )
    session.scalar.return_value = ownership.schema_oid
    function = {
        "capture": archive.capture_model_family_stage_ownership,
        "verify": archive.verify_model_family_stage_ownership,
        "complete": archive.complete_model_family_stage,
        "cleanup": archive.cleanup_model_family_stage,
    }[operation]
    argument = ownership.dataset_id if operation == "capture" else ownership
    with pytest.raises(archive.ReferenceFamilyArchiveError, match="unexpected relation"):
        await function(session, spec, argument, include_identity=True)
    session.execute.assert_not_awaited()


@pytest.mark.asyncio
async def test_cleanup_locks_exact_family_and_uses_restrict_without_cascade(scoped_family_fixture):
    spec, ownership, catalog, session = scoped_family_fixture
    session.scalar.side_effect = (ownership.schema_oid, 0)
    await archive.cleanup_model_family_stage(session, spec, ownership, include_identity=True)
    catalog.lock.assert_awaited_once_with(
        session, ownership.schema_name, spec.archive_names, "ACCESS EXCLUSIVE", nowait=True
    )
    catalog.sequences.assert_awaited_once_with(session, ownership.schema_oid, include_identity=True)
    assert _statements(session) == [
        f'DROP TABLE "{ownership.schema_name}"."synthetic_child", "{ownership.schema_name}"."synthetic_parent" RESTRICT',
        f'DROP SCHEMA "{ownership.schema_name}"',
    ]


@pytest.mark.asyncio
async def test_cleanup_refuses_incomplete_token_even_when_schema_is_absent(scoped_family_fixture):
    spec, ownership, catalog, session = scoped_family_fixture
    session.scalar.return_value = None
    with pytest.raises(archive.ReferenceFamilyArchiveError, match="ownership differs"):
        await archive.cleanup_model_family_stage(
            session, spec, replace(ownership, relation_oids=()), include_identity=True
        )
    session.scalar.assert_not_awaited()
    session.execute.assert_not_awaited()
    catalog.lock.assert_not_awaited()
    await archive.cleanup_model_family_stage(session, spec, ownership, include_identity=True)
    session.execute.assert_not_awaited()


@pytest.mark.asyncio
@pytest.mark.parametrize("operation", ("capture", "verify", "precreate", "complete", "cleanup"))
async def test_every_public_lifecycle_operation_requires_caller_transaction(scoped_family_fixture, operation):
    spec, ownership, catalog, session = scoped_family_fixture
    session.in_transaction = lambda: False
    function = {
        "capture": archive.capture_model_family_stage_ownership,
        "verify": archive.verify_model_family_stage_ownership,
        "precreate": archive.precreate_model_family_stage,
        "complete": archive.complete_model_family_stage,
        "cleanup": archive.cleanup_model_family_stage,
    }[operation]
    argument = ownership.dataset_id if operation in {"capture", "precreate"} else ownership
    with pytest.raises(archive.ReferenceFamilyArchiveError, match="caller transaction"):
        await function(session, spec, argument, include_identity=True)
    session.execute.assert_not_awaited()
    session.scalar.assert_not_awaited()
    catalog.schema.assert_not_awaited()
