# Licensed under the HealthPorta Non-Commercial License (see LICENSE).

"""Static contract coverage for the schema-only generation-finality revision."""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.script import ScriptDirectory

ROOT = Path(__file__).resolve().parents[1]
MIGRATION_PATH = ROOT / "alembic" / "versions" / "20260917130000_custom_import_generation_finality.py"
PLANS_MIGRATION_PATH = ROOT / "alembic" / "versions" / "20261005020000_custom_import_sealed_append_plans.py"


def _migration():
    spec = importlib.util.spec_from_file_location("custom_import_finality_migration", MIGRATION_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _normalized(statements: list[str]) -> str:
    return "\n".join(" ".join(statement.split()) for statement in statements)


def test_finality_migration_is_schema_only_and_installs_fenced_seal_guards(monkeypatch):
    migration = _migration()
    monkeypatch.setenv("HLTHPRT_DB_SCHEMA", "custom_import_finality_test")
    monkeypatch.delenv("DB_SCHEMA", raising=False)
    statements: list[str] = []
    monkeypatch.setattr(migration.op, "execute", statements.append)

    migration.upgrade()

    normalized = _normalized(statements)
    assert migration.down_revision == "20260914120000_npi_result_generation"
    assert "INSERT INTO" not in normalized
    assert "UPDATE custom_import" not in normalized
    assert "CREATE TABLE" in normalized
    assert "custom_import_generation_seal" in normalized
    assert "custom_import_no_change_seal" in normalized
    assert "producing_fence BIGINT" in normalized
    assert "producing_token_sha256 BYTEA" in normalized
    assert "custom_import_generation_producing_authority_check" in normalized
    assert "RENAME COLUMN generation_sha256 TO candidate_sha256" in normalized
    assert "DROP CONSTRAINT custom_import_generation_content_key" in normalized
    assert "DROP CONSTRAINT custom_import_generation_execution_key" in normalized
    assert "custom_import_generation_execution_fence_key" in normalized
    assert "NOT VALID" in normalized
    assert "custom_import_current_generation_seal_fkey" in normalized
    assert "custom_import_publication_event_to_seal_fkey" in normalized
    assert "custom_import_no_change_seal_base_finality_fkey" in normalized
    assert "custom_import_publication_event_pointer_version_key" in normalized
    assert "custom_import_publication_event_no_change_execution_key" in normalized
    assert "WHERE finality_contract = 'custom-import-finality/v1'" in normalized
    assert "ADD COLUMN rejection_id BIGINT GENERATED BY DEFAULT AS IDENTITY" in normalized
    assert "custom_import_generation_seal_duplicate_child_key" in normalized
    assert "GROUP BY child.family_revision_id, child.collection_slot, child_revision.child_key_sha256" in normalized
    assert "current_setting('transaction_isolation') <> 'read committed'" in normalized
    assert "clock_timestamp()" in normalized
    assert "FOR UPDATE" in normalized
    assert normalized.count("SECURITY DEFINER") == 6
    assert normalized.count("SET search_path = pg_catalog") == 6
    assert normalized.count("REVOKE ALL ON FUNCTION") == 6
    for table_name in migration._APPEND_GUARD_TABLES:
        assert f'BEFORE INSERT ON "custom_import_finality_test"."{table_name}"' in normalized
    for table_name in migration._DATASET_FIRST_INSERT_TABLES:
        assert f'BEFORE INSERT ON "custom_import_finality_test"."{table_name}"' in normalized
    assert "custom_import_generation_seal_immutable_row_guard" in normalized
    assert "custom_import_no_change_seal_immutable_row_guard" in normalized


def test_finality_downgrade_removes_references_before_finality_tables(monkeypatch):
    migration = _migration()
    monkeypatch.setenv("HLTHPRT_DB_SCHEMA", "custom_import_finality_test")
    monkeypatch.delenv("DB_SCHEMA", raising=False)
    statements: list[str] = []
    monkeypatch.setattr(migration.op, "execute", statements.append)

    migration.downgrade()

    normalized = _normalized(statements)
    guard = normalized.index("custom_import_generation_finality_downgrade_blocked")
    first_drop = normalized.index("DROP TRIGGER IF EXISTS")
    current_fk = normalized.index("DROP CONSTRAINT IF EXISTS custom_import_current_generation_seal_fkey")
    event_fk = normalized.index("DROP CONSTRAINT IF EXISTS custom_import_publication_event_to_seal_fkey")
    no_change_table = normalized.index(
        'DROP TABLE IF EXISTS "custom_import_finality_test"."custom_import_no_change_seal"'
    )
    generation_table = normalized.index(
        'DROP TABLE IF EXISTS "custom_import_finality_test"."custom_import_generation_seal"'
    )
    assert guard < first_drop < current_fk < generation_table
    assert event_fk < generation_table
    assert no_change_table < generation_table
    assert "producing_fence IS NOT NULL OR producing_token_sha256 IS NOT NULL" in normalized
    assert "DROP CONSTRAINT IF EXISTS custom_import_generation_seal_reference_key" in normalized
    assert "DROP CONSTRAINT IF EXISTS custom_import_generation_execution_fence_key" in normalized
    assert "RENAME COLUMN candidate_sha256 TO generation_sha256" in normalized
    assert "LOCK TABLE" in normalized
    assert "IN SHARE ROW EXCLUSIVE MODE" in normalized
    assert "DROP COLUMN IF EXISTS rejection_id" in normalized
    assert "code ~ '^[a-z][a-z0-9_]{0,62}$'" in normalized
    assert "{{0,62}}" not in normalized


def _plans_migration():
    spec = importlib.util.spec_from_file_location("custom_import_sealed_append_plans", PLANS_MIGRATION_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _append_body():
    legacy = _migration()
    return legacy._with_read_committed_guard(legacy._APPEND_GUARD_FUNCTION_BODY)


@pytest.mark.parametrize("operation", ("upgrade", "downgrade"))
def test_sealed_append_plans_replace_only_an_existing_function(monkeypatch, operation):
    migration = _plans_migration()
    monkeypatch.setenv("HLTHPRT_DB_SCHEMA", "synthetic_append")
    monkeypatch.delenv("DB_SCHEMA", raising=False)
    statements = []
    monkeypatch.setattr(migration.op, "execute", statements.append)
    getattr(migration, operation)()

    assert migration.revision == "20261005020000_custom_import_sealed_append_plans"
    assert migration.down_revision == "20261001110000_profile_initial_publication"
    assert len(statements) == 2
    assert statements[0].startswith("DO $function$")
    assert "pg_catalog.to_regprocedure" in statements[0]
    assert "custom_import_sealed_append_function_missing" in statements[0]
    assert 'E\'"synthetic_append"."guard_custom_import_sealed_append"()\'' in statements[0]
    assert (
        statements[1]
        .lstrip()
        .startswith('CREATE OR REPLACE FUNCTION "synthetic_append"."guard_custom_import_sealed_append"()')
    )
    for declaration in ("RETURNS trigger", "LANGUAGE plpgsql", "SECURITY DEFINER", "SET search_path = pg_catalog"):
        assert statements[1].count(declaration) == 1
    for forbidden in ("DROP ", "GRANT ", "REVOKE ", "CREATE TABLE", "CREATE TRIGGER", "ALTER TABLE", "CREATE INDEX"):
        assert forbidden not in "\n".join(statements)
    if operation == "downgrade":
        original = _migration()._append_guard_function_sql("synthetic_append")
        assert statements[1] == original.replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1)


def test_sealed_append_plans_extend_the_single_installed_migration_head():
    config = Config(str(ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(ROOT / "alembic"))
    script = ScriptDirectory.from_config(config)
    revision = _plans_migration().revision
    assert script.get_heads() == ["20261007000000_custom_import_rejection_anti_joins"]
    assert tuple(
        step.revision.revision for step in script._upgrade_revs("head", "20261001110000_profile_initial_publication")
    ) == (
        revision,
        "20261005030000_source_profile_statement_pins",
        "20261005100000_rooted_graph_set_validation",
        "20261005110000_ptg_set_validation",
        "20261005120000_practitioner_set_validation",
        "20261005130000_provider_dataset_candidates",
        "20261005030000_custom_import_snapshot_storage",
        "20261005040000_custom_import_bulk_snapshot_writers",
        "20261005050000_custom_import_legacy_snapshot_writers",
        "20261005060000_custom_import_snapshot_finality",
        "20261005070000_custom_import_materialization_storage",
        "20261005080000_custom_import_writer_cutover",
        "20261007000000_custom_import_rejection_anti_joins",
    )


def test_sealed_append_plans_preserve_query_order_bindings_and_exact_dynamic_fallback():
    migration = _plans_migration()
    body = _append_body()
    static = migration._static_body(body)
    matches = list(migration._EXECUTE.finditer(body))
    assert len(matches) == 27
    restored = static
    for match in matches:
        query = "".join(re.findall(r"'([^']*)'", match["strings"]))
        bindings = [binding.strip() for binding in match["using"].split(",")]
        receivers = ", ".join(receiver.strip() for receiver in match["into"].split(","))
        query = re.sub(r"\$(\d+)", lambda placeholder: f"({bindings[int(placeholder[1]) - 1]})", query)
        query = query.replace("%I", migration._STATIC_SCHEMA)
        if query.startswith("SELECT EXISTS ("):
            query += f" INTO {receivers}"
        else:
            query = query.replace(" FROM ", f" INTO {receivers} FROM ", 1)
        assert query + ";" in restored
        restored = restored.replace(query + ";", match[0], 1)
    assert restored == body
    assert static.count("FOR UPDATE") == 3
    assert static.count("clock_timestamp()") == 1
    assert (
        static.index("INTO locked_dataset_id")
        < static.index("INTO authority_state")
        < static.index("INTO authority_expires_at")
    )
    assert static.index("INTO authority_expires_at") < static.index("authority_expires_at <= clock_timestamp()")
    planned = migration._planned_body(_migration(), body, "synthetic_append")
    original_statements = body.split("    BEGIN\n", 1)[1].removesuffix("    END;\n")
    assert "        ELSE\n" + original_statements + "        END IF;\n" in planned
    assert planned.count(_migration()._read_committed_guard()) == 2


@pytest.mark.parametrize("schema", ("mrf", 'synthetic"quoted', "synthetic'$1\\$function$__SEALED_APPEND_SCHEMA__"))
def test_sealed_append_plans_quote_schema_only_after_rewriting(schema):
    migration = _plans_migration()
    legacy = _migration()
    body = migration._planned_body(legacy, _append_body(), schema)
    literal = "E'" + schema.replace("\\", "\\\\").replace("'", "''") + "'"
    assert f"IF TG_TABLE_SCHEMA = {literal} THEN\n" in body
    assert f"FROM {legacy._quote(schema)}.custom_import_dataset WHERE dataset_id = (NEW.dataset_id) FOR UPDATE;" in body
    definition = migration._definition(legacy._qualified(schema, migration._FUNCTION_NAME), body)
    delimiter = migration._delimiter(body)
    assert delimiter not in body
    assert f"    AS {delimiter}\n    {body}\n    {delimiter}" in definition
    if "$function$" in schema:
        assert delimiter != "$function$"
    guard = migration._existing_function_guard(legacy._qualified(schema, migration._FUNCTION_NAME))
    assert guard.startswith("DO " + migration._delimiter(guard.split("\n", 1)[1].rsplit("\n", 1)[0]))


@pytest.mark.parametrize(
    ("old", "new"),
    (
        ("TG_TABLE_SCHEMA", "TG_TABLE_NAME"),
        ("%I.custom_import_dataset", "%L.custom_import_dataset"),
        ("NEW.dataset_id", "NEW.dataset_id + 1"),
        ("WHERE dataset_id = $1 FOR UPDATE", "WHERE dataset_id = $9 FOR UPDATE"),
        ("RETURN NEW;", "IF FOUND THEN RETURN NEW; END IF;"),
        ("RETURN NEW;", "GET DIAGNOSTICS locked_dataset_id = ROW_COUNT; RETURN NEW;"),
        ("clock_timestamp()", "now()"),
    ),
)
def test_sealed_append_plans_reject_unrecognized_source_shapes(old, new):
    migration = _plans_migration()
    with pytest.raises(RuntimeError, match="source differs"):
        migration._static_body(_append_body().replace(old, new, 1))


@pytest.mark.parametrize("operation", ("upgrade", "downgrade"))
def test_sealed_append_plans_reject_historical_source_drift_before_ddl(monkeypatch, operation):
    migration = _plans_migration()
    original_read = Path.read_bytes
    statements = []
    monkeypatch.setattr(migration.op, "execute", statements.append)
    monkeypatch.setattr(
        Path, "read_bytes", lambda path: original_read(path) + (b"\n" if path == MIGRATION_PATH else b"")
    )
    with pytest.raises(RuntimeError, match="source differs"):
        getattr(migration, operation)()
    assert statements == []
