# Licensed under the HealthPorta Non-Commercial License (see LICENSE).
"""Persist immutable connector source bindings for custom-import operators.

Revision ID: 20260923030000_custom_import_source_binding
Revises: 20260922010000_custom_import_execution_request_identity
"""

from __future__ import annotations

import os

from alembic import op

revision = "20260923030000_custom_import_source_binding"
down_revision = "20260922010000_custom_import_execution_request_identity"
branch_labels = None
depends_on = None


_BINDING_CONTRACT = "custom-import/source-binding/v1"
_CONNECTOR_KIND = "snowflake_bundle"
_BINDING_TABLE = "custom_import_source_binding_revision"
_DEFINITION_TABLE = "custom_import_definition_revision"
_EXECUTION_TABLE = "custom_import_execution"
_BINDING_IMMUTABLE_TRIGGER = "custom_import_source_binding_revision_immutable_row_guard"
_BINDING_TRUNCATE_TRIGGER = "custom_import_source_binding_revision_truncate_guard"
_EXECUTION_BINDING_GUARD = "guard_custom_import_execution_source_binding_revision"
_EXECUTION_BINDING_TRIGGER = "custom_import_execution_source_binding_revision_guard"
_EXECUTION_BINDING_FKEY = "custom_import_execution_source_binding_revision_fkey"
_EXECUTION_BINDING_CHECK = "custom_import_execution_source_binding_identity_check"


def _schema() -> str:
    runtime_schema = os.getenv("HLTHPRT_DB_SCHEMA")
    legacy_schema = os.getenv("DB_SCHEMA")
    if runtime_schema and legacy_schema and runtime_schema != legacy_schema:
        raise RuntimeError("DB_SCHEMA and HLTHPRT_DB_SCHEMA must match")
    return runtime_schema or legacy_schema or "mrf"


def _quote(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def _qualified(schema: str, object_name: str) -> str:
    return f"{_quote(schema)}.{_quote(object_name)}"


def _binding_table_sql(schema: str) -> str:
    binding = _qualified(schema, _BINDING_TABLE)
    definition = _qualified(schema, _DEFINITION_TABLE)
    return f"""
    CREATE TABLE {binding} (
        source_binding_revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        dataset_id BIGINT NOT NULL,
        definition_revision_id BIGINT NOT NULL,
        schema_revision_id BIGINT NOT NULL,
        revision_number INTEGER NOT NULL,
        binding_contract VARCHAR(63) NOT NULL,
        connector_kind VARCHAR(32) NOT NULL,
        definition_sha256 BYTEA NOT NULL,
        schema_sha256 BYTEA NOT NULL,
        source_object_fingerprint_sha256 BYTEA NOT NULL,
        source_object_version VARCHAR(255) NOT NULL,
        canonical_binding TEXT NOT NULL,
        binding_sha256 BYTEA NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT transaction_timestamp(),
        CONSTRAINT custom_import_source_binding_revision_pkey
            PRIMARY KEY (source_binding_revision_id),
        CONSTRAINT custom_import_source_binding_revision_number_key
            UNIQUE (definition_revision_id, revision_number),
        CONSTRAINT custom_import_source_binding_revision_hash_key
            UNIQUE (definition_revision_id, binding_sha256),
        CONSTRAINT custom_import_source_binding_revision_owner_key
            UNIQUE (
                source_binding_revision_id,
                dataset_id,
                definition_revision_id,
                schema_revision_id
            ),
        CONSTRAINT custom_import_source_binding_revision_definition_fkey
            FOREIGN KEY (definition_revision_id, dataset_id, schema_revision_id)
            REFERENCES {definition} (definition_revision_id, dataset_id, schema_revision_id)
            ON DELETE RESTRICT,
        CONSTRAINT custom_import_source_binding_revision_shape_check CHECK (
            binding_contract = '{_BINDING_CONTRACT}'
            AND connector_kind = '{_CONNECTOR_KIND}'
            AND revision_number > 0
            AND octet_length(definition_sha256) = 32
            AND octet_length(schema_sha256) = 32
            AND octet_length(source_object_fingerprint_sha256) = 32
            AND source_object_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{{0,127}}$'
            AND octet_length(canonical_binding) BETWEEN 2 AND 1048576
            AND octet_length(binding_sha256) = 32
            AND binding_sha256 = pg_catalog.sha256(
                convert_to(binding_contract || ':' || canonical_binding, 'UTF8')
            )
        )
    )
    """


def _binding_immutable_trigger_sql(schema: str) -> str:
    binding = _qualified(schema, _BINDING_TABLE)
    immutable_guard = _qualified(schema, "guard_custom_import_immutable_row")
    return f"""
    CREATE TRIGGER {_quote(_BINDING_IMMUTABLE_TRIGGER)}
    BEFORE UPDATE OR DELETE ON {binding}
    FOR EACH ROW EXECUTE FUNCTION {immutable_guard}()
    """


def _binding_truncate_trigger_sql(schema: str) -> str:
    binding = _qualified(schema, _BINDING_TABLE)
    immutable_guard = _qualified(schema, "guard_custom_import_immutable_row")
    return f"""
    CREATE TRIGGER {_quote(_BINDING_TRUNCATE_TRIGGER)}
    BEFORE TRUNCATE ON {binding}
    FOR EACH STATEMENT EXECUTE FUNCTION {immutable_guard}()
    """


def _enable_trigger_sql(schema: str, table_name: str, trigger_name: str) -> str:
    return f"ALTER TABLE {_qualified(schema, table_name)} ENABLE ALWAYS TRIGGER {_quote(trigger_name)}"


def _execution_binding_column_sql(schema: str) -> str:
    execution = _qualified(schema, _EXECUTION_TABLE)
    binding = _qualified(schema, _BINDING_TABLE)
    return f"""
    ALTER TABLE {execution}
        ADD COLUMN source_binding_revision_id BIGINT,
        ADD CONSTRAINT {_quote(_EXECUTION_BINDING_CHECK)} CHECK (
            source_binding_revision_id IS NULL OR request_identity_sha256 IS NOT NULL
        ),
        ADD CONSTRAINT {_quote(_EXECUTION_BINDING_FKEY)}
            FOREIGN KEY (
                source_binding_revision_id,
                dataset_id,
                definition_revision_id,
                schema_revision_id
            )
            REFERENCES {binding} (
                source_binding_revision_id,
                dataset_id,
                definition_revision_id,
                schema_revision_id
            )
            ON DELETE RESTRICT
    """


def _execution_binding_guard_sql(schema: str) -> str:
    function = _qualified(schema, _EXECUTION_BINDING_GUARD)
    return f"""
    CREATE FUNCTION {function}()
    RETURNS trigger
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = pg_catalog
    AS $function$
    BEGIN
        IF NEW.source_binding_revision_id IS DISTINCT FROM OLD.source_binding_revision_id THEN
            RAISE EXCEPTION 'custom_import_execution_source_binding_revision_immutable'
                USING ERRCODE = 'P0001';
        END IF;
        RETURN NEW;
    END;
    $function$
    """


def _revoke_execution_binding_guard_sql(schema: str) -> str:
    return f"REVOKE ALL ON FUNCTION {_qualified(schema, _EXECUTION_BINDING_GUARD)}() FROM PUBLIC"


def _execution_binding_trigger_sql(schema: str) -> str:
    execution = _qualified(schema, _EXECUTION_TABLE)
    function = _qualified(schema, _EXECUTION_BINDING_GUARD)
    return f"""
    CREATE TRIGGER {_quote(_EXECUTION_BINDING_TRIGGER)}
    BEFORE UPDATE ON {execution}
    FOR EACH ROW EXECUTE FUNCTION {function}()
    """


def _downgrade_guard_sql(schema: str) -> str:
    binding = _qualified(schema, _BINDING_TABLE)
    execution = _qualified(schema, _EXECUTION_TABLE)
    return f"""
    DO $block$
    BEGIN
        LOCK TABLE {execution} IN ACCESS EXCLUSIVE MODE;
        LOCK TABLE {binding} IN ACCESS EXCLUSIVE MODE;
        IF EXISTS (SELECT 1 FROM {binding})
           OR EXISTS (
                SELECT 1
                  FROM {execution}
                 WHERE source_binding_revision_id IS NOT NULL
           ) THEN
            RAISE EXCEPTION 'custom_import_source_binding_downgrade_blocked'
                USING ERRCODE = 'P0001';
        END IF;
    END;
    $block$
    """


def _drop_execution_binding_sql(schema: str) -> str:
    execution = _qualified(schema, _EXECUTION_TABLE)
    return f"""
    ALTER TABLE {execution}
        DROP CONSTRAINT IF EXISTS {_quote(_EXECUTION_BINDING_FKEY)},
        DROP CONSTRAINT IF EXISTS {_quote(_EXECUTION_BINDING_CHECK)},
        DROP COLUMN IF EXISTS source_binding_revision_id
    """


def _drop_trigger_sql(schema: str, table_name: str, trigger_name: str) -> str:
    return f"DROP TRIGGER IF EXISTS {_quote(trigger_name)} ON {_qualified(schema, table_name)}"


def upgrade() -> None:
    """Add immutable source bindings without changing legacy executions."""

    schema = _schema()
    op.execute(_binding_table_sql(schema))
    op.execute(_binding_immutable_trigger_sql(schema))
    op.execute(_enable_trigger_sql(schema, _BINDING_TABLE, _BINDING_IMMUTABLE_TRIGGER))
    op.execute(_binding_truncate_trigger_sql(schema))
    op.execute(_enable_trigger_sql(schema, _BINDING_TABLE, _BINDING_TRUNCATE_TRIGGER))
    op.execute(_execution_binding_column_sql(schema))
    op.execute(_execution_binding_guard_sql(schema))
    op.execute(_revoke_execution_binding_guard_sql(schema))
    op.execute(_execution_binding_trigger_sql(schema))
    op.execute(_enable_trigger_sql(schema, _EXECUTION_TABLE, _EXECUTION_BINDING_TRIGGER))


def downgrade() -> None:
    """Refuse to discard retained bindings or execution lineage."""

    schema = _schema()
    op.execute(_downgrade_guard_sql(schema))
    op.execute(_drop_trigger_sql(schema, _EXECUTION_TABLE, _EXECUTION_BINDING_TRIGGER))
    op.execute(f"DROP FUNCTION IF EXISTS {_qualified(schema, _EXECUTION_BINDING_GUARD)}()")
    op.execute(_drop_execution_binding_sql(schema))
    op.execute(_drop_trigger_sql(schema, _BINDING_TABLE, _BINDING_TRUNCATE_TRIGGER))
    op.execute(_drop_trigger_sql(schema, _BINDING_TABLE, _BINDING_IMMUTABLE_TRIGGER))
    op.execute(f"DROP TABLE IF EXISTS {_qualified(schema, _BINDING_TABLE)}")
