# Licensed under the HealthPorta Non-Commercial License (see LICENSE).
"""Static USPS Publication 28 normalization tables for address-canonical v1.

Generated from official USPS Postal Explorer pages on 2026-06-11 and then
checked into the repo. Runtime code must not fetch USPS or read lookup tables.
Sources:
- https://pe.usps.com/text/pub28/28apc_002.htm
- https://pe.usps.com/text/pub28/28apc_003.htm
- https://pe.usps.com/text/pub28/28apb.htm
- https://pe.usps.com/text/pub28/28api_007.htm
"""

from __future__ import annotations

PUB28_STREET_SUFFIX_MAP: dict[str, str] = {'allee': 'aly',
 'alley': 'aly',
 'ally': 'aly',
 'aly': 'aly',
 'anex': 'anx',
 'annex': 'anx',
 'annx': 'anx',
 'anx': 'anx',
 'arc': 'arc',
 'arcade': 'arc',
 'av': 'ave',
 'ave': 'ave',
 'aven': 'ave',
 'avenu': 'ave',
 'avenue': 'ave',
 'avn': 'ave',
 'avnue': 'ave',
 'bayoo': 'byu',
 'bayou': 'byu',
 'bch': 'bch',
 'beach': 'bch',
 'bend': 'bnd',
 'bg': 'bg',
 'bgs': 'bgs',
 'blf': 'blf',
 'blfs': 'blfs',
 'bluf': 'blf',
 'bluff': 'blf',
 'bluffs': 'blfs',
 'blvd': 'blvd',
 'bnd': 'bnd',
 'bot': 'btm',
 'bottm': 'btm',
 'bottom': 'btm',
 'boul': 'blvd',
 'boulevard': 'blvd',
 'boulv': 'blvd',
 'br': 'br',
 'branch': 'br',
 'brdge': 'brg',
 'brg': 'brg',
 'bridge': 'brg',
 'brk': 'brk',
 'brks': 'brks',
 'brnch': 'br',
 'brook': 'brk',
 'brooks': 'brks',
 'btm': 'btm',
 'burg': 'bg',
 'burgs': 'bgs',
 'byp': 'byp',
 'bypa': 'byp',
 'bypas': 'byp',
 'bypass': 'byp',
 'byps': 'byp',
 'byu': 'byu',
 'camp': 'cp',
 'canyn': 'cyn',
 'canyon': 'cyn',
 'cape': 'cpe',
 'causeway': 'cswy',
 'causwa': 'cswy',
 'cen': 'ctr',
 'cent': 'ctr',
 'center': 'ctr',
 'centers': 'ctrs',
 'centr': 'ctr',
 'centre': 'ctr',
 'cir': 'cir',
 'circ': 'cir',
 'circl': 'cir',
 'circle': 'cir',
 'circles': 'cirs',
 'cirs': 'cirs',
 'clb': 'clb',
 'clf': 'clf',
 'clfs': 'clfs',
 'cliff': 'clf',
 'cliffs': 'clfs',
 'club': 'clb',
 'cmn': 'cmn',
 'cmns': 'cmns',
 'cmp': 'cp',
 'cnter': 'ctr',
 'cntr': 'ctr',
 'cnyn': 'cyn',
 'common': 'cmn',
 'commons': 'cmns',
 'cor': 'cor',
 'corner': 'cor',
 'corners': 'cors',
 'cors': 'cors',
 'course': 'crse',
 'court': 'ct',
 'courts': 'cts',
 'cove': 'cv',
 'coves': 'cvs',
 'cp': 'cp',
 'cpe': 'cpe',
 'crcl': 'cir',
 'crcle': 'cir',
 'creek': 'crk',
 'cres': 'cres',
 'crescent': 'cres',
 'crest': 'crst',
 'crk': 'crk',
 'crossing': 'xing',
 'crossroad': 'xrd',
 'crossroads': 'xrds',
 'crse': 'crse',
 'crsent': 'cres',
 'crsnt': 'cres',
 'crssng': 'xing',
 'crst': 'crst',
 'cswy': 'cswy',
 'ct': 'ct',
 'ctr': 'ctr',
 'ctrs': 'ctrs',
 'cts': 'cts',
 'curv': 'curv',
 'curve': 'curv',
 'cv': 'cv',
 'cvs': 'cvs',
 'cyn': 'cyn',
 'dale': 'dl',
 'dam': 'dm',
 'div': 'dv',
 'divide': 'dv',
 'dl': 'dl',
 'dm': 'dm',
 'dr': 'dr',
 'driv': 'dr',
 'drive': 'dr',
 'drives': 'drs',
 'drs': 'drs',
 'drv': 'dr',
 'dv': 'dv',
 'dvd': 'dv',
 'est': 'est',
 'estate': 'est',
 'estates': 'ests',
 'ests': 'ests',
 'exp': 'expy',
 'expr': 'expy',
 'express': 'expy',
 'expressway': 'expy',
 'expw': 'expy',
 'expy': 'expy',
 'ext': 'ext',
 'extension': 'ext',
 'extensions': 'exts',
 'extn': 'ext',
 'extnsn': 'ext',
 'exts': 'exts',
 'fall': 'fall',
 'falls': 'fls',
 'ferry': 'fry',
 'field': 'fld',
 'fields': 'flds',
 'flat': 'flt',
 'flats': 'flts',
 'fld': 'fld',
 'flds': 'flds',
 'fls': 'fls',
 'flt': 'flt',
 'flts': 'flts',
 'ford': 'frd',
 'fords': 'frds',
 'forest': 'frst',
 'forests': 'frst',
 'forg': 'frg',
 'forge': 'frg',
 'forges': 'frgs',
 'fork': 'frk',
 'forks': 'frks',
 'fort': 'ft',
 'frd': 'frd',
 'frds': 'frds',
 'freeway': 'fwy',
 'freewy': 'fwy',
 'frg': 'frg',
 'frgs': 'frgs',
 'frk': 'frk',
 'frks': 'frks',
 'frry': 'fry',
 'frst': 'frst',
 'frt': 'ft',
 'frway': 'fwy',
 'frwy': 'fwy',
 'fry': 'fry',
 'ft': 'ft',
 'fwy': 'fwy',
 'garden': 'gdn',
 'gardens': 'gdns',
 'gardn': 'gdn',
 'gateway': 'gtwy',
 'gatewy': 'gtwy',
 'gatway': 'gtwy',
 'gdn': 'gdn',
 'gdns': 'gdns',
 'glen': 'gln',
 'glens': 'glns',
 'gln': 'gln',
 'glns': 'glns',
 'grden': 'gdn',
 'grdn': 'gdn',
 'grdns': 'gdns',
 'green': 'grn',
 'greens': 'grns',
 'grn': 'grn',
 'grns': 'grns',
 'grov': 'grv',
 'grove': 'grv',
 'groves': 'grvs',
 'grv': 'grv',
 'grvs': 'grvs',
 'gtway': 'gtwy',
 'gtwy': 'gtwy',
 'harb': 'hbr',
 'harbor': 'hbr',
 'harbors': 'hbrs',
 'harbr': 'hbr',
 'haven': 'hvn',
 'hbr': 'hbr',
 'hbrs': 'hbrs',
 'heights': 'hts',
 'highway': 'hwy',
 'highwy': 'hwy',
 'hill': 'hl',
 'hills': 'hls',
 'hiway': 'hwy',
 'hiwy': 'hwy',
 'hl': 'hl',
 'hllw': 'holw',
 'hls': 'hls',
 'hollow': 'holw',
 'hollows': 'holw',
 'holw': 'holw',
 'holws': 'holw',
 'hrbor': 'hbr',
 'ht': 'hts',
 'hts': 'hts',
 'hvn': 'hvn',
 'hway': 'hwy',
 'hwy': 'hwy',
 'inlet': 'inlt',
 'inlt': 'inlt',
 'is': 'is',
 'island': 'is',
 'islands': 'iss',
 'isle': 'isle',
 'isles': 'isle',
 'islnd': 'is',
 'islnds': 'iss',
 'iss': 'iss',
 'jct': 'jct',
 'jction': 'jct',
 'jctn': 'jct',
 'jctns': 'jcts',
 'jcts': 'jcts',
 'junction': 'jct',
 'junctions': 'jcts',
 'junctn': 'jct',
 'juncton': 'jct',
 'key': 'ky',
 'keys': 'kys',
 'knl': 'knl',
 'knls': 'knls',
 'knol': 'knl',
 'knoll': 'knl',
 'knolls': 'knls',
 'ky': 'ky',
 'kys': 'kys',
 'lake': 'lk',
 'lakes': 'lks',
 'land': 'land',
 'landing': 'lndg',
 'lane': 'ln',
 'lck': 'lck',
 'lcks': 'lcks',
 'ldg': 'ldg',
 'ldge': 'ldg',
 'lf': 'lf',
 'lgt': 'lgt',
 'lgts': 'lgts',
 'light': 'lgt',
 'lights': 'lgts',
 'lk': 'lk',
 'lks': 'lks',
 'ln': 'ln',
 'lndg': 'lndg',
 'lndng': 'lndg',
 'loaf': 'lf',
 'lock': 'lck',
 'locks': 'lcks',
 'lodg': 'ldg',
 'lodge': 'ldg',
 'loop': 'loop',
 'loops': 'loop',
 'mall': 'mall',
 'manor': 'mnr',
 'manors': 'mnrs',
 'mdw': 'mdw',
 'mdws': 'mdws',
 'meadow': 'mdw',
 'meadows': 'mdws',
 'medows': 'mdws',
 'mews': 'mews',
 'mill': 'ml',
 'mills': 'mls',
 'mission': 'msn',
 'missn': 'msn',
 'ml': 'ml',
 'mls': 'mls',
 'mnr': 'mnr',
 'mnrs': 'mnrs',
 'mnt': 'mt',
 'mntain': 'mtn',
 'mntn': 'mtn',
 'mntns': 'mtns',
 'motorway': 'mtwy',
 'mount': 'mt',
 'mountain': 'mtn',
 'mountains': 'mtns',
 'mountin': 'mtn',
 'msn': 'msn',
 'mssn': 'msn',
 'mt': 'mt',
 'mtin': 'mtn',
 'mtn': 'mtn',
 'mtns': 'mtns',
 'mtwy': 'mtwy',
 'nck': 'nck',
 'neck': 'nck',
 'opas': 'opas',
 'orch': 'orch',
 'orchard': 'orch',
 'orchrd': 'orch',
 'oval': 'oval',
 'overpass': 'opas',
 'ovl': 'oval',
 'park': 'park',
 'parks': 'park',
 'parkway': 'pkwy',
 'parkways': 'pkwy',
 'parkwy': 'pkwy',
 'pass': 'pass',
 'passage': 'psge',
 'path': 'path',
 'paths': 'path',
 'pike': 'pike',
 'pikes': 'pike',
 'pine': 'pne',
 'pines': 'pnes',
 'pkway': 'pkwy',
 'pkwy': 'pkwy',
 'pkwys': 'pkwy',
 'pky': 'pkwy',
 'pl': 'pl',
 'place': 'pl',
 'plain': 'pln',
 'plains': 'plns',
 'plaza': 'plz',
 'pln': 'pln',
 'plns': 'plns',
 'plz': 'plz',
 'plza': 'plz',
 'pne': 'pne',
 'pnes': 'pnes',
 'point': 'pt',
 'points': 'pts',
 'port': 'prt',
 'ports': 'prts',
 'pr': 'pr',
 'prairie': 'pr',
 'prk': 'park',
 'prr': 'pr',
 'prt': 'prt',
 'prts': 'prts',
 'psge': 'psge',
 'pt': 'pt',
 'pts': 'pts',
 'rad': 'radl',
 'radial': 'radl',
 'radiel': 'radl',
 'radl': 'radl',
 'ramp': 'ramp',
 'ranch': 'rnch',
 'ranches': 'rnch',
 'rapid': 'rpd',
 'rapids': 'rpds',
 'rd': 'rd',
 'rdg': 'rdg',
 'rdge': 'rdg',
 'rdgs': 'rdgs',
 'rds': 'rds',
 'rest': 'rst',
 'ridge': 'rdg',
 'ridges': 'rdgs',
 'riv': 'riv',
 'river': 'riv',
 'rivr': 'riv',
 'rnch': 'rnch',
 'rnchs': 'rnch',
 'road': 'rd',
 'roads': 'rds',
 'route': 'rte',
 'row': 'row',
 'rpd': 'rpd',
 'rpds': 'rpds',
 'rst': 'rst',
 'rte': 'rte',
 'rue': 'rue',
 'run': 'run',
 'rvr': 'riv',
 'shl': 'shl',
 'shls': 'shls',
 'shoal': 'shl',
 'shoals': 'shls',
 'shoar': 'shr',
 'shoars': 'shrs',
 'shore': 'shr',
 'shores': 'shrs',
 'shr': 'shr',
 'shrs': 'shrs',
 'skwy': 'skwy',
 'skyway': 'skwy',
 'smt': 'smt',
 'spg': 'spg',
 'spgs': 'spgs',
 'spng': 'spg',
 'spngs': 'spgs',
 'spring': 'spg',
 'springs': 'spgs',
 'sprng': 'spg',
 'sprngs': 'spgs',
 'spur': 'spur',
 'spurs': 'spur',
 'sq': 'sq',
 'sqr': 'sq',
 'sqre': 'sq',
 'sqrs': 'sqs',
 'sqs': 'sqs',
 'squ': 'sq',
 'square': 'sq',
 'squares': 'sqs',
 'st': 'st',
 'sta': 'sta',
 'station': 'sta',
 'statn': 'sta',
 'stn': 'sta',
 'str': 'st',
 'stra': 'stra',
 'strav': 'stra',
 'straven': 'stra',
 'stravenue': 'stra',
 'stravn': 'stra',
 'stream': 'strm',
 'street': 'st',
 'streets': 'sts',
 'streme': 'strm',
 'strm': 'strm',
 'strt': 'st',
 'strvn': 'stra',
 'strvnue': 'stra',
 'sts': 'sts',
 'sumit': 'smt',
 'sumitt': 'smt',
 'summit': 'smt',
 'ter': 'ter',
 'terr': 'ter',
 'terrace': 'ter',
 'throughway': 'trwy',
 'tpke': 'tpke',
 'trace': 'trce',
 'traces': 'trce',
 'track': 'trak',
 'tracks': 'trak',
 'trafficway': 'trfy',
 'trail': 'trl',
 'trailer': 'trlr',
 'trails': 'trl',
 'trak': 'trak',
 'trce': 'trce',
 'trfy': 'trfy',
 'trk': 'trak',
 'trks': 'trak',
 'trl': 'trl',
 'trlr': 'trlr',
 'trlrs': 'trlr',
 'trls': 'trl',
 'trnpk': 'tpke',
 'trwy': 'trwy',
 'tunel': 'tunl',
 'tunl': 'tunl',
 'tunls': 'tunl',
 'tunnel': 'tunl',
 'tunnels': 'tunl',
 'tunnl': 'tunl',
 'turnpike': 'tpke',
 'turnpk': 'tpke',
 'un': 'un',
 'underpass': 'upas',
 'union': 'un',
 'unions': 'uns',
 'uns': 'uns',
 'upas': 'upas',
 'valley': 'vly',
 'valleys': 'vlys',
 'vally': 'vly',
 'vdct': 'via',
 'via': 'via',
 'viadct': 'via',
 'viaduct': 'via',
 'view': 'vw',
 'views': 'vws',
 'vill': 'vlg',
 'villag': 'vlg',
 'village': 'vlg',
 'villages': 'vlgs',
 'ville': 'vl',
 'villg': 'vlg',
 'villiage': 'vlg',
 'vis': 'vis',
 'vist': 'vis',
 'vista': 'vis',
 'vl': 'vl',
 'vlg': 'vlg',
 'vlgs': 'vlgs',
 'vlly': 'vly',
 'vly': 'vly',
 'vlys': 'vlys',
 'vst': 'vis',
 'vsta': 'vis',
 'vw': 'vw',
 'vws': 'vws',
 'walk': 'walk',
 'walks': 'walk',
 'wall': 'wall',
 'way': 'way',
 'ways': 'ways',
 'well': 'wl',
 'wells': 'wls',
 'wl': 'wl',
 'wls': 'wls',
 'wy': 'way',
 'xing': 'xing',
 'xrd': 'xrd',
 'xrds': 'xrds'}

PUB28_DIRECTIONAL_MAP: dict[str, str] = {'e': 'e',
 'east': 'e',
 'este': 'e',
 'n': 'n',
 'ne': 'ne',
 'noreste': 'ne',
 'noroeste': 'nw',
 'norte': 'n',
 'north': 'n',
 'northeast': 'ne',
 'northwest': 'nw',
 'nw': 'nw',
 'oeste': 'w',
 's': 's',
 'se': 'se',
 'south': 's',
 'southeast': 'se',
 'southwest': 'sw',
 'sur': 's',
 'sureste': 'se',
 'suroeste': 'sw',
 'sw': 'sw',
 'w': 'w',
 'west': 'w'}

PUB28_STATE_MAP: dict[str, str] = {'AA': 'AA',
 'AE': 'AE',
 'AK': 'AK',
 'AL': 'AL',
 'ALABAMA': 'AL',
 'ALASKA': 'AK',
 'AMERICANSAMOA': 'AS',
 'AP': 'AP',
 'AR': 'AR',
 'ARIZONA': 'AZ',
 'ARKANSAS': 'AR',
 'ARMEDFORCESAMERICASEXCEPTCANADA': 'AA',
 'ARMEDFORCESEUROPETHEMIDDLEEASTANDCANADA': 'AE',
 'ARMEDFORCESPACIFIC': 'AP',
 'AS': 'AS',
 'AZ': 'AZ',
 'CA': 'CA',
 'CALIFORNIA': 'CA',
 'CO': 'CO',
 'COLORADO': 'CO',
 'CONNECTICUT': 'CT',
 'CT': 'CT',
 'DC': 'DC',
 'DE': 'DE',
 'DELAWARE': 'DE',
 'DISTRICTOFCOLUMBIA': 'DC',
 'FEDERATEDSTATESOFMICRONESIA': 'FM',
 'FL': 'FL',
 'FLORIDA': 'FL',
 'FM': 'FM',
 'GA': 'GA',
 'GEORGIA': 'GA',
 'GU': 'GU',
 'GUAM': 'GU',
 'HAWAII': 'HI',
 'HI': 'HI',
 'IA': 'IA',
 'ID': 'ID',
 'IDAHO': 'ID',
 'IL': 'IL',
 'ILLINOIS': 'IL',
 'IN': 'IN',
 'INDIANA': 'IN',
 'IOWA': 'IA',
 'KANSAS': 'KS',
 'KENTUCKY': 'KY',
 'KS': 'KS',
 'KY': 'KY',
 'LA': 'LA',
 'LOUISIANA': 'LA',
 'MA': 'MA',
 'MAINE': 'ME',
 'MARSHALLISLANDS': 'MH',
 'MARYLAND': 'MD',
 'MASSACHUSETTS': 'MA',
 'MD': 'MD',
 'ME': 'ME',
 'MH': 'MH',
 'MI': 'MI',
 'MICHIGAN': 'MI',
 'MINNESOTA': 'MN',
 'MISSISSIPPI': 'MS',
 'MISSOURI': 'MO',
 'MN': 'MN',
 'MO': 'MO',
 'MONTANA': 'MT',
 'MP': 'MP',
 'MS': 'MS',
 'MT': 'MT',
 'NC': 'NC',
 'ND': 'ND',
 'NE': 'NE',
 'NEBRASKA': 'NE',
 'NEVADA': 'NV',
 'NEWHAMPSHIRE': 'NH',
 'NEWJERSEY': 'NJ',
 'NEWMEXICO': 'NM',
 'NEWYORK': 'NY',
 'NH': 'NH',
 'NJ': 'NJ',
 'NM': 'NM',
 'NORTHCAROLINA': 'NC',
 'NORTHDAKOTA': 'ND',
 'NORTHERNMARIANAISLANDS': 'MP',
 'NV': 'NV',
 'NY': 'NY',
 'OH': 'OH',
 'OHIO': 'OH',
 'OK': 'OK',
 'OKLAHOMA': 'OK',
 'OR': 'OR',
 'OREGON': 'OR',
 'PA': 'PA',
 'PALAU': 'PW',
 'PENNSYLVANIA': 'PA',
 'PR': 'PR',
 'PUERTORICO': 'PR',
 'PW': 'PW',
 'RHODEISLAND': 'RI',
 'RI': 'RI',
 'SC': 'SC',
 'SD': 'SD',
 'SOUTHCAROLINA': 'SC',
 'SOUTHDAKOTA': 'SD',
 'TENNESSEE': 'TN',
 'TEXAS': 'TX',
 'TN': 'TN',
 'TX': 'TX',
 'UT': 'UT',
 'UTAH': 'UT',
 'VA': 'VA',
 'VERMONT': 'VT',
 'VI': 'VI',
 'VIRGINIA': 'VA',
 'VIRGINISLANDS': 'VI',
 'VT': 'VT',
 'WA': 'WA',
 'WASHINGTON': 'WA',
 'WESTVIRGINIA': 'WV',
 'WI': 'WI',
 'WISCONSIN': 'WI',
 'WV': 'WV',
 'WY': 'WY',
 'WYOMING': 'WY'}

PUB28_UNIT_DESIGNATOR_MAP: dict[str, str] = {'#': 'ste',
 'apartment': 'apt',
 'apt': 'apt',
 'basement': 'bsmt',
 'bldg': 'bldg',
 'bsmt': 'bsmt',
 'building': 'bldg',
 'department': 'dept',
 'dept': 'dept',
 'fl': 'fl',
 'floor': 'fl',
 'frnt': 'frnt',
 'front': 'frnt',
 'hanger': 'hngr',
 'hngr': 'hngr',
 'key': 'key',
 'lbby': 'lbby',
 'lobby': 'lbby',
 'lot': 'lot',
 'lower': 'lowr',
 'lowr': 'lowr',
 'ofc': 'ofc',
 'office': 'ofc',
 'penthouse': 'ph',
 'ph': 'ph',
 'pier': 'pier',
 'rear': 'rear',
 'rm': 'rm',
 'room': 'rm',
 'side': 'side',
 'slip': 'slip',
 'space': 'spc',
 'spc': 'spc',
 'ste': 'ste',
 'stop': 'stop',
 'suite': 'ste',
 'trailer': 'trlr',
 'trlr': 'trlr',
 'unit': 'unit',
 'upper': 'uppr',
 'uppr': 'uppr'}

PUB28_UNIT_NO_RANGE: set[str] = {'rear', 'side', 'uppr', 'lowr', 'ph', 'ofc', 'bsmt', 'lbby', 'frnt'}

PUB28_INVALID_UNIT_VALUES: set[str] = {'allee',
 'alley',
 'ally',
 'aly',
 'anex',
 'annex',
 'annx',
 'anx',
 'arc',
 'arcade',
 'av',
 'ave',
 'aven',
 'avenu',
 'avenue',
 'avn',
 'avnue',
 'bayoo',
 'bayou',
 'bch',
 'beach',
 'bend',
 'bg',
 'bgs',
 'blf',
 'blfs',
 'bluf',
 'bluff',
 'bluffs',
 'blvd',
 'bnd',
 'bot',
 'bottm',
 'bottom',
 'boul',
 'boulevard',
 'boulv',
 'br',
 'branch',
 'brdge',
 'brg',
 'bridge',
 'brk',
 'brks',
 'brnch',
 'brook',
 'brooks',
 'btm',
 'burg',
 'burgs',
 'byp',
 'bypa',
 'bypas',
 'bypass',
 'byps',
 'byu',
 'camp',
 'canyn',
 'canyon',
 'cape',
 'causeway',
 'causwa',
 'cen',
 'cent',
 'center',
 'centers',
 'centr',
 'centre',
 'cir',
 'circ',
 'circl',
 'circle',
 'circles',
 'cirs',
 'clb',
 'clf',
 'clfs',
 'cliff',
 'cliffs',
 'club',
 'cmn',
 'cmns',
 'cmp',
 'cnter',
 'cntr',
 'cnyn',
 'common',
 'commons',
 'cor',
 'corner',
 'corners',
 'cors',
 'course',
 'court',
 'courts',
 'cove',
 'coves',
 'cp',
 'cpe',
 'crcl',
 'crcle',
 'creek',
 'cres',
 'crescent',
 'crest',
 'crk',
 'crossing',
 'crossroad',
 'crossroads',
 'crse',
 'crsent',
 'crsnt',
 'crssng',
 'crst',
 'cswy',
 'ct',
 'ctr',
 'ctrs',
 'cts',
 'curv',
 'curve',
 'cv',
 'cvs',
 'cyn',
 'dale',
 'dam',
 'div',
 'divide',
 'dl',
 'dm',
 'dr',
 'driv',
 'drive',
 'drives',
 'drs',
 'drv',
 'dv',
 'dvd',
 'e',
 'east',
 'est',
 'estate',
 'estates',
 'este',
 'ests',
 'exp',
 'expr',
 'express',
 'expressway',
 'expw',
 'expy',
 'ext',
 'extension',
 'extensions',
 'extn',
 'extnsn',
 'exts',
 'fall',
 'falls',
 'ferry',
 'field',
 'fields',
 'flat',
 'flats',
 'fld',
 'flds',
 'fls',
 'flt',
 'flts',
 'ford',
 'fords',
 'forest',
 'forests',
 'forg',
 'forge',
 'forges',
 'fork',
 'forks',
 'fort',
 'frd',
 'frds',
 'freeway',
 'freewy',
 'frg',
 'frgs',
 'frk',
 'frks',
 'frry',
 'frst',
 'frt',
 'frway',
 'frwy',
 'fry',
 'ft',
 'fwy',
 'garden',
 'gardens',
 'gardn',
 'gateway',
 'gatewy',
 'gatway',
 'gdn',
 'gdns',
 'glen',
 'glens',
 'gln',
 'glns',
 'grden',
 'grdn',
 'grdns',
 'green',
 'greens',
 'grn',
 'grns',
 'grov',
 'grove',
 'groves',
 'grv',
 'grvs',
 'gtway',
 'gtwy',
 'harb',
 'harbor',
 'harbors',
 'harbr',
 'haven',
 'hbr',
 'hbrs',
 'heights',
 'highway',
 'highwy',
 'hill',
 'hills',
 'hiway',
 'hiwy',
 'hl',
 'hllw',
 'hls',
 'hollow',
 'hollows',
 'holw',
 'holws',
 'hrbor',
 'ht',
 'hts',
 'hvn',
 'hway',
 'hwy',
 'inlet',
 'inlt',
 'is',
 'island',
 'islands',
 'isle',
 'isles',
 'islnd',
 'islnds',
 'iss',
 'jct',
 'jction',
 'jctn',
 'jctns',
 'jcts',
 'junction',
 'junctions',
 'junctn',
 'juncton',
 'key',
 'keys',
 'knl',
 'knls',
 'knol',
 'knoll',
 'knolls',
 'ky',
 'kys',
 'lake',
 'lakes',
 'land',
 'landing',
 'lane',
 'lck',
 'lcks',
 'ldg',
 'ldge',
 'lf',
 'lgt',
 'lgts',
 'light',
 'lights',
 'lk',
 'lks',
 'ln',
 'lndg',
 'lndng',
 'loaf',
 'lock',
 'locks',
 'lodg',
 'lodge',
 'loop',
 'loops',
 'mall',
 'manor',
 'manors',
 'mdw',
 'mdws',
 'meadow',
 'meadows',
 'medows',
 'mews',
 'mill',
 'mills',
 'mission',
 'missn',
 'ml',
 'mls',
 'mnr',
 'mnrs',
 'mnt',
 'mntain',
 'mntn',
 'mntns',
 'motorway',
 'mount',
 'mountain',
 'mountains',
 'mountin',
 'msn',
 'mssn',
 'mt',
 'mtin',
 'mtn',
 'mtns',
 'mtwy',
 'n',
 'nck',
 'ne',
 'neck',
 'noreste',
 'noroeste',
 'norte',
 'north',
 'northeast',
 'northwest',
 'nw',
 'oeste',
 'opas',
 'orch',
 'orchard',
 'orchrd',
 'oval',
 'overpass',
 'ovl',
 'park',
 'parks',
 'parkway',
 'parkways',
 'parkwy',
 'pass',
 'passage',
 'path',
 'paths',
 'pike',
 'pikes',
 'pine',
 'pines',
 'pkway',
 'pkwy',
 'pkwys',
 'pky',
 'pl',
 'place',
 'plain',
 'plains',
 'plaza',
 'pln',
 'plns',
 'plz',
 'plza',
 'pne',
 'pnes',
 'point',
 'points',
 'port',
 'ports',
 'pr',
 'prairie',
 'prk',
 'prr',
 'prt',
 'prts',
 'psge',
 'pt',
 'pts',
 'rad',
 'radial',
 'radiel',
 'radl',
 'ramp',
 'ranch',
 'ranches',
 'rapid',
 'rapids',
 'rd',
 'rdg',
 'rdge',
 'rdgs',
 'rds',
 'rest',
 'ridge',
 'ridges',
 'riv',
 'river',
 'rivr',
 'rnch',
 'rnchs',
 'road',
 'roads',
 'route',
 'row',
 'rpd',
 'rpds',
 'rst',
 'rte',
 'rue',
 'run',
 'rvr',
 's',
 'se',
 'shl',
 'shls',
 'shoal',
 'shoals',
 'shoar',
 'shoars',
 'shore',
 'shores',
 'shr',
 'shrs',
 'skwy',
 'skyway',
 'smt',
 'south',
 'southeast',
 'southwest',
 'spg',
 'spgs',
 'spng',
 'spngs',
 'spring',
 'springs',
 'sprng',
 'sprngs',
 'spur',
 'spurs',
 'sq',
 'sqr',
 'sqre',
 'sqrs',
 'sqs',
 'squ',
 'square',
 'squares',
 'st',
 'sta',
 'station',
 'statn',
 'stn',
 'str',
 'stra',
 'strav',
 'straven',
 'stravenue',
 'stravn',
 'stream',
 'street',
 'streets',
 'streme',
 'strm',
 'strt',
 'strvn',
 'strvnue',
 'sts',
 'sumit',
 'sumitt',
 'summit',
 'sur',
 'sureste',
 'suroeste',
 'sw',
 'ter',
 'terr',
 'terrace',
 'throughway',
 'tpke',
 'trace',
 'traces',
 'track',
 'tracks',
 'trafficway',
 'trail',
 'trailer',
 'trails',
 'trak',
 'trce',
 'trfy',
 'trk',
 'trks',
 'trl',
 'trlr',
 'trlrs',
 'trls',
 'trnpk',
 'trwy',
 'tunel',
 'tunl',
 'tunls',
 'tunnel',
 'tunnels',
 'tunnl',
 'turnpike',
 'turnpk',
 'un',
 'underpass',
 'union',
 'unions',
 'uns',
 'upas',
 'valley',
 'valleys',
 'vally',
 'vdct',
 'via',
 'viadct',
 'viaduct',
 'view',
 'views',
 'vill',
 'villag',
 'village',
 'villages',
 'ville',
 'villg',
 'villiage',
 'vis',
 'vist',
 'vista',
 'vl',
 'vlg',
 'vlgs',
 'vlly',
 'vly',
 'vlys',
 'vst',
 'vsta',
 'vw',
 'vws',
 'w',
 'walk',
 'walks',
 'wall',
 'way',
 'ways',
 'well',
 'wells',
 'west',
 'wl',
 'wls',
 'wy',
 'xing',
 'xrd',
 'xrds'}
