# Licensed under the HealthPorta Non-Commercial License (see LICENSE).
"""Configuration constants and environment helpers for PTG imports."""

from __future__ import annotations

import os

TEST_TOC_FILES = 2
TEST_TOC_JOBS = 2
TEST_PROVIDER_GROUPS = 50
TEST_IN_NETWORK_ITEMS = 25
TEST_NEGOTIATED_PRICES = 250
TEST_ALLOWED_ITEMS = 25

PTG2_KEEP_PARTIAL_ENV = "HLTHPRT_PTG2_KEEP_PARTIAL_ARTIFACTS"
PTG2_DEFER_LOGICAL_HASH_BYTES_ENV = "HLTHPRT_PTG2_DEFER_LOGICAL_HASH_BYTES"
PTG2_PROVIDER_REF_BATCH_ROWS_ENV = "HLTHPRT_PTG2_PROVIDER_REF_BATCH_ROWS"
PTG2_ITEM_BATCH_ROWS_ENV = "HLTHPRT_PTG2_ITEM_BATCH_ROWS"
PTG2_BILLING_BATCH_ROWS_ENV = "HLTHPRT_PTG2_BILLING_BATCH_ROWS"
PTG2_RATE_BATCH_ROWS_ENV = "HLTHPRT_PTG2_RATE_BATCH_ROWS"
PTG2_PRICE_BATCH_ROWS_ENV = "HLTHPRT_PTG2_PRICE_BATCH_ROWS"
PTG2_PROGRESS_INTERVAL_SECONDS_ENV = "HLTHPRT_PTG2_PROGRESS_INTERVAL_SECONDS"
PTG2_DOWNLOAD_PROGRESS_BYTES_ENV = "HLTHPRT_PTG2_DOWNLOAD_PROGRESS_BYTES"
PTG2_DOWNLOAD_TASKS_ENV = "HLTHPRT_PTG2_DOWNLOAD_TASKS"
PTG2_RANGE_DOWNLOADS_ENV = "HLTHPRT_PTG2_RANGE_DOWNLOADS"
PTG2_RANGE_DOWNLOAD_TASKS_ENV = "HLTHPRT_PTG2_RANGE_DOWNLOAD_TASKS"
PTG2_RANGE_DOWNLOAD_CHUNK_BYTES_ENV = "HLTHPRT_PTG2_RANGE_DOWNLOAD_CHUNK_BYTES"
PTG2_RANGE_DOWNLOAD_MIN_BYTES_ENV = "HLTHPRT_PTG2_RANGE_DOWNLOAD_MIN_BYTES"
PTG2_DOWNLOAD_RETRIES_ENV = "HLTHPRT_PTG2_DOWNLOAD_RETRIES"
PTG2_DOWNLOAD_RETRY_DELAY_SECONDS_ENV = "HLTHPRT_PTG2_DOWNLOAD_RETRY_DELAY_SECONDS"
PTG2_COMPACT_IMPORT_ENV = "HLTHPRT_PTG2_COMPACT_IMPORT"
PTG2_COMPACT_BATCH_ROWS_ENV = "HLTHPRT_PTG2_COMPACT_BATCH_ROWS"
PTG2_PROVIDER_SET_INLINE_NPI_LIMIT_ENV = "HLTHPRT_PTG2_PROVIDER_SET_INLINE_NPI_LIMIT"
PTG2_PROVIDER_BUCKET_COUNT_ENV = "HLTHPRT_PTG2_PROVIDER_BUCKET_COUNT"
PTG2_PROVIDER_CACHE_MEMORY_REFS_ENV = "HLTHPRT_PTG2_PROVIDER_CACHE_MEMORY_REFS"
PTG2_RATE_GROUP_FLUSH_ITEMS_ENV = "HLTHPRT_PTG2_RATE_GROUP_FLUSH_ITEMS"
PTG2_PROVIDER_COMBO_CACHE_REFS_ENV = "HLTHPRT_PTG2_PROVIDER_COMBO_CACHE_REFS"
PTG2_SERVING_ROW_LIMIT_ENV = "HLTHPRT_PTG2_SERVING_ROW_LIMIT"
PTG2_COPY_UPSERT_ROWS_ENV = "HLTHPRT_PTG2_COPY_UPSERT_ROWS"
PTG2_DIRECT_COPY_SERVING_RATE_ENV = "HLTHPRT_PTG2_DIRECT_COPY_SERVING_RATE"
PTG2_STREAMING_DEDUPE_ENV = "HLTHPRT_PTG2_STREAMING_DEDUPE"
PTG2_STAGE_PRICE_SETS_ENV = "HLTHPRT_PTG2_STAGE_PRICE_SETS"
PTG2_SKIP_EXISTING_PRICE_SETS_ENV = "HLTHPRT_PTG2_SKIP_EXISTING_PRICE_SETS"
PTG2_KEEP_PRICE_SET_STAGE_ENV = "HLTHPRT_PTG2_KEEP_PRICE_SET_STAGE"
PTG2_STAGE_SERVING_RATES_ENV = "HLTHPRT_PTG2_STAGE_SERVING_RATES"
PTG2_KEEP_SERVING_RATE_STAGE_ENV = "HLTHPRT_PTG2_KEEP_SERVING_RATE_STAGE"
PTG2_STAGE_SERVING_AS_FINAL_ENV = "HLTHPRT_PTG2_STAGE_SERVING_AS_FINAL"
PTG2_COMPACT_SERVING_TABLE_ENV = "HLTHPRT_PTG2_COMPACT_SERVING_TABLE"
PTG2_COMPACT_BULK_DROP_INDEXES_ENV = "HLTHPRT_PTG2_COMPACT_BULK_DROP_INDEXES"
PTG2_SKIP_BULK_INDEX_ENSURE_ENV = "HLTHPRT_PTG2_SKIP_BULK_INDEX_ENSURE"
PTG2_SKIP_COMPACT_FINALIZE_ENV = "HLTHPRT_PTG2_SKIP_COMPACT_FINALIZE"
PTG2_SKIP_COMPACT_SERVING_INDEX_ENSURE_ENV = "HLTHPRT_PTG2_SKIP_COMPACT_SERVING_INDEX_ENSURE"
PTG2_COMPACT_SERVING_INDEX_MODE_ENV = "HLTHPRT_PTG2_COMPACT_SERVING_INDEX_MODE"
PTG2_COMPACT_DICTIONARY_INDEX_MODE_ENV = "HLTHPRT_PTG2_COMPACT_DICTIONARY_INDEX_MODE"
PTG2_INDEX_TASKS_ENV = "HLTHPRT_PTG2_INDEX_TASKS"
PTG2_FAST_FINAL_REBUILD_ENV = "HLTHPRT_PTG2_FAST_FINAL_REBUILD"
PTG2_DEFER_PROVIDER_LOCATIONS_ENV = "HLTHPRT_PTG2_DEFER_PROVIDER_LOCATIONS"
PTG2_STAGE_INDEXES_ENV = "HLTHPRT_PTG2_STAGE_INDEXES"
PTG2_UNLOGGED_STAGE_ENV = "HLTHPRT_PTG2_UNLOGGED_STAGE"
PTG2_UNLOGGED_FINAL_ENV = "HLTHPRT_PTG2_UNLOGGED_FINAL"
PTG2_BINARY_IDS_ENV = "HLTHPRT_PTG2_BINARY_IDS"
PTG2_MANIFEST_PRECOPY_MERGE_ENV = "HLTHPRT_PTG2_MANIFEST_PRECOPY_MERGE"
PTG2_MANIFEST_STREAM_MERGE_COPY_ENV = "HLTHPRT_PTG2_MANIFEST_STREAM_MERGE_COPY"
PTG2_MANIFEST_DIRECT_COPY_FILES_ENV = "HLTHPRT_PTG2_MANIFEST_DIRECT_COPY_FILES"
PTG2_MANIFEST_DIRECT_COPY_TASKS_ENV = "HLTHPRT_PTG2_MANIFEST_DIRECT_COPY_TASKS"
PTG2_FILE_PROCESS_CONCURRENCY_ENV = "HLTHPRT_PTG2_FILE_PROCESS_CONCURRENCY"
PTG2_MANIFEST_PROVIDER_NPI_SIDECAR_ENABLED_ENV = "HLTHPRT_PTG2_MANIFEST_PROVIDER_NPI_SIDECAR_ENABLED"
PTG2_MANIFEST_PUBLISH_DB_DEDUPE_FALLBACK_ENV = "HLTHPRT_PTG2_PUBLISH_DB_DEDUPE_FALLBACK"
PTG2_DEDUPE_SERVING_STAGE_MERGE_ENV = "HLTHPRT_PTG2_DEDUPE_SERVING_STAGE_MERGE"
PTG2_PROVIDER_CACHE_BACKEND_ENV = "HLTHPRT_PTG2_PROVIDER_CACHE_BACKEND"
PTG2_STREAM_BUFFER_BYTES_ENV = "HLTHPRT_PTG2_STREAM_BUFFER_BYTES"
PTG2_ASYNC_WRITE_TASKS_ENV = "HLTHPRT_PTG2_ASYNC_WRITE_TASKS"
PTG2_FAST_PROVIDER_UNION_ENV = "HLTHPRT_PTG2_FAST_PROVIDER_UNION"
PTG2_FAST_PROVIDER_AGGREGATION_ENV = "HLTHPRT_PTG2_FAST_PROVIDER_AGGREGATION"
PTG2_EXPECTED_IN_NETWORK_ITEMS_ENV = "HLTHPRT_PTG2_EXPECTED_IN_NETWORK_ITEMS"
PTG2_FAST_OBJECT_ITERATOR_ENV = "HLTHPRT_PTG2_FAST_OBJECT_ITERATOR"
PTG2_JSON_DECODER_ITERATOR_ENV = "HLTHPRT_PTG2_JSON_DECODER_ITERATOR"
PTG2_FAST_JSON_LOADS_ENV = "HLTHPRT_PTG2_FAST_JSON_LOADS"
PTG2_ISAL_GZIP_ENV = "HLTHPRT_PTG2_ISAL_GZIP"
PTG2_SERVING_ONLY_IMPORT_ENV = "HLTHPRT_PTG2_SERVING_ONLY_IMPORT"
PTG2_SERVING_WORKERS_ENV = "HLTHPRT_PTG2_SERVING_WORKERS"
PTG2_SLIM_SERVING_ROWS_ENV = "HLTHPRT_PTG2_SLIM_SERVING_ROWS"
PTG2_RAW_WORKER_OBJECTS_ENV = "HLTHPRT_PTG2_RAW_WORKER_OBJECTS"
PTG2_WORKER_CHUNK_ITEMS_ENV = "HLTHPRT_PTG2_WORKER_CHUNK_ITEMS"
PTG2_WORKER_CHUNK_BYTES_ENV = "HLTHPRT_PTG2_WORKER_CHUNK_BYTES"
PTG2_WORKER_MAX_PENDING_BATCHES_ENV = "HLTHPRT_PTG2_WORKER_MAX_PENDING_BATCHES"
PTG2_WORKER_MAX_PENDING_BYTES_ENV = "HLTHPRT_PTG2_WORKER_MAX_PENDING_BYTES"
PTG2_WORKER_RESULT_FILES_ENV = "HLTHPRT_PTG2_WORKER_RESULT_FILES"
PTG2_RUST_SCANNER_ENV = "HLTHPRT_PTG2_RUST_SCANNER"
PTG2_RUST_SCANNER_BIN_ENV = "HLTHPRT_PTG2_RUST_SCANNER_BIN"
PTG2_RUST_REQUIRE_RELEASE_ENV = "HLTHPRT_PTG2_RUST_REQUIRE_RELEASE"
PTG2_RUST_COMPACT_SERVING_ENV = "HLTHPRT_PTG2_RUST_COMPACT_SERVING"
PTG2_HASH_MODE_ENV = "HLTHPRT_PTG2_HASH_MODE"
PTG2_COMPACT_COPY_TASKS_ENV = "HLTHPRT_PTG2_COMPACT_COPY_TASKS"
PTG2_COMPACT_COPY_KIND_TASKS_ENV = "HLTHPRT_PTG2_COMPACT_COPY_KIND_TASKS"
PTG2_COMPACT_SERVING_COPY_TASKS_ENV = "HLTHPRT_PTG2_COMPACT_SERVING_COPY_TASKS"
PTG2_STAGE_COPY_DEDUPE_ENV = "HLTHPRT_PTG2_STAGE_COPY_DEDUPE"
PTG2_RUST_WORKERS_ENV = "HLTHPRT_PTG2_RUST_WORKERS"
PTG2_RUST_WORK_QUEUE_ENV = "HLTHPRT_PTG2_RUST_WORK_QUEUE"
PTG2_RUST_SPLIT_NEGOTIATED_RATES_ENV = "HLTHPRT_PTG2_RUST_SPLIT_NEGOTIATED_RATES"
PTG2_RUST_PARSE_IN_WORKERS_ENV = "HLTHPRT_PTG2_RUST_PARSE_IN_WORKERS"
PTG2_RUST_TOP_LEVEL_BYTE_SCAN_ENV = "HLTHPRT_PTG2_RUST_TOP_LEVEL_BYTE_SCAN"
PTG2_RUST_EVENT_QUEUE_ENV = "HLTHPRT_PTG2_RUST_EVENT_QUEUE"
PTG2_RUST_PROVIDER_REFS_IN_WORKERS_ENV = "HLTHPRT_PTG2_RUST_PROVIDER_REFS_IN_WORKERS"
PTG2_RUST_PROVIDER_REF_WORKERS_ENV = "HLTHPRT_PTG2_RUST_PROVIDER_REF_WORKERS"
PTG2_RUST_PROVIDER_REF_QUEUE_ENV = "HLTHPRT_PTG2_RUST_PROVIDER_REF_QUEUE"
PTG2_RUST_PROVIDER_REF_CHUNK_ITEMS_ENV = "HLTHPRT_PTG2_RUST_PROVIDER_REF_CHUNK_ITEMS"
PTG2_RUST_RAW_CHUNK_BYTES_ENV = "HLTHPRT_PTG2_RUST_RAW_CHUNK_BYTES"
PTG2_RUST_PROVIDER_REF_RAW_CHUNK_BYTES_ENV = "HLTHPRT_PTG2_RUST_PROVIDER_REF_RAW_CHUNK_BYTES"
PTG2_MANIFEST_MERGE_CHUNK_BYTES_ENV = "HLTHPRT_PTG2_MANIFEST_MERGE_CHUNK_BYTES"
PTG2_MANIFEST_MERGE_SORT_WORKERS_ENV = "HLTHPRT_PTG2_MANIFEST_MERGE_SORT_WORKERS"
PTG2_SNAPSHOT_ARCH_ENV = "HLTHPRT_PTG2_SNAPSHOT_ARCH"
PTG2_SNAPSHOT_ARCH_VARIANT_ENV = "HLTHPRT_PTG2_SNAPSHOT_ARCH_VARIANT"

PTG2_SNAPSHOT_ARCH_MATERIALIZED_V1 = "materialized_v1"
PTG2_SNAPSHOT_ARCH_SIDECAR_SCOPE_V1 = "sidecar_scope_v1"
PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1 = "postgres_binary_v1"
PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V2 = "postgres_binary_v2"
PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V3 = "postgres_binary_v3"
PTG2_SNAPSHOT_ARCH_LEGACY_MIXED_V1 = "legacy_mixed_v1"
PTG2_POSTGRES_BINARY_SNAPSHOT_ARCHES = frozenset(
    {
        PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1,
        PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V2,
        PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V3,
    }
)
PTG2_POSTGRES_BINARY_PROVIDER_MEMBERSHIP_ARCHES = frozenset(
    {
        PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V2,
        PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V3,
    }
)
PTG2_PROVIDER_SCOPE_STRATEGY_MATERIALIZED_RATE_SCOPE = "materialized_rate_scope"
PTG2_PROVIDER_SCOPE_STRATEGY_COMPONENT_TABLE = "component_table"
PTG2_PROVIDER_SCOPE_STRATEGY_SIDECAR = "sidecar_provider_scope"

PTG2_DEFAULT_COMPACT_COPY_TASKS = 4
PTG2_DEFAULT_COMPACT_COPY_KIND_TASKS = 1
PTG2_DEFAULT_COMPACT_SERVING_COPY_TASKS = 1
PTG2_DEFAULT_RUST_WORKERS = 8
PTG2_DEFAULT_RUST_WORK_QUEUE = 16
PTG2_DEFAULT_RUST_EVENT_QUEUE = 32
PTG2_DEFAULT_RUST_SPLIT_NEGOTIATED_RATES = 8192
PTG2_DEFAULT_DOWNLOAD_TASKS = 4
PTG2_DEFAULT_RANGE_DOWNLOAD_TASKS = 4
PTG2_DEFAULT_RANGE_DOWNLOAD_CHUNK_BYTES = 128 * 1024 * 1024
PTG2_DEFAULT_RANGE_DOWNLOAD_MIN_BYTES = 512 * 1024 * 1024
PTG2_DEFAULT_INDEX_TASKS = 4

PTG2_STAGE_COPY_DEDUPE_DEFAULT_KINDS = frozenset(
    {
        "procedure",
        "price_code_set",
        "price_atom",
        "price_set_entry",
        "provider_set",
        "provider_set_component",
        "provider_group_member",
        "provider_set_entry",
    }
)


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(str(raw).strip())
    except ValueError:
        return default


def _ptg2_snapshot_arch_from_env() -> str | None:
    raw = os.getenv(PTG2_SNAPSHOT_ARCH_ENV)
    if raw is None or not str(raw).strip():
        return PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V2
    normalized = str(raw).strip().lower().replace("-", "_")
    arch_alias_map = {
        "materialized": PTG2_SNAPSHOT_ARCH_MATERIALIZED_V1,
        "materialized_v1": PTG2_SNAPSHOT_ARCH_MATERIALIZED_V1,
        "legacy": PTG2_SNAPSHOT_ARCH_MATERIALIZED_V1,
        "legacy_materialized": PTG2_SNAPSHOT_ARCH_MATERIALIZED_V1,
        "legacy_materialized_v1": PTG2_SNAPSHOT_ARCH_MATERIALIZED_V1,
        "sidecar": PTG2_SNAPSHOT_ARCH_SIDECAR_SCOPE_V1,
        "sidecar_only": PTG2_SNAPSHOT_ARCH_SIDECAR_SCOPE_V1,
        "sidecar_scope": PTG2_SNAPSHOT_ARCH_SIDECAR_SCOPE_V1,
        "sidecar_scope_v1": PTG2_SNAPSHOT_ARCH_SIDECAR_SCOPE_V1,
        "postgres_binary": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1,
        "postgres_binary_v1": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1,
        "postgres_binary_v2": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V2,
        "postgres_binary_v3": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V3,
        "db_binary": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1,
        "db_binary_v1": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1,
        "db_binary_v2": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V2,
        "db_binary_v3": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V3,
        "binary": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1,
        "binary_v1": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1,
        "binary_v2": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V2,
        "binary_v3": PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V3,
    }
    if normalized not in arch_alias_map:
        raise ValueError(
            f"Unsupported {PTG2_SNAPSHOT_ARCH_ENV}={raw!r}; "
            f"expected {PTG2_SNAPSHOT_ARCH_MATERIALIZED_V1!r}, "
            f"{PTG2_SNAPSHOT_ARCH_SIDECAR_SCOPE_V1!r}, "
            f"{PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V1!r}, "
            f"{PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V2!r}, "
            f"or {PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V3!r}"
        )
    return arch_alias_map[normalized]


def _is_postgres_binary_snapshot_arch(arch_version: str | None) -> bool:
    return arch_version in PTG2_POSTGRES_BINARY_SNAPSHOT_ARCHES


def _is_postgres_binary_v3_arch(arch_version: str | None) -> bool:
    return arch_version == PTG2_SNAPSHOT_ARCH_POSTGRES_BINARY_V3


_is_postgres_binary_v3_snapshot_arch = _is_postgres_binary_v3_arch


def _uses_postgres_binary_provider_membership_graph(arch_version: str | None) -> bool:
    return arch_version in PTG2_POSTGRES_BINARY_PROVIDER_MEMBERSHIP_ARCHES


def _ptg2_snapshot_arch_variant(arch_version: str | None = None) -> str | None:
    raw = os.getenv(PTG2_SNAPSHOT_ARCH_VARIANT_ENV)
    if raw is None and os.getenv(PTG2_SNAPSHOT_ARCH_ENV) is not None:
        raw = arch_version or _ptg2_snapshot_arch_from_env()
    if raw is None or not str(raw).strip():
        return None
    normalized = "".join(ch if ch.isalnum() else "_" for ch in str(raw).strip().lower()).strip("_")
    return normalized or None


def _ptg2_stage_copy_dedupe_enabled(kind: str) -> bool:
    if kind in PTG2_STAGE_COPY_DEDUPE_DEFAULT_KINDS:
        return True
    return _env_bool(PTG2_STAGE_COPY_DEDUPE_ENV, False)


def _use_serving_only_import() -> bool:
    return _env_bool(PTG2_SERVING_ONLY_IMPORT_ENV, True)


def _use_stage_serving_as_final() -> bool:
    return _env_bool(
        PTG2_STAGE_SERVING_AS_FINAL_ENV,
        _use_serving_only_import(),
    )


def _use_compact_serving_table() -> bool:
    return _env_bool(
        PTG2_COMPACT_SERVING_TABLE_ENV,
        _use_serving_only_import(),
    )


def _use_rust_compact_serving() -> bool:
    return _env_bool(
        PTG2_RUST_COMPACT_SERVING_ENV,
        _env_bool(PTG2_RUST_SCANNER_ENV, True),
    )


def _stream_buffer_bytes() -> int:
    return max(_env_int(PTG2_STREAM_BUFFER_BYTES_ENV, 4 * 1024 * 1024), 64 * 1024)


def _download_progress_interval_bytes() -> int:
    return max(_env_int(PTG2_DOWNLOAD_PROGRESS_BYTES_ENV, 64 * 1024 * 1024), 1024 * 1024)


def _range_download_chunk_bytes() -> int:
    return max(
        _env_int(PTG2_RANGE_DOWNLOAD_CHUNK_BYTES_ENV, PTG2_DEFAULT_RANGE_DOWNLOAD_CHUNK_BYTES),
        1024 * 1024,
    )


def _range_download_tasks() -> int:
    return max(_env_int(PTG2_RANGE_DOWNLOAD_TASKS_ENV, PTG2_DEFAULT_RANGE_DOWNLOAD_TASKS), 1)


def _range_download_min_bytes() -> int:
    return max(
        _env_int(PTG2_RANGE_DOWNLOAD_MIN_BYTES_ENV, PTG2_DEFAULT_RANGE_DOWNLOAD_MIN_BYTES),
        1,
    )


def _download_retry_count() -> int:
    return max(_env_int(PTG2_DOWNLOAD_RETRIES_ENV, 4), 0)


def _download_retry_delay_seconds() -> float:
    raw = os.getenv(PTG2_DOWNLOAD_RETRY_DELAY_SECONDS_ENV)
    if raw is None:
        return 2.0
    try:
        return max(float(str(raw).strip()), 0.0)
    except ValueError:
        return 2.0
