#!/usr/bin/env python3
"""Validate or regenerate public Python locks without CI infrastructure."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import subprocess
import tempfile


LOCK_INPUTS = {
    "requirements-runtime.lock": ("requirements.txt", "requirements-runtime.in"),
    "requirements-build.lock": ("requirements-build.txt",),
}
ROOT = Path(__file__).resolve().parents[1]


def input_header(root: Path, input_name: str) -> str:
    """Record the exact requirement input used to generate a lock."""
    digest = hashlib.sha256((root / input_name).read_bytes()).hexdigest()
    return f"# Input: {input_name} ({digest})"


def validate(root: Path) -> None:
    """Reject a stale lock before uv can install its hashed artifacts."""
    for lock_name, input_names in LOCK_INPUTS.items():
        recorded = re.findall(r"^# Input: .+$", (root / lock_name).read_text(), re.M)
        if recorded != [input_header(root, name) for name in input_names]:
            raise ValueError(f"{lock_name} is stale; run uv run scripts/python_locks.py compile")


def compile_locks(root: Path) -> None:
    """Use uv's universal resolver and publish each lock after its input is stable."""
    resolver = subprocess.check_output(["uv", "--version"], text=True).strip()
    for lock_name, input_names in LOCK_INPUTS.items():
        header = "\n".join(input_header(root, name) for name in input_names)
        with tempfile.TemporaryDirectory(dir=root) as directory:
            candidate = Path(directory) / lock_name
            current = root / lock_name
            if current.exists():
                candidate.write_bytes(current.read_bytes())
            subprocess.run([
                "uv", "pip", "compile", str(root / input_names[-1]),
                "--python-version", "3.14.7", "--universal", "--generate-hashes",
                "--only-binary", ":all:", "--emit-build-options", "--no-annotate",
                "--no-header", "--no-strip-extras", "--no-python-downloads",
                "--upgrade", "--output-file", str(candidate), "--quiet",
            ], check=True)
            if "\n".join(input_header(root, name) for name in input_names) != header:
                raise ValueError(f"{lock_name} inputs changed during compilation")
            candidate.write_text(
                f"# Generated by scripts/python_locks.py with {resolver}.\n"
                + header + "\n" + candidate.read_text()
            )
            candidate.replace(current)
    validate(root)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "compile"))
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    (validate if args.command == "check" else compile_locks)(args.root)
