attributes_labels = {
    'BusinessYear': 'Business Year',
    'StateCode': 'State Code',
    'IssuerId': 'Issuer ID',
    'IssuerMarketPlaceMarketingName': 'Issuer Marketplace Marketing Name',
    'SourceName': 'Source Name',
    'VersionNum': 'Version Number',
    'ImportDate': 'Import Date',
    'BenefitPackageId': 'Benefit Package ID',
    'IssuerId2': 'Issuer ID',
    'StateCode2': 'State Code',
    'MarketCoverage': 'Market Coverage',
    'DentalOnlyPlan': 'Dental Only Plan',
    'TIN': 'Tax Identification Number',
    'StandardComponentId': 'Plan ID',
    'PlanMarketingName': 'Plan Marketing Name',
    'HIOSProductId': 'HIOS Product ID',
    'HPID': 'HPID (National Health Plan Identifier)',
    'NetworkId': 'Network ID',
    'ServiceAreaId': 'Service Area ID',
    'FormularyId': 'Formulary ID',
    'IsNewPlan': 'New/Existing Plan',
    'PlanType': 'Plan Type',
    'MetalLevel': 'Metal Level',
    'DesignType': 'Design Type',
    'UniquePlanDesign': 'Unique Plan Design',
    'QHPNonQHPTypeId': 'QHP/Non QHP',
    'IsNoticeRequiredForPregnancy': 'Notice Required for Pregnancy',
    'IsReferralRequiredForSpecialist': 'Is a Referral Required for Specialist?',
    'SpecialistRequiringReferral': 'Specialist Requiring a Referral',
    'PlanLevelExclusions': 'Plan Level Exclusions',
    'IndianPlanVariationEstimatedAdvancedPaymentAmountPerEnrollee': 'Limited Cost Sharing Plan Variation - Estimated '
                                                                    'Advanced Payment',
    'CompositeRatingOffered': 'Composite Rating Offered',
    'ChildOnlyOffering': 'Child-Only Offering',
    'ChildOnlyPlanId': 'Child Only Plan ID',
    'WellnessProgramOffered': 'Wellness Program Offered',
    'DiseaseManagementProgramsOffered': 'Disease Management Programs Offered',
    'EHBPercentTotalPremium': 'EHB Percent of Total Premium ',
    'EHBPercentPremiumS4': 'EHB Percent of Total Premium, Section 4',
    'EHBPediatricDentalApportionmentQuantity': 'EHB Apportionment for Pediatric Dental',
    'IsGuaranteedRate': 'Guaranteed Rate',
    'PlanEffectiveDate': 'Plan Effective Date',
    'PlanExpirationDate': 'Plan Expiration Date',
    'OutOfCountryCoverage': 'Out of Country Coverage',
    'OutOfCountryCoverageDescription': 'Out of Country Coverage Description',
    'OutOfServiceAreaCoverage': 'Out of Service Area Coverage',
    'OutOfServiceAreaCoverageDescription': 'Out of Service Area Coverage Description',
    'NationalNetwork': 'National Network',
    'URLForEnrollmentPayment': 'URL for Enrollment Payment',
    'FormularyURL': 'Formulary URL',
    'PlanId': 'Plan ID (Standard Component ID with Variant) ',
    'PlanVariantMarketingName': 'Plan Variant Marketing Name',
    'CSRVariationType': 'CSR Variation Type',
    'IssuerActuarialValue': 'Issuer Actuarial Value',
    'AVCalculatorOutputNumber': 'AV Calculator Output Number',
    'MedicalDrugDeductiblesIntegrated': 'Medical Drug Deductibles Integrated',
    'MedicalDrugMaximumOutofPocketIntegrated': 'Medical Drug Maximum Out of Pocket Integrated',
    'MultipleInNetworkTiers': 'Multiple In Network Tiers',
    'FirstTierUtilization': 'First Tier Utilization',
    'SecondTierUtilization': 'Second Tier Utilization',
    'SBCHavingaBabyDeductible': 'SBC Scenario, Having a Baby, Deductible',
    'SBCHavingaBabyCopayment': 'SBC Scenario, Having a Baby, Copayment',
    'SBCHavingaBabyCoinsurance': 'SBC Scenario, Having a Baby, Coinsurance',
    'SBCHavingaBabyLimit': 'SBC Scenario, Having a Baby, Limit',
    'SBCHavingDiabetesDeductible': 'SBC Scenario, Having Diabetes, Deductible',
    'SBCHavingDiabetesCopayment': 'SBC Scenario, Having Diabetes, Copayment',
    'SBCHavingDiabetesCoinsurance': 'SBC Scenario, Having Diabetes, Coinsurance',
    'SBCHavingDiabetesLimit': 'SBC Scenario, Having Diabetes, Limit',
    'SBCHavingSimplefractureDeductible': 'SBC Scenario, Treatment of a Simple Fracture, Deductible',
    'SBCHavingSimplefractureCopayment': 'SBC Scenario, Treatment of a Simple Fracture, Copayment',
    'SBCHavingSimplefractureCoinsurance': 'SBC Scenario, Treatment of a Simple Fracture, Coinsurance',
    'SBCHavingSimplefractureLimit': 'SBC Scenario, Treatment of a Simple Fracture, Limit',
    'SpecialtyDrugMaximumCoinsurance': 'Specialty Drug Maximum Coinsurance',
    'InpatientCopaymentMaximumDays': 'Inpatient Copayment Maximum Days',
    'BeginPrimaryCareCostSharingAfterNumberOfVisits': 'Begin Primary Care Cost-Sharing After Number Of Visits',
    'BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays': 'Begin Primary Care Deductible Coinsurance After '
                                                                'Number Of Copays',
    'MEHBInnTier1IndividualMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 1), Individual',
    'MEHBInnTier1FamilyMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 1), Family',
    'MEHBInnTier1FamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 1), '
                                       'Family Per Person',
    'MEHBInnTier1FamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 1), '
                                      'Family Per Group',
    'MEHBInnTier2IndividualMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 2), Individual',
    'MEHBInnTier2FamilyMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 2), Family',
    'MEHBInnTier2FamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 2), '
                                       'Family Per Person',
    'MEHBInnTier2FamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 2), '
                                      'Family Per Group',
    'MEHBOutOfNetIndividualMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Out of Network, Individual',
    'MEHBOutOfNetFamilyMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Out of Network, Family',
    'MEHBOutOfNetFamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Out of Network, Family Per '
                                       'Person',
    'MEHBOutOfNetFamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Out of Network, Family Per '
                                      'Group',
    'MEHBCombInnOonIndividualMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Combined In/Out ',
    'MEHBCombInnOonFamilyMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Combined In/Out Network, Family',
    'MEHBCombInnOonFamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Combined In/Out Network, '
                                         'Family Per Person',
    'MEHBCombInnOonFamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Combined In/Out Network, '
                                        'Family Per Group',
    'DEHBInnTier1IndividualMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 1), Individual',
    'DEHBInnTier1FamilyMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 1), Family',
    'DEHBInnTier1FamilyPerPersonMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 1), Family Per '
                                       'Person',
    'DEHBInnTier1FamilyPerGroupMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 1), Family Per '
                                      'Group',
    'DEHBInnTier2IndividualMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 2), Individual',
    'DEHBInnTier2FamilyMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 2), Family',
    'DEHBInnTier2FamilyPerPersonMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 2), Family Per '
                                       'Person',
    'DEHBInnTier2FamilyPerGroupMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 2), Family Per '
                                      'Group',
    'DEHBOutOfNetIndividualMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Out of Network, Individual',
    'DEHBOutOfNetFamilyMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Out of Network, Family',
    'DEHBOutOfNetFamilyPerPersonMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Out of Network, Family Per Person',
    'DEHBOutOfNetFamilyPerGroupMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Out of Network, Family Per Group',
    'DEHBCombInnOonIndividualMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Combined In/Out Network, Individual',
    'DEHBCombInnOonFamilyMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Combined In/Out Network, Family',
    'DEHBCombInnOonFamilyPerPersonMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Combined In/Out Network, '
                                         'Family Per Person',
    'DEHBCombInnOonFamilyPerGroupMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Combined In/Out Network, '
                                        'Family Per Group ',
    'TEHBInnTier1IndividualMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network (Tier '
                                  '1), Individual',
    'TEHBInnTier1FamilyMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network (Tier 1), '
                              'Family',
    'TEHBInnTier1FamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network ('
                                       'Tier 1), Family Per Person',
    'TEHBInnTier1FamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network ('
                                      'Tier 1), Family Per Group',
    'TEHBInnTier2IndividualMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network (Tier '
                                  '2), Individual',
    'TEHBInnTier2FamilyMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network (Tier 2), '
                              'Family',
    'TEHBInnTier2FamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network ('
                                       'Tier 2), Family Per Person',
    'TEHBInnTier2FamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network ('
                                      'Tier 2), Family Per Group',
    'TEHBOutOfNetIndividualMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), Out of Network, '
                                  'Individual',
    'TEHBOutOfNetFamilyMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), Out of Network, Family',
    'TEHBOutOfNetFamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), '
                                       'Out of Network, Family Per Person',
    'TEHBOutOfNetFamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), '
                                      'Out of Network, Family Per Group',
    'TEHBCombInnOonIndividualMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), Combined In/Out '
                                    'Network, Individual',
    'TEHBCombInnOonFamilyMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), Combined In/Out '
                                'Network, Family',
    'TEHBCombInnOonFamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), '
                                         'Combined In/Out Network, Family Per Person',
    'TEHBCombInnOonFamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), '
                                        'Combined In/Out Network, Family Per Group',
    'MEHBDedInnTier1Individual': 'Medical EHB Deductible, In Network (Tier 1), Individual',
    'MEHBDedInnTier1Family': 'Medical EHB Deductible, In Network (Tier 1), Family',
    'MEHBDedInnTier1FamilyPerPerson': 'Medical EHB Deductible, In Network (Tier 1), Family Per Person',
    'MEHBDedInnTier1FamilyPerGroup': 'Medical EHB Deductible, In Network (Tier 1), Family Per Group',
    'MEHBDedInnTier1Coinsurance': 'Medical EHB Deductible, In Network (Tier 1), Default Coinsurance',
    'MEHBDedInnTier2Individual': 'Medical EHB Deductible, In Network (Tier 2), Individual',
    'MEHBDedInnTier2Family': 'Medical EHB Deductible, In Network (Tier 2), Family',
    'MEHBDedInnTier2FamilyPerPerson': 'Medical EHB Deductible, In Network (Tier 2), Family Per Person',
    'MEHBDedInnTier2FamilyPerGroup': 'Medical EHB Deductible, In Network (Tier 2), Family Per Group',
    'MEHBDedInnTier2Coinsurance': 'Medical EHB Deductible, In Network (Tier 2), Default Coinsurance',
    'MEHBDedOutOfNetIndividual': 'Medical EHB Deductible, Out of Network, Individual',
    'MEHBDedOutOfNetFamily': 'Medical EHB Deductible, Out of Network, Family',
    'MEHBDedOutOfNetFamilyPerPerson': 'Medical EHB Deductible, Out of Network, Family Per Person',
    'MEHBDedOutOfNetFamilyPerGroup': 'Medical EHB Deductible, Out of Network, Family Per Group',
    'MEHBDedCombInnOonIndividual': 'Medical EHB Deductible, Combined In/Out of Network, Individual',
    'MEHBDedCombInnOonFamily': 'Medical EHB Deductible, Combined In/Out of Network, Family',
    'MEHBDedCombInnOonFamilyPerPerson': 'Medical EHB Deductible, Combined In/Out of Network, Family Per Person',
    'MEHBDedCombInnOonFamilyPerGroup': 'Medical EHB Deductible, Combined In/Out of Network, Family Per Group',
    'DEHBDedInnTier1Individual': 'Drug EHB Deductible, In Network (Tier 1), Individual',
    'DEHBDedInnTier1Family': 'Drug EHB Deductible, In Network (Tier 1), Family',
    'DEHBDedInnTier1FamilyPerPerson': 'Drug EHB Deductible, In Network (Tier 1), Family Per Person',
    'DEHBDedInnTier1FamilyPerGroup': 'Drug EHB Deductible, In Network (Tier 1), Family Per Group',
    'DEHBDedInnTier1Coinsurance': 'Drug EHB Deductible, In Network (Tier 1), Default Coinsurance',
    'DEHBDedInnTier2Individual': 'Drug EHB Deductible, In Network (Tier 2), Individual',
    'DEHBDedInnTier2Family': 'Drug EHB Deductible, In Network (Tier 2), Family',
    'DEHBDedInnTier2FamilyPerPerson': 'Drug EHB Deductible, In Network (Tier 2), Family Per Person',
    'DEHBDedInnTier2FamilyPerGroup': 'Drug EHB Deductible, In Network (Tier 2), Family Per Group',
    'DEHBDedInnTier2Coinsurance': 'Drug EHB Deductible, In Network (Tier 2), Default Coinsurance',
    'DEHBDedOutOfNetIndividual': 'Drug EHB Deductible, Out of Network, Individual',
    'DEHBDedOutofNetFamily': 'Drug EHB Deductible, Out of Network, Family',
    'DEHBDedOutofNetFamilyPerPerson': 'Drug EHB Deductible, Out of Network, Family Per Person',
    'DEHBDedOutofNetFamilyPerGroup': 'Drug EHB Deductible, Out of Network, Family Per Group',
    'DEHBDedCombInnOonIndividual': 'Drug EHB Deductible, Combined In/Out of Network, Individual',
    'DEHBDedCombInnOonFamily': 'Drug EHB Deductible, Combined In/Out of Network, Family',
    'DEHBDedCombInnOonFamilyPerPerson': 'Drug EHB Deductible, Combined In/Out of Network, Family Per Person',
    'DEHBDedCombInnOonFamilyPerGroup': 'Drug EHB Deductible, Combined In/Out of Network, Family Per Group',
    'TEHBDedInnTier1Individual': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Individual',
    'TEHBDedInnTier1Family': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Family',
    'TEHBDedInnTier1FamilyPerPerson': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Family Per '
                                      'Person',
    'TEHBDedInnTier1FamilyPerGroup': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Family Per Group',
    'TEHBDedInnTier1Coinsurance': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Default Coinsurance',
    'TEHBDedInnTier2Individual': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Individual',
    'TEHBDedInnTier2Family': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Family',
    'TEHBDedInnTier2FamilyPerPerson': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Family Per '
                                      'Person',
    'TEHBDedInnTier2FamilyPerGroup': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Family Per Group',
    'TEHBDedInnTier2Coinsurance': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Default Coinsurance',
    'TEHBDedOutOfNetIndividual': 'Combined Medical and Drug EHB Deductible, Out of Network, Individual',
    'TEHBDedOutofNetFamily': 'Combined Medical and Drug EHB Deductible, Out of Network, Family',
    'TEHBDedOutofNetFamilyPerPerson': 'Combined Medical and Drug EHB Deductible, Out of Network, Family Per Person',
    'TEHBDedOutofNetFamilyPerGroup': 'Combined Medical and Drug EHB Deductible, Out of Network, Family Per Group',
    'TEHBDedCombInnOonIndividual': 'Combined Medical and Drug EHB Deductible, Combined In/Out of Network, Individual',
    'TEHBDedCombInnOonFamily': 'Combined Medical and Drug EHB Deductible, Combined In/Out of Network, Family',
    'TEHBDedCombInnOonFamilyPerPerson': 'Combined Medical and Drug EHB Deductible, Combined In/Out of Network, '
                                        'Family Per Person',
    'TEHBDedCombInnOonFamilyPerGroup': 'Combined Medical and Drug EHB Deductible, Combined In/Out of Network, '
                                       'Family Per Group',
    'IsHSAEligible': 'HSA Eligible',
    'HSAOrHRAEmployerContribution': 'HSA/HRA Employer Contribution',
    'HSAOrHRAEmployerContributionAmount': 'HSA/HRA Employer Contribution Amount',
    'URLForSummaryofBenefitsCoverage': 'URL for Summary of Benefits & Coverage',
    'PlanBrochure': 'Plan Brochure',
    'RowNumber': 'Row Number',
}
