# Licensed under the HealthPorta Non-Commercial License (see LICENSE).

plan_attributes_labels_to_key = {'AV CALCULATOR OUTPUT NUMBER': 'AVCalculatorOutputNumber',
    'BEGIN PRIMARY CARE COST SHARING AFTER NUMBER OF VISITS': 'BeginPrimaryCareCostSharingAfterNumberOfVisits',
    'BEGIN PRIMARY CARE DEDUCTIBLE COINSURANCE AFTER NUMBER OF COPAYS':
        'BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays',
    'BENEFIT PACKAGE ID': 'BenefitPackageId',
    'BUSINESS YEAR': 'BusinessYear',
    'CHILD ONLY OFFERING': 'ChildOnlyOffering',
    'CHILD ONLY PLAN ID': 'ChildOnlyPlanId',
    'CSR VARIATION TYPE': 'CSRVariationType',
    'DEHB COMB INN OON FAMILY MOOP': 'DEHBCombInnOonFamilyMOOP',
    'DEHB COMB INN OON INDIVIDUAL MOOP': 'DEHBCombInnOonIndividualMOOP',
    'DEHB DED COMB INN OON FAMILY': 'DEHBDedCombInnOonFamily',
    'DEHB DED COMB INN OON INDIVIDUAL': 'DEHBDedCombInnOonIndividual',
    'DEHB DED INN TIER1 COINSURNACE': 'DEHBDedInnTier1Coinsurance',
    'DEHB DED INN TIER1 FAMILY': 'DEHBDedInnTier1Family',
    'DEHB DED INN TIER1 INDIVIDUAL': 'DEHBDedInnTier1Individual',
    'DEHB DED INN TIER2 COINSURANCE': 'DEHBDedInnTier2Coinsurance',
    'DEHB DED INN TIER2 FAMILY': 'DEHBDedInnTier2Family',
    'DEHB DED INN TIER2 INDIVIDUAL': 'DEHBDedInnTier2Individual',
    'DEHB DED OUT OF NET FAMILY': 'DEHBDedOutOfNetFamily',
    'DEHB DED OUT OF NET INDIVIDUAL': 'DEHBDedOutOfNetIndividual',
    'DEHB INN TIER 1 FAMILY MOOP': 'DEHBInnTier1FamilyMOOP',
    'DEHB INN TIER 1 INDIVIDUAL MOOP': 'DEHBInnTier1IndividualMOOP',
    'DEHB INN TIER 2 FAMILY MOOP': 'DEHBInnTier2FamilyMOOP',
    'DEHB INN TIER 2 INDIVIDUAL MOOP': 'DEHBInnTier2IndividualMOOP',
    'DEHB OUT OF NET FAMILY MOOP': 'DEHBOutOfNetFamilyMOOP',
    'DEHB OUT OF NET INDIVIDUAL MOOP': 'DEHBOutOfNetIndividualMOOP',
    'DENTAL ONLY PLAN': 'DentalOnlyPlan',
    'DISEASE MANAGEMENT PROGRAMS OFFERED': 'DiseaseManagementProgramsOffered',
    'EHB PEDIATRIC DENTAL APPORTIONMENT QUANTITY': 'EHBPediatricDentalApportionmentQuantity',
    'EHB PERCENT PREMIUM': 'EHBPercentTotalPremium',
    'FIRST TIER UTILIZATION': 'FirstTierUtilization',
    'FORMULARY ID': 'FormularyId',
    'FORMULARY URL': 'FormularyURL',
    'HIOS PRODUCT ID': 'HIOSProductId',
    'HPID': 'HPID',
    'HSA OR HRA EMPLOYER CONTRIBUTION': 'HSAOrHRAEmployerContribution',
    'HSA OR HRA EMPLOYER CONTRIBUTION AMOUNT': 'HSAOrHRAEmployerContributionAmount',
    'IMPORT DATE': 'ImportDate',
    'INPATIENT COPAYMENT MAXIMUM DAYS': 'InpatientCopaymentMaximumDays',
    'INSURANCE PLAN COMPOSITE PREMIUM AVAILABLE INDICATOR': 'CompositeRatingOffered',
    'IS GUARANTEED RATE?': 'IsGuaranteedRate',
    'IS HSA ELIGIBLE': 'IsHSAEligible',
    'IS IT A NEW PLAN': 'IsItANewPlan',
    'IS NOTICE REQUIRED FOR PREGNACY': 'IsNoticeRequiredForPregnancy',
    'IS NOTICE REQUIRED FOR PREGNANCY': 'IsNoticeRequiredForPregnancy',
    'IS REFERRAL REQUIRED FOR SPECIALIST': 'IsReferralRequiredForSpecialist',
    'ISSUER ACTUARIAL VALUE': 'IssuerActuarialValue',
    'ISSUER ID': 'IssuerId',
    'ISSUER NAME': 'IssuerName',
    'MARKET COVERAGE': 'MarketCoverage',
    'MEDICAL DRUG DEDUCTIBLES INTEGRATED': 'MedicalDrugDeductiblesIntegrated',
    'MEDICAL DRUG MAXIMUM OUT OF POCKET INTEGRATED': 'MedicalDrugMaximumOutofPocketIntegrated',
    'MEHB COMB INN OON FAMILY MOOP': 'MEHBCombInnOonFamilyMOOP',
    'MEHB COMB INN OON INDIVIDUAL MOOP': 'MEHBCombInnOonIndividualMOOP',
    'MEHB DED COMB INN OON FAMILY': 'MEHBDedCombInnOonFamily',
    'MEHB DED COMB INN OON INDIVIDUAL': 'MEHBDedCombInnOonIndividual',
    'MEHB DED INN TIER1 COINSURNACE': 'MEHBDedInnTier1Coinsurance',
    'MEHB DED INN TIER1 COINSURANCE': 'MEHBDedInnTier1Coinsurance',
    'MEHB DED INN TIER1 FAMILY': 'MEHBDedInnTier1Family',
    'MEHB DED INN TIER1 INDIVIDUAL': 'MEHBDedInnTier1Individual',
    'MEHB DED INN TIER2 COINSURANCE': 'MEHBDedInnTier2Coinsurance',
    'MEHB DED INN TIER2 FAMILY': 'MEHBDedInnTier2Family',
    'MEHB DED INN TIER2 INDIVIDUAL': 'MEHBDedInnTier2Individual',
    'MEHB DED OUT OF NET FAMILY': 'MEHBDedOutOfNetFamily',
    'MEHB DED OUT OF NET INDIVIDUAL': 'MEHBDedOutOfNetIndividual',
    'MEHB INN TIER 1 FAMILY MOOP': 'MEHBInnTier1FamilyMOOP',
    'MEHB INN TIER 1 INDIVIDUAL MOOP': 'MEHBInnTier1IndividualMOOP',
    'MEHB INN TIER 2 FAMILY MOOP': 'MEHBInnTier2FamilyMOOP',
    'MEHB INN TIER 2 INDIVIDUAL MOOP': 'MEHBInnTier2IndividualMOOP',
    'MEHB OUT OF NET FAMILY MOOP': 'MEHBOutOfNetFamilyMOOP',
    'MEHB OUT OF NET INDIVIDUAL MOOP': 'MEHBOutOfNetIndividualMOOP',
    'METAL LEVEL': 'MetalLevel',
    'MULTIPLE NETWORK TIERS': 'MultipleInNetworkTiers',
    'NATIONAL NETWORK': 'NationalNetwork',
    'NETWORK ID': 'NetworkId',
    'OUT OF COUNTRY COVERAGE': 'OutOfCountryCoverage',
    'OUT OF COUNTRY COVERAGE DESCRIPTION': 'OutOfCountryCoverageDescription',
    'OUT OF SERVICE AREA COVERAGE': 'OutOfServiceAreaCoverage',
    'OUT OF SERVICE AREA COVERAGE DESCRIPTION': 'OutOfServiceAreaCoverageDescription',
    'PLAN BROCHURE': 'PlanBrochure',
    'PLAN DESIGN TYPE': 'DesignType',
    'PLAN EFFECTIVE DATE': 'PlanEffectiveDate',
    'PLAN EXPIRATION DATE': 'PlanExpirationDate',
    'PLAN ID': 'PlanId',
    'PLAN LEVEL EXCLUSIONS': 'PlanLevelExclusions',
    'PLAN MARKETING NAME': 'PlanMarketingName',
    'PLAN TYPE': 'PlanType',
    'PLAN VARIANT MARKETING NAME': 'PlanVariantMarketingName',
    'QHP NONQHP TYPE ID': 'QHPNonQHPTypeId',
    'SBC HAVING  DIABETES COPAYMENT': 'SBCHavingDiabetesCopayment',
    'SBC HAVING A BABY COINSURANCE': 'SBCHavingaBabyCoinsurance',
    'SBC HAVING A BABY COPAYMENT': 'SBCHavingaBabyCopayment',
    'SBC HAVING A BABY DEDUCTIBLE': 'SBCHavingaBabyDeductible',
    'SBC HAVING A BABY LIMIT': 'SBCHavingaBabyLimit',
    'SBC HAVING DIABETES COINSURANCE': 'SBCHavingDiabetesCoinsurance',
    'SBC HAVING DIABETES DEDUCTIBLE': 'SBCHavingDiabetesDeductible',
    'SBC HAVING DIABETES LIMIT': 'SBCHavingDiabetesLimit',
    'SBC HAVING SIMPLE FRACTURE COINSURANCE': 'SBCHavingSimplefractureCoinsurance',
    'SBC HAVING SIMPLE FRACTURE COPAYMENT': 'SBCHavingSimplefractureCopayment',
    'SBC HAVING SIMPLE FRACTURE DEDUCTIBLE': 'SBCHavingSimplefractureDeductible',
    'SBC HAVING SIMPLE FRACTURE LIMIT': 'SBCHavingSimplefractureLimit',
    'SECOND TIER UTILIZATION': 'SecondTierUtilization',
    'SERVICE AREA ID': 'ServiceAreaId',
    'SOURCE NAME': 'SourceName',
    'SPECIALIST REQUIRING REFERRAL': 'SpecialistRequiringReferral',
    'SPECIALITY DRUG MAXIMUM COINSURANCE': 'SpecialtyDrugMaximumCoinsurance',
    'STANDARD COMPONENT ID': 'StandardComponentId',
    'STATE CODE': 'StateCode',
    'TEHB COMB INN OON FAMILY MOOP': 'TEHBCombInnOonFamilyMOOP',
    'TEHB COMB INN OON INDIVIDUAL MOOP': 'TEHBCombInnOonIndividualMOOP',
    'TEHB DED INN TIER 1 COINSURANCE': 'TEHBDedInnTier1Coinsurance',
    'TEHB DED INN TIER 1 FAMILY': 'TEHBDedInnTier1Family',
    'TEHB DED INN TIER 1 INDIVIDUAL': 'TEHBDedInnTier1Individual',
    'TEHB DED INN TIER 2 COINSURANCE': 'TEHBDedInnTier2Coinsurance',
    'TEHB DED INN TIER 2 FAMILY': 'TEHBDedInnTier2Family',
    'TEHB DED INN TIER 2 INDIVIDUAL': 'TEHBDedInnTier2Individual',
    'TEHB DED OUT COMB INN OON FAMILY': 'TEHBDedCombInnOonFamily',
    'TEHB DED OUT COMB INN OON INDIVIDUAL': 'TEHBDedCombInnOonIndividual',
    'TEHB DED OUT OF NET FAMILY': 'TEHBDedOutofNetFamily',
    'TEHB DED OUT OF NET INDIVIDUAL': 'TEHBDedOutOfNetIndividual',
    'TEHB INN TIER 1 FAMILY MOOP': 'TEHBInnTier1FamilyMOOP',
    'TEHB INN TIER 1 INDIVIDUAL MOOP': 'TEHBInnTier1IndividualMOOP',
    'TEHB INN TIER 2 FAMILY MOOP': 'TEHBInnTier2FamilyMOOP',
    'TEHB INN TIER 2 INDIVIDUAL MOOP': 'TEHBInnTier2IndividualMOOP',
    'TEHB OUT OF NET FAMILY MOOP': 'TEHBOutOfNetFamilyMOOP',
    'TEHB OUT OF NET INDIVIDUAL MOOP': 'TEHBOutOfNetIndividualMOOP',
    'TIN': 'TIN',
    'UNIQUE PLAN DESIGN': 'UniquePlanDesign',
    'URL FOR ENROLLMENT PAYMENT': 'URLForEnrollmentPayment',
    'URL FOR SUMMARY OF BENEFITS COVERAGE': 'URLForSummaryofBenefitsCoverage',
    'VERSION NUMBER': 'VersionNumber',
    'WELLNESS PROGRAM OFFERED': 'WellnessProgramOffered'}

benefits_labels = {
    "year": "Year",
    "plan_id": "Plan ID",
    "full_plan_id": "Full Plan ID",
    "benefit_name": "Benefit Name",
    "copay_inn_tier1": "Copayment In Network, Tier 1",
    "copay_inn_tier2": "Copayment In Network, Tier 2",
    "copay_outof_net": "Copayment Out of Network",
    "coins_inn_tier1": "Coinsurance In Network, Tier 1",
    "coins_inn_tier2": "Coinsurance In Network, Tier 2",
    "coins_outof_net": "Coinsurance Out of Network",
    "is_ehb": "Is EHB",
    "is_covered": "Is Covered",
    "quant_limit_on_svc": "Quantitative Limit on Service",
    "limit_unit": "Limit Unit",
    "exclusions": "Exclusions",
    "explanation": "Explanation",
    "ehb_var_reason": "EHB Variation Reason",
    "is_excl_from_inn_mo": "Is Excluded From In Network MOOP",
    "is_excl_from_oon_mo": "Is Excluded From Out of Network MOOP",
}


attributes_labels = {
    'BusinessYear': 'Business Year',
    'StateCode': 'State Code',
    'IssuerId': 'Issuer ID',
    'IssuerName': 'Issuer Name',
    'IssuerMarketPlaceMarketingName': 'Issuer Marketplace Marketing Name',
    'SourceName': 'Source Name',
    'VersionNum': 'Version Number',
    'ImportDate': 'Import Date',
    'BenefitPackageId': 'Benefit Package ID',
    'IssuerId2': 'Issuer ID',
    'StateCode2': 'State Code',
    'VersionNumber': 'Version Number',
    'MarketCoverage': 'Market Coverage',
    'DentalOnlyPlan': 'Dental Only Plan',
    'TIN': 'Tax Identification Number',
    'StandardComponentId': 'Plan ID',
    'PlanMarketingName': 'Plan Marketing Name',
    'HIOSProductId': 'HIOS Product ID',
    'HPID': 'HPID (National Health Plan Identifier)',
    'NetworkId': 'Network ID',
    'ServiceAreaId': 'Service Area ID',
    'FormularyId': 'Formulary ID',
    'IsNewPlan': 'New/Existing Plan',
    'PlanType': 'Plan Type',
    'MetalLevel': 'Metal Level',
    'DesignType': 'Design Type',
    'UniquePlanDesign': 'Unique Plan Design',
    'QHPNonQHPTypeId': 'QHP/Non QHP',
    'IsNoticeRequiredForPregnancy': 'Notice Required for Pregnancy',
    'IsReferralRequiredForSpecialist': 'Is a Referral Required for Specialist?',
    'SpecialistRequiringReferral': 'Specialist Requiring a Referral',
    'PlanLevelExclusions': 'Plan Level Exclusions',
    'IndianPlanVariationEstimatedAdvancedPaymentAmountPerEnrollee': 'Limited Cost Sharing Plan Variation - Estimated '
                                                                    'Advanced Payment',
    'CompositeRatingOffered': 'Composite Rating Offered',
    'ChildOnlyOffering': 'Child-Only Offering',
    'ChildOnlyPlanId': 'Child Only Plan ID',
    'WellnessProgramOffered': 'Wellness Program Offered',
    'DiseaseManagementProgramsOffered': 'Disease Management Programs Offered',
    'EHBPercentTotalPremium': 'EHB Percent of Total Premium ',
    'EHBPercentPremiumS4': 'EHB Percent of Total Premium, Section 4',
    'EHBPediatricDentalApportionmentQuantity': 'EHB Apportionment for Pediatric Dental',
    'IsGuaranteedRate': 'Guaranteed Rate',
    'PlanEffectiveDate': 'Plan Effective Date',
    'PlanExpirationDate': 'Plan Expiration Date',
    'OutOfCountryCoverage': 'Out of Country Coverage',
    'OutOfCountryCoverageDescription': 'Out of Country Coverage Description',
    'OutOfServiceAreaCoverage': 'Out of Service Area Coverage',
    'OutOfServiceAreaCoverageDescription': 'Out of Service Area Coverage Description',
    'NationalNetwork': 'National Network',
    'URLForEnrollmentPayment': 'URL for Enrollment Payment',
    'FormularyURL': 'Formulary URL',
    'PlanId': 'Plan ID (Standard Component ID with Variant) ',
    'PlanVariantMarketingName': 'Plan Variant Marketing Name',
    'CSRVariationType': 'CSR Variation Type',
    'IssuerActuarialValue': 'Issuer Actuarial Value',
    'AVCalculatorOutputNumber': 'AV Calculator Output Number',
    'MedicalDrugDeductiblesIntegrated': 'Medical Drug Deductibles Integrated',
    'MedicalDrugMaximumOutofPocketIntegrated': 'Medical Drug Maximum Out of Pocket Integrated',
    'MultipleInNetworkTiers': 'Multiple In Network Tiers',
    'FirstTierUtilization': 'First Tier Utilization',
    'SecondTierUtilization': 'Second Tier Utilization',
    'SBCHavingaBabyDeductible': 'SBC Scenario, Having a Baby, Deductible',
    'SBCHavingaBabyCopayment': 'SBC Scenario, Having a Baby, Copayment',
    'SBCHavingaBabyCoinsurance': 'SBC Scenario, Having a Baby, Coinsurance',
    'SBCHavingaBabyLimit': 'SBC Scenario, Having a Baby, Limit',
    'SBCHavingDiabetesDeductible': 'SBC Scenario, Having Diabetes, Deductible',
    'SBCHavingDiabetesCopayment': 'SBC Scenario, Having Diabetes, Copayment',
    'SBCHavingDiabetesCoinsurance': 'SBC Scenario, Having Diabetes, Coinsurance',
    'SBCHavingDiabetesLimit': 'SBC Scenario, Having Diabetes, Limit',
    'SBCHavingSimplefractureDeductible': 'SBC Scenario, Treatment of a Simple Fracture, Deductible',
    'SBCHavingSimplefractureCopayment': 'SBC Scenario, Treatment of a Simple Fracture, Copayment',
    'SBCHavingSimplefractureCoinsurance': 'SBC Scenario, Treatment of a Simple Fracture, Coinsurance',
    'SBCHavingSimplefractureLimit': 'SBC Scenario, Treatment of a Simple Fracture, Limit',
    'SpecialtyDrugMaximumCoinsurance': 'Specialty Drug Maximum Coinsurance',
    'InpatientCopaymentMaximumDays': 'Inpatient Copayment Maximum Days',
    'BeginPrimaryCareCostSharingAfterNumberOfVisits': 'Begin Primary Care Cost-Sharing After Number Of Visits',
    'BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays': 'Begin Primary Care Deductible Coinsurance After '
                                                                'Number Of Copays',
    'MEHBInnTier1IndividualMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 1), Individual',
    'MEHBInnTier1FamilyMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 1), Family',
    'MEHBInnTier1FamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 1), '
                                       'Family Per Person',
    'MEHBInnTier1FamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 1), '
                                      'Family Per Group',
    'MEHBInnTier2IndividualMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 2), Individual',
    'MEHBInnTier2FamilyMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 2), Family',
    'MEHBInnTier2FamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 2), '
                                       'Family Per Person',
    'MEHBInnTier2FamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, In Network (Tier 2), '
                                      'Family Per Group',
    'MEHBOutOfNetIndividualMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Out of Network, Individual',
    'MEHBOutOfNetFamilyMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Out of Network, Family',
    'MEHBOutOfNetFamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Out of Network, Family Per '
                                       'Person',
    'MEHBOutOfNetFamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Out of Network, Family Per '
                                      'Group',
    'MEHBCombInnOonIndividualMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Combined In/Out ',
    'MEHBCombInnOonFamilyMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Combined In/Out Network, Family',
    'MEHBCombInnOonFamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Combined In/Out Network, '
                                         'Family Per Person',
    'MEHBCombInnOonFamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical EHB Benefits, Combined In/Out Network, '
                                        'Family Per Group',
    'DEHBInnTier1IndividualMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 1), Individual',
    'DEHBInnTier1FamilyMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 1), Family',
    'DEHBInnTier1FamilyPerPersonMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 1), Family Per '
                                       'Person',
    'DEHBInnTier1FamilyPerGroupMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 1), Family Per '
                                      'Group',
    'DEHBInnTier2IndividualMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 2), Individual',
    'DEHBInnTier2FamilyMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 2), Family',
    'DEHBInnTier2FamilyPerPersonMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 2), Family Per '
                                       'Person',
    'DEHBInnTier2FamilyPerGroupMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, In Network (Tier 2), Family Per '
                                      'Group',
    'DEHBOutOfNetIndividualMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Out of Network, Individual',
    'DEHBOutOfNetFamilyMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Out of Network, Family',
    'DEHBOutOfNetFamilyPerPersonMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Out of Network, Family Per Person',
    'DEHBOutOfNetFamilyPerGroupMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Out of Network, Family Per Group',
    'DEHBCombInnOonIndividualMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Combined In/Out Network, Individual',
    'DEHBCombInnOonFamilyMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Combined In/Out Network, Family',
    'DEHBCombInnOonFamilyPerPersonMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Combined In/Out Network, '
                                         'Family Per Person',
    'DEHBCombInnOonFamilyPerGroupMOOP': 'Maximum Out of Pocket for Drug EHB Benefits, Combined In/Out Network, '
                                        'Family Per Group ',
    'TEHBInnTier1IndividualMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network (Tier '
                                  '1), Individual',
    'TEHBInnTier1FamilyMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network (Tier 1), '
                              'Family',
    'TEHBInnTier1FamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network ('
                                       'Tier 1), Family Per Person',
    'TEHBInnTier1FamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network ('
                                      'Tier 1), Family Per Group',
    'TEHBInnTier2IndividualMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network (Tier '
                                  '2), Individual',
    'TEHBInnTier2FamilyMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network (Tier 2), '
                              'Family',
    'TEHBInnTier2FamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network ('
                                       'Tier 2), Family Per Person',
    'TEHBInnTier2FamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), In Network ('
                                      'Tier 2), Family Per Group',
    'TEHBOutOfNetIndividualMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), Out of Network, '
                                  'Individual',
    'TEHBOutOfNetFamilyMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), Out of Network, Family',
    'TEHBOutOfNetFamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), '
                                       'Out of Network, Family Per Person',
    'TEHBOutOfNetFamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), '
                                      'Out of Network, Family Per Group',
    'TEHBCombInnOonIndividualMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), Combined In/Out '
                                    'Network, Individual',
    'TEHBCombInnOonFamilyMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), Combined In/Out '
                                'Network, Family',
    'TEHBCombInnOonFamilyPerPersonMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), '
                                         'Combined In/Out Network, Family Per Person',
    'TEHBCombInnOonFamilyPerGroupMOOP': 'Maximum Out of Pocket for Medical and Drug EHB Benefits (Total), '
                                        'Combined In/Out Network, Family Per Group',
    'MEHBDedInnTier1Individual': 'Medical EHB Deductible, In Network (Tier 1), Individual',
    'MEHBDedInnTier1Family': 'Medical EHB Deductible, In Network (Tier 1), Family',
    'MEHBDedInnTier1FamilyPerPerson': 'Medical EHB Deductible, In Network (Tier 1), Family Per Person',
    'MEHBDedInnTier1FamilyPerGroup': 'Medical EHB Deductible, In Network (Tier 1), Family Per Group',
    'MEHBDedInnTier1Coinsurance': 'Medical EHB Deductible, In Network (Tier 1), Default Coinsurance',
    'MEHBDedInnTier2Individual': 'Medical EHB Deductible, In Network (Tier 2), Individual',
    'MEHBDedInnTier2Family': 'Medical EHB Deductible, In Network (Tier 2), Family',
    'MEHBDedInnTier2FamilyPerPerson': 'Medical EHB Deductible, In Network (Tier 2), Family Per Person',
    'MEHBDedInnTier2FamilyPerGroup': 'Medical EHB Deductible, In Network (Tier 2), Family Per Group',
    'MEHBDedInnTier2Coinsurance': 'Medical EHB Deductible, In Network (Tier 2), Default Coinsurance',
    'MEHBDedOutOfNetIndividual': 'Medical EHB Deductible, Out of Network, Individual',
    'MEHBDedOutOfNetFamily': 'Medical EHB Deductible, Out of Network, Family',
    'MEHBDedOutOfNetFamilyPerPerson': 'Medical EHB Deductible, Out of Network, Family Per Person',
    'MEHBDedOutOfNetFamilyPerGroup': 'Medical EHB Deductible, Out of Network, Family Per Group',
    'MEHBDedCombInnOonIndividual': 'Medical EHB Deductible, Combined In/Out of Network, Individual',
    'MEHBDedCombInnOonFamily': 'Medical EHB Deductible, Combined In/Out of Network, Family',
    'MEHBDedCombInnOonFamilyPerPerson': 'Medical EHB Deductible, Combined In/Out of Network, Family Per Person',
    'MEHBDedCombInnOonFamilyPerGroup': 'Medical EHB Deductible, Combined In/Out of Network, Family Per Group',
    'DEHBDedInnTier1Individual': 'Drug EHB Deductible, In Network (Tier 1), Individual',
    'DEHBDedInnTier1Family': 'Drug EHB Deductible, In Network (Tier 1), Family',
    'DEHBDedInnTier1FamilyPerPerson': 'Drug EHB Deductible, In Network (Tier 1), Family Per Person',
    'DEHBDedInnTier1FamilyPerGroup': 'Drug EHB Deductible, In Network (Tier 1), Family Per Group',
    'DEHBDedInnTier1Coinsurance': 'Drug EHB Deductible, In Network (Tier 1), Default Coinsurance',
    'DEHBDedInnTier2Individual': 'Drug EHB Deductible, In Network (Tier 2), Individual',
    'DEHBDedInnTier2Family': 'Drug EHB Deductible, In Network (Tier 2), Family',
    'DEHBDedInnTier2FamilyPerPerson': 'Drug EHB Deductible, In Network (Tier 2), Family Per Person',
    'DEHBDedInnTier2FamilyPerGroup': 'Drug EHB Deductible, In Network (Tier 2), Family Per Group',
    'DEHBDedInnTier2Coinsurance': 'Drug EHB Deductible, In Network (Tier 2), Default Coinsurance',
    'DEHBDedOutOfNetIndividual': 'Drug EHB Deductible, Out of Network, Individual',
    'DEHBDedOutOfNetFamily': 'Drug EHB Deductible, Out of Network, Family',
    'DEHBDedOutOfNetFamilyPerPerson': 'Drug EHB Deductible, Out of Network, Family Per Person',
    'DEHBDedOutOfNetFamilyPerGroup': 'Drug EHB Deductible, Out of Network, Family Per Group',
    'DEHBDedCombInnOonIndividual': 'Drug EHB Deductible, Combined In/Out of Network, Individual',
    'DEHBDedCombInnOonFamily': 'Drug EHB Deductible, Combined In/Out of Network, Family',
    'DEHBDedCombInnOonFamilyPerPerson': 'Drug EHB Deductible, Combined In/Out of Network, Family Per Person',
    'DEHBDedCombInnOonFamilyPerGroup': 'Drug EHB Deductible, Combined In/Out of Network, Family Per Group',
    'TEHBDedInnTier1Individual': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Individual',
    'TEHBDedInnTier1Family': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Family',
    'TEHBDedInnTier1FamilyPerPerson': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Family Per '
                                      'Person',
    'TEHBDedInnTier1FamilyPerGroup': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Family Per Group',
    'TEHBDedInnTier1Coinsurance': 'Combined Medical and Drug EHB Deductible, In Network (Tier 1), Default Coinsurance',
    'TEHBDedInnTier2Individual': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Individual',
    'TEHBDedInnTier2Family': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Family',
    'TEHBDedInnTier2FamilyPerPerson': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Family Per '
                                      'Person',
    'TEHBDedInnTier2FamilyPerGroup': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Family Per Group',
    'TEHBDedInnTier2Coinsurance': 'Combined Medical and Drug EHB Deductible, In Network (Tier 2), Default Coinsurance',
    'TEHBDedOutOfNetIndividual': 'Combined Medical and Drug EHB Deductible, Out of Network, Individual',
    'TEHBDedOutOfNetFamily': 'Combined Medical and Drug EHB Deductible, Out of Network, Family',
    'TEHBDedOutOfNetFamilyPerPerson': 'Combined Medical and Drug EHB Deductible, Out of Network, Family Per Person',
    'TEHBDedOutOfNetFamilyPerGroup': 'Combined Medical and Drug EHB Deductible, Out of Network, Family Per Group',
    'TEHBDedCombInnOonIndividual': 'Combined Medical and Drug EHB Deductible, Combined In/Out of Network, Individual',
    'TEHBDedCombInnOonFamily': 'Combined Medical and Drug EHB Deductible, Combined In/Out of Network, Family',
    'TEHBDedCombInnOonFamilyPerPerson': 'Combined Medical and Drug EHB Deductible, Combined In/Out of Network, '
                                        'Family Per Person',
    'TEHBDedCombInnOonFamilyPerGroup': 'Combined Medical and Drug EHB Deductible, Combined In/Out of Network, '
                                       'Family Per Group',
    'IsHSAEligible': 'HSA Eligible',
    'HSAOrHRAEmployerContribution': 'HSA/HRA Employer Contribution',
    'HSAOrHRAEmployerContributionAmount': 'HSA/HRA Employer Contribution Amount',
    'URLForSummaryofBenefitsCoverage': 'URL for Summary of Benefits & Coverage',
    'PlanBrochure': 'Plan Brochure',
    'RowNumber': 'Row Number',
}